Nous allons, dans ce fichier, mettre en place l'algo de PPO pour notre agent RL.

In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
!pip install gymnasium

Requirement already satisfied: gymnasium in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (1.2.2)
Requirement already satisfied: numpy>=1.21.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gymnasium) (2.2.6)
Requirement already satisfied: cloudpickle>=1.2.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gymnasium) (3.1.2)
Requirement already satisfied: typing-extensions>=4.3.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gymnasium) (4.15.0)
Requirement already satisfied: farama-notifications>=0.0.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gymnasium) (0.0.4)

In [6]:
!pip install gym_trading_env_continuous

Exception ignored in: <_io.FileIO name=3 mode='wb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    stdout : str
              ^^^
ResourceWarning: unclosed file <_io.BufferedWriter name=3>
Exception ignored in: <_io.FileIO name=4 mode='rb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    stdout : str
              ^^^
ResourceWarning: unclosed file <_io.BufferedReader name=4>
Exception ignored in: <_io.FileIO name=5 mode='rb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    stdout : str
              ^^^
ResourceWarning: unclosed file <_io.BufferedReader name=5>

Collecting gym_trading_env_continuous
  Downloading gym_trading_env_continuous-1.0.4-py3-none-any.whl.metadata (4.9 kB)
Collecting pandas>=1.5.3 (from gym_trading_env_continuous)
  Using cached pandas-2.3.3-cp310-cp310-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.21.1 (from gym_trading_env_continuous)
  Using cached numpy-2.2.6-cp310-cp310-win_amd64.whl.metadata (60 kB)
Collecting gymnasium>=0.28.1 (from gym_trading_env_continuous)
  Downloading gymnasium-1.2.3-py3-none-any.whl.metadata (10 kB)
Collecting flask>=2.2.3 (from gym_trading_env_continuous)
  Downloading flask-3.1.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pyecharts>=2.0.2 (from gym_trading_env_continuous)
  Downloading pyecharts-2.0.9-py3-none-any.whl.metadata (1.6 kB)
Collecting ccxt==3.0.59 (from gym_trading_env_continuous)
  Downloading ccxt-3.0.59-py2.py3-none-any.whl.metadata (111 kB)
Requirement already satisfied: nest_asyncio in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gym_trading_env_continuous) (1.6.0)
Requirement already satisfied: setuptools>=60.9.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ccxt==3.0.59->gym_trading_env_continuous) (65.5.0)
Collecting certifi>=2018.1.18 (from ccxt==3.0.59->gym_trading_env_continuous)
  Downloading certifi-2025.11.12-py3-none-any.whl.metadata (2.5 kB)
Collecting requests>=2.18.4 (from ccxt==3.0.59->gym_trading_env_continuous)
  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting cryptography>=2.6.1 (from ccxt==3.0.59->gym_trading_env_continuous)
  Downloading cryptography-46.0.3-cp38-abi3-win_amd64.whl.metadata (5.7 kB)
Collecting aiohttp>=3.8 (from ccxt==3.0.59->gym_trading_env_continuous)
  Downloading aiohttp-3.13.2-cp310-cp310-win_amd64.whl.metadata (8.4 kB)
Collecting aiodns>=1.1.1 (from ccxt==3.0.59->gym_trading_env_continuous)
  Downloading aiodns-3.6.1-py3-none-any.whl.metadata (5.8 kB)
Collecting yarl>=1.7.2 (from ccxt==3.0.59->gym_trading_env_continuous)
  Downloading yarl-1.22.0-cp310-cp310-win_amd64.whl.metadata (77 kB)
Collecting pycares<5,>=4.9.0 (from aiodns>=1.1.1->ccxt==3.0.59->gym_trading_env_continuous)
  Downloading pycares-4.11.0-cp310-cp310-win_amd64.whl.metadata (4.8 kB)
Collecting cffi>=1.5.0 (from pycares<5,>=4.9.0->aiodns>=1.1.1->ccxt==3.0.59->gym_trading_env_continuous)
  Downloading cffi-2.0.0-cp310-cp310-win_amd64.whl.metadata (2.6 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp>=3.8->ccxt==3.0.59->gym_trading_env_continuous)
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp>=3.8->ccxt==3.0.59->gym_trading_env_continuous)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting async-timeout<6.0,>=4.0 (from aiohttp>=3.8->ccxt==3.0.59->gym_trading_env_continuous)
  Downloading async_timeout-5.0.1-py3-none-any.whl.metadata (5.1 kB)
Collecting attrs>=17.3.0 (from aiohttp>=3.8->ccxt==3.0.59->gym_trading_env_continuous)
  Using cached attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Collecting frozenlist>=1.1.1 (from aiohttp>=3.8->ccxt==3.0.59->gym_trading_env_continuous)
  Downloading frozenlist-1.8.0-cp310-cp310-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp>=3.8->ccxt==3.0.59->gym_trading_env_continuous)
  Downloading multidict-6.7.0-cp310-cp310-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp>=3.8->ccxt==3.0.59->gym_trading_env_continuous)
  Downloading propcache-0.4.1-cp310-cp310-win_amd64.whl.metadata (14 kB)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from multidict<7.0,>=4.5->aiohttp>=3.8->ccxt==3.0.59->gym_trading_env_continuous) (4.15.0)
Collecting idna>=2.0 (from yarl>=1.7.2->ccxt==3.0.59->gym_trading_env_continuous)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting pycparser (from cffi>=1.5.0->pycares<5,>=4.9.0->aiodns>=1.1.1->ccxt==3.0.59->gym_trading_env_continuous)
  Downloading pycparser-2.23-py3-none-any.whl.metadata (993 bytes)
Collecting blinker>=1.9.0 (from flask>=2.2.3->gym_trading_env_continuous)
  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting click>=8.1.3 (from flask>=2.2.3->gym_trading_env_continuous)
  Downloading click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Collecting itsdangerous>=2.2.0 (from flask>=2.2.3->gym_trading_env_continuous)
  Downloading itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting jinja2>=3.1.2 (from flask>=2.2.3->gym_trading_env_continuous)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting markupsafe>=2.1.1 (from flask>=2.2.3->gym_trading_env_continuous)
  Using cached markupsafe-3.0.3-cp310-cp310-win_amd64.whl.metadata (2.8 kB)
Collecting werkzeug>=3.1.0 (from flask>=2.2.3->gym_trading_env_continuous)
  Downloading werkzeug-3.1.4-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: colorama in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from click>=8.1.3->flask>=2.2.3->gym_trading_env_continuous) (0.4.6)
Collecting cloudpickle>=1.2.0 (from gymnasium>=0.28.1->gym_trading_env_continuous)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting farama-notifications>=0.0.1 (from gymnasium>=0.28.1->gym_trading_env_continuous)
  Downloading Farama_Notifications-0.0.4-py3-none-any.whl.metadata (558 bytes)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas>=1.5.3->gym_trading_env_continuous) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas>=1.5.3->gym_trading_env_continuous)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas>=1.5.3->gym_trading_env_continuous)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting prettytable (from pyecharts>=2.0.2->gym_trading_env_continuous)
  Downloading prettytable-3.17.0-py3-none-any.whl.metadata (34 kB)
Collecting simplejson (from pyecharts>=2.0.2->gym_trading_env_continuous)
  Downloading simplejson-3.20.2-cp310-cp310-win_amd64.whl.metadata (3.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.3->gym_trading_env_continuous) (1.17.0)
Collecting charset_normalizer<4,>=2 (from requests>=2.18.4->ccxt==3.0.59->gym_trading_env_continuous)
  Using cached charset_normalizer-3.4.4-cp310-cp310-win_amd64.whl.metadata (38 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.18.4->ccxt==3.0.59->gym_trading_env_continuous)
  Downloading urllib3-2.6.2-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: wcwidth in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from prettytable->pyecharts>=2.0.2->gym_trading_env_continuous) (0.2.14)
Downloading gym_trading_env_continuous-1.0.4-py3-none-any.whl (19 kB)
Downloading ccxt-3.0.59-py2.py3-none-any.whl (3.6 MB)
   ---------------------------------------- 0.0/3.6 MB ? eta -:--:--
   ----------- ---------------------------- 1.0/3.6 MB 5.6 MB/s eta 0:00:01
   ----------------------- ---------------- 2.1/3.6 MB 5.6 MB/s eta 0:00:01
   ----------------------------- ---------- 2.6/3.6 MB 4.1 MB/s eta 0:00:01
   ------------------------------------- -- 3.4/3.6 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 3.6/3.6 MB 4.0 MB/s  0:00:00
Downloading aiodns-3.6.1-py3-none-any.whl (8.0 kB)
Downloading pycares-4.11.0-cp310-cp310-win_amd64.whl (144 kB)
Downloading aiohttp-3.13.2-cp310-cp310-win_amd64.whl (455 kB)
Downloading async_timeout-5.0.1-py3-none-any.whl (6.2 kB)
Downloading multidict-6.7.0-cp310-cp310-win_amd64.whl (46 kB)
Downloading yarl-1.22.0-cp310-cp310-win_amd64.whl (86 kB)
Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Using cached attrs-25.4.0-py3-none-any.whl (67 kB)
Downloading certifi-2025.11.12-py3-none-any.whl (159 kB)
Downloading cffi-2.0.0-cp310-cp310-win_amd64.whl (182 kB)
Downloading cryptography-46.0.3-cp38-abi3-win_amd64.whl (3.5 MB)
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   -------- ------------------------------- 0.8/3.5 MB 2.6 MB/s eta 0:00:02
   ----------- ---------------------------- 1.0/3.5 MB 2.6 MB/s eta 0:00:01
   ----------------- ---------------------- 1.6/3.5 MB 2.5 MB/s eta 0:00:01
   ----------------------- ---------------- 2.1/3.5 MB 2.4 MB/s eta 0:00:01
   -------------------------------- ------- 2.9/3.5 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 3.4/3.5 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 3.5/3.5 MB 2.4 MB/s  0:00:01
Downloading flask-3.1.2-py3-none-any.whl (103 kB)
Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Downloading click-8.3.1-py3-none-any.whl (108 kB)
Downloading frozenlist-1.8.0-cp310-cp310-win_amd64.whl (43 kB)
Downloading gymnasium-1.2.3-py3-none-any.whl (952 kB)
   ---------------------------------------- 0.0/952.1 kB ? eta -:--:--
   ---------------------- ----------------- 524.3/952.1 kB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 952.1/952.1 kB 2.8 MB/s  0:00:00
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading Farama_Notifications-0.0.4-py3-none-any.whl (2.5 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Downloading itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached markupsafe-3.0.3-cp310-cp310-win_amd64.whl (15 kB)
Downloading numpy-2.2.6-cp310-cp310-win_amd64.whl (12.9 MB)
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
    --------------------------------------- 0.3/12.9 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.9 MB 2.6 MB/s eta 0:00:05
   ---- ----------------------------------- 1.3/12.9 MB 2.6 MB/s eta 0:00:05
   ----- ---------------------------------- 1.8/12.9 MB 2.6 MB/s eta 0:00:05
   ------- -------------------------------- 2.4/12.9 MB 2.7 MB/s eta 0:00:04
   --------- ------------------------------ 3.1/12.9 MB 2.8 MB/s eta 0:00:04
   ------------ --------------------------- 3.9/12.9 MB 2.9 MB/s eta 0:00:04
   ------------- -------------------------- 4.5/12.9 MB 2.9 MB/s eta 0:00:03
   ---------------- ----------------------- 5.2/12.9 MB 3.1 MB/s eta 0:00:03
   ------------------- -------------------- 6.3/12.9 MB 3.2 MB/s eta 0:00:03
   --------------------- ------------------ 7.1/12.9 MB 3.2 MB/s eta 0:00:02
   ------------------------ --------------- 7.9/12.9 MB 3.3 MB/s eta 0:00:02
   --------------------------- ------------ 8.9/12.9 MB 3.4 MB/s eta 0:00:02
   ------------------------------ --------- 9.7/12.9 MB 3.5 MB/s eta 0:00:01
   --------------------------------- ------ 10.7/12.9 MB 3.6 MB/s eta 0:00:01
   ----------------------------------- ---- 11.5/12.9 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.9 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 3.6 MB/s  0:00:03
Using cached pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
Downloading propcache-0.4.1-cp310-cp310-win_amd64.whl (41 kB)
Downloading pyecharts-2.0.9-py3-none-any.whl (153 kB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached requests-2.32.5-py3-none-any.whl (64 kB)
Using cached charset_normalizer-3.4.4-cp310-cp310-win_amd64.whl (107 kB)
Downloading urllib3-2.6.2-py3-none-any.whl (131 kB)
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Downloading werkzeug-3.1.4-py3-none-any.whl (224 kB)
Downloading prettytable-3.17.0-py3-none-any.whl (34 kB)
Downloading pycparser-2.23-py3-none-any.whl (118 kB)
Downloading simplejson-3.20.2-cp310-cp310-win_amd64.whl (76 kB)
Installing collected packages: pytz, farama-notifications, urllib3, tzdata, simplejson, pycparser, propcache, prettytable, numpy, multidict, markupsafe, itsdangerous, idna, frozenlist, cloudpickle, click, charset_normalizer, certifi, blinker, attrs, async-timeout, aiohappyeyeballs, yarl, werkzeug, requests, pandas, jinja2, gymnasium, cffi, aiosignal, pyecharts, pycares, flask, cryptography, aiohttp, aiodns, ccxt, gym_trading_env_continuous

   ----------------------------------------  0/38 [pytz]
   ----------------------------------------  0/38 [pytz]
   ----------------------------------------  0/38 [pytz]
   ----------------------------------------  0/38 [pytz]
   ----------------------------------------  0/38 [pytz]
   ----------------------------------------  0/38 [pytz]
   - --------------------------------------  1/38 [farama-notifications]
   -- -------------------------------------  2/38 [urllib3]
   -- -------------------------------------  2/38 [urllib3]
   -- -------------------------------------  2/38 [urllib3]
   -- -------------------------------------  2/38 [urllib3]
   -- -------------------------------------  2/38 [urllib3]
   -- -------------------------------------  2/38 [urllib3]
   -- -------------------------------------  2/38 [urllib3]
   -- -------------------------------------  2/38 [urllib3]
   -- -------------------------------------  2/38 [urllib3]
   -- -------------------------------------  2/38 [urllib3]
   -- -------------------------------------  2/38 [urllib3]
   -- -------------------------------------  2/38 [urllib3]
   -- -------------------------------------  2/38 [urllib3]
   -- -------------------------------------  2/38 [urllib3]
   --- ------------------------------------  3/38 [tzdata]
   --- ------------------------------------  3/38 [tzdata]
   --- ------------------------------------  3/38 [tzdata]
   --- ------------------------------------  3/38 [tzdata]
   --- ------------------------------------  3/38 [tzdata]
   ---- -----------------------------------  4/38 [simplejson]
   ---- -----------------------------------  4/38 [simplejson]
   ---- -----------------------------------  4/38 [simplejson]
   ---- -----------------------------------  4/38 [simplejson]
   ---- -----------------------------------  4/38 [simplejson]
   ---- -----------------------------------  4/38 [simplejson]
   ---- -----------------------------------  4/38 [simplejson]
   ---- -----------------------------------  4/38 [simplejson]
   ---- -----------------------------------  4/38 [simplejson]
   ---- -----------------------------------  4/38 [simplejson]
   ---- -----------------------------------  4/38 [simplejson]
   ---- -----------------------------------  4/38 [simplejson]
   ---- -----------------------------------  4/38 [simplejson]
   ---- -----------------------------------  4/38 [simplejson]
   ----- ----------------------------------  5/38 [pycparser]
   ----- ----------------------------------  5/38 [pycparser]
   ----- ----------------------------------  5/38 [pycparser]
   ----- ----------------------------------  5/38 [pycparser]
   ----- ----------------------------------  5/38 [pycparser]
   ----- ----------------------------------  5/38 [pycparser]
   ----- ----------------------------------  5/38 [pycparser]
   ----- ----------------------------------  5/38 [pycparser]
   ------ ---------------------------------  6/38 [propcache]
   ------- --------------------------------  7/38 [prettytable]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]
   -------- -------------------------------  8/38 [numpy]

In [7]:
pip install "numpy<2.0"

Exception ignored in: <_io.FileIO name=3 mode='wb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    stdout : str
              ^^^
ResourceWarning: unclosed file <_io.BufferedWriter name=3>
Exception ignored in: <_io.FileIO name=4 mode='rb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    stdout : str
              ^^^
ResourceWarning: unclosed file <_io.BufferedReader name=4>
Exception ignored in: <_io.FileIO name=5 mode='rb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    stdout : str
              ^^^
ResourceWarning: unclosed file <_io.BufferedReader name=5>

Collecting numpy<2.0
  Downloading numpy-1.26.4-cp310-cp310-win_amd64.whl.metadata (61 kB)
Downloading numpy-1.26.4-cp310-cp310-win_amd64.whl (15.8 MB)
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ------- -------------------------------- 2.9/15.8 MB 15.2 MB/s eta 0:00:01
   --------------- ------------------------ 6.3/15.8 MB 16.1 MB/s eta 0:00:01
   ------------------------- -------------- 10.2/15.8 MB 16.8 MB/s eta 0:00:01
   ---------------------------------- ----- 13.6/15.8 MB 16.8 MB/s eta 0:00:01
   ---------------------------------------- 15.8/15.8 MB 15.1 MB/s  0:00:01
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.2.6
    Uninstalling numpy-2.2.6:
      Successfully uninstalled numpy-2.2.6
Successfully installed numpy-1.26.4
Note: you may need to restart the kernel to use updated packages.

In [9]:
!pip install "stable-baselines3[extra]" wandb pandas plotly notebook

Exception ignored in: <_io.FileIO name=3 mode='wb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    stdout : str
              ^^^
ResourceWarning: unclosed file <_io.BufferedWriter name=3>
Exception ignored in: <_io.FileIO name=4 mode='rb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    stdout : str
              ^^^
ResourceWarning: unclosed file <_io.BufferedReader name=4>
Exception ignored in: <_io.FileIO name=5 mode='rb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    stdout : str
              ^^^
ResourceWarning: unclosed file <_io.BufferedReader name=5>

Collecting wandb
  Using cached wandb-0.23.1-py3-none-win_amd64.whl.metadata (12 kB)
Requirement already satisfied: pandas in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (2.3.3)
Collecting plotly
  Using cached plotly-6.5.0-py3-none-any.whl.metadata (8.5 kB)
Collecting notebook
  Using cached notebook-7.5.1-py3-none-any.whl.metadata (10 kB)
Collecting stable-baselines3[extra]
  Downloading stable_baselines3-2.7.1-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: gymnasium<1.3.0,>=0.29.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from stable-baselines3[extra]) (1.2.3)
Requirement already satisfied: numpy<3.0,>=1.20 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from stable-baselines3[extra]) (1.26.4)
Collecting torch<3.0,>=2.3 (from stable-baselines3[extra])
  Downloading torch-2.9.1-cp310-cp310-win_amd64.whl.metadata (30 kB)
Requirement already satisfied: cloudpickle in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from stable-baselines3[extra]) (3.1.2)
Collecting matplotlib (from stable-baselines3[extra])
  Downloading matplotlib-3.10.8-cp310-cp310-win_amd64.whl.metadata (52 kB)
Collecting opencv-python (from stable-baselines3[extra])
  Downloading opencv_python-4.12.0.88-cp37-abi3-win_amd64.whl.metadata (19 kB)
Collecting pygame (from stable-baselines3[extra])
  Downloading pygame-2.6.1-cp310-cp310-win_amd64.whl.metadata (13 kB)
Collecting tensorboard>=2.9.1 (from stable-baselines3[extra])
  Using cached tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: psutil in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from stable-baselines3[extra]) (7.1.3)
Collecting tqdm (from stable-baselines3[extra])
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting rich (from stable-baselines3[extra])
  Using cached rich-14.2.0-py3-none-any.whl.metadata (18 kB)
Collecting ale-py>=0.9.0 (from stable-baselines3[extra])
  Downloading ale_py-0.11.2-cp310-cp310-win_amd64.whl.metadata (9.2 kB)
Collecting pillow (from stable-baselines3[extra])
  Downloading pillow-12.0.0-cp310-cp310-win_amd64.whl.metadata (9.0 kB)
Requirement already satisfied: typing-extensions>=4.3.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gymnasium<1.3.0,>=0.29.1->stable-baselines3[extra]) (4.15.0)
Requirement already satisfied: farama-notifications>=0.0.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gymnasium<1.3.0,>=0.29.1->stable-baselines3[extra]) (0.0.4)
Collecting filelock (from torch<3.0,>=2.3->stable-baselines3[extra])
  Downloading filelock-3.20.1-py3-none-any.whl.metadata (2.1 kB)
Collecting sympy>=1.13.3 (from torch<3.0,>=2.3->stable-baselines3[extra])
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch<3.0,>=2.3->stable-baselines3[extra])
  Using cached networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: jinja2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from torch<3.0,>=2.3->stable-baselines3[extra]) (3.1.6)
Collecting fsspec>=0.8.5 (from torch<3.0,>=2.3->stable-baselines3[extra])
  Downloading fsspec-2025.12.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: click>=8.0.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from wandb) (8.3.1)
Collecting gitpython!=3.1.29,>=1.0.0 (from wandb)
  Using cached gitpython-3.1.45-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from wandb) (25.0)
Requirement already satisfied: platformdirs in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from wandb) (4.5.1)
Collecting protobuf!=4.21.0,!=5.28.0,<7,>=3.19.0 (from wandb)
  Downloading protobuf-6.33.2-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Collecting pydantic<3 (from wandb)
  Downloading pydantic-2.12.5-py3-none-any.whl.metadata (90 kB)
Collecting pyyaml (from wandb)
  Using cached pyyaml-6.0.3-cp310-cp310-win_amd64.whl.metadata (2.4 kB)
Requirement already satisfied: requests<3,>=2.0.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from wandb) (2.32.5)
Collecting sentry-sdk>=2.0.0 (from wandb)
  Downloading sentry_sdk-2.48.0-py2.py3-none-any.whl.metadata (10 kB)
Collecting annotated-types>=0.6.0 (from pydantic<3->wandb)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.5 (from pydantic<3->wandb)
  Downloading pydantic_core-2.41.5-cp310-cp310-win_amd64.whl.metadata (7.4 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3->wandb)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from requests<3,>=2.0.0->wandb) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from requests<3,>=2.0.0->wandb) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from requests<3,>=2.0.0->wandb) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from requests<3,>=2.0.0->wandb) (2025.11.12)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas) (2025.3)
Collecting narwhals>=1.15.1 (from plotly)
  Downloading narwhals-2.14.0-py3-none-any.whl.metadata (13 kB)
Collecting jupyter-server<3,>=2.4.0 (from notebook)
  Downloading jupyter_server-2.17.0-py3-none-any.whl.metadata (8.5 kB)
Collecting jupyterlab-server<3,>=2.28.0 (from notebook)
  Downloading jupyterlab_server-2.28.0-py3-none-any.whl.metadata (5.9 kB)
Collecting jupyterlab<4.6,>=4.5.1 (from notebook)
  Downloading jupyterlab-4.5.1-py3-none-any.whl.metadata (16 kB)
Collecting notebook-shim<0.3,>=0.2 (from notebook)
  Downloading notebook_shim-0.2.4-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: tornado>=6.2.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from notebook) (6.5.4)
Collecting anyio>=3.1.0 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading anyio-4.12.0-py3-none-any.whl.metadata (4.3 kB)
Collecting argon2-cffi>=21.1 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading argon2_cffi-25.1.0-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: jupyter-client>=7.4.4 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (8.7.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (5.9.1)
Collecting jupyter-events>=0.11.0 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading jupyter_events-0.12.0-py3-none-any.whl.metadata (5.8 kB)
Collecting jupyter-server-terminals>=0.4.4 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading jupyter_server_terminals-0.5.3-py3-none-any.whl.metadata (5.6 kB)
Collecting nbconvert>=6.4.4 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading nbconvert-7.16.6-py3-none-any.whl.metadata (8.5 kB)
Collecting nbformat>=5.3.0 (from jupyter-server<3,>=2.4.0->notebook)
  Using cached nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Collecting overrides>=5.0 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Collecting prometheus-client>=0.9 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading prometheus_client-0.23.1-py3-none-any.whl.metadata (1.9 kB)
Collecting pywinpty>=2.0.1 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading pywinpty-3.0.2-cp310-cp310-win_amd64.whl.metadata (5.7 kB)
Requirement already satisfied: pyzmq>=24 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (27.1.0)
Collecting send2trash>=1.8.2 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading Send2Trash-1.8.3-py3-none-any.whl.metadata (4.0 kB)
Collecting terminado>=0.8.3 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading terminado-0.18.1-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: traitlets>=5.6.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (5.14.3)
Collecting websocket-client>=1.7 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Collecting async-lru>=1.0.0 (from jupyterlab<4.6,>=4.5.1->notebook)
  Downloading async_lru-2.0.5-py3-none-any.whl.metadata (4.5 kB)
Collecting httpx<1,>=0.25.0 (from jupyterlab<4.6,>=4.5.1->notebook)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: ipykernel!=6.30.0,>=6.5.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from jupyterlab<4.6,>=4.5.1->notebook) (7.1.0)
Collecting jupyter-lsp>=2.0.0 (from jupyterlab<4.6,>=4.5.1->notebook)
  Downloading jupyter_lsp-2.3.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: setuptools>=41.1.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from jupyterlab<4.6,>=4.5.1->notebook) (65.5.0)
Collecting tomli>=1.2.2 (from jupyterlab<4.6,>=4.5.1->notebook)
  Downloading tomli-2.3.0-py3-none-any.whl.metadata (10 kB)
Collecting httpcore==1.* (from httpx<1,>=0.25.0->jupyterlab<4.6,>=4.5.1->notebook)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab<4.6,>=4.5.1->notebook)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting babel>=2.10 (from jupyterlab-server<3,>=2.28.0->notebook)
  Downloading babel-2.17.0-py3-none-any.whl.metadata (2.0 kB)
Collecting json5>=0.9.0 (from jupyterlab-server<3,>=2.28.0->notebook)
  Downloading json5-0.12.1-py3-none-any.whl.metadata (36 kB)
Collecting jsonschema>=4.18.0 (from jupyterlab-server<3,>=2.28.0->notebook)
  Using cached jsonschema-4.25.1-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook) (1.3.1)
Collecting argon2-cffi-bindings (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook)
  Downloading argon2_cffi_bindings-25.1.0-cp39-abi3-win_amd64.whl.metadata (7.5 kB)
Requirement already satisfied: colorama in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from click>=8.0.1->wandb) (0.4.6)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.29,>=1.0.0->wandb)
  Using cached gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb)
  Using cached smmap-5.0.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: comm>=0.1.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.1->notebook) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.1->notebook) (1.8.19)
Requirement already satisfied: ipython>=7.23.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.1->notebook) (8.37.0)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.1->notebook) (0.2.1)
Requirement already satisfied: nest-asyncio>=1.4 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.1->notebook) (1.6.0)
Requirement already satisfied: decorator in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.1->notebook) (5.2.1)
Requirement already satisfied: jedi>=0.16 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.1->notebook) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.1->notebook) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.1->notebook) (2.19.2)
Requirement already satisfied: stack_data in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.1->notebook) (0.6.3)
Requirement already satisfied: wcwidth in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.1->notebook) (0.2.14)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.1->notebook) (0.8.5)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from jinja2->torch<3.0,>=2.3->stable-baselines3[extra]) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook) (25.4.0)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook)
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook)
  Downloading referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.7.1 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook)
  Downloading rpds_py-0.30.0-cp310-cp310-win_amd64.whl.metadata (4.2 kB)
Collecting python-json-logger>=2.0.4 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook)
  Downloading python_json_logger-4.0.0-py3-none-any.whl.metadata (4.0 kB)
Collecting rfc3339-validator (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook)
  Downloading rfc3339_validator-0.1.4-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting rfc3986-validator>=0.1.1 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook)
  Downloading rfc3986_validator-0.1.1-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting fqdn (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook)
  Downloading fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting isoduration (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook)
  Downloading isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
Collecting jsonpointer>1.13 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook)
  Downloading jsonpointer-3.0.0-py2.py3-none-any.whl.metadata (2.3 kB)
Collecting rfc3987-syntax>=1.1.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook)
  Downloading rfc3987_syntax-1.1.0-py3-none-any.whl.metadata (7.7 kB)
Collecting uri-template (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook)
  Downloading uri_template-1.3.0-py3-none-any.whl.metadata (8.8 kB)
Collecting webcolors>=24.6.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook)
  Downloading webcolors-25.10.0-py3-none-any.whl.metadata (2.2 kB)
Collecting beautifulsoup4 (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook)
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting bleach!=5.0.0 (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook)
  Downloading bleach-6.3.0-py3-none-any.whl.metadata (31 kB)
Collecting defusedxml (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook)
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting jupyterlab-pygments (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook)
  Downloading jupyterlab_pygments-0.3.0-py3-none-any.whl.metadata (4.4 kB)
Collecting mistune<4,>=2.0.3 (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook)
  Downloading mistune-3.1.4-py3-none-any.whl.metadata (1.8 kB)
Collecting nbclient>=0.5.0 (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook)
  Downloading nbclient-0.10.3-py3-none-any.whl.metadata (8.3 kB)
Collecting pandocfilters>=1.4.1 (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook)
  Downloading pandocfilters-1.5.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting webencodings (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook)
  Using cached webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting tinycss2<1.5,>=1.1.0 (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook)
  Downloading tinycss2-1.4.0-py3-none-any.whl.metadata (3.0 kB)
Collecting fastjsonschema>=2.15 (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->notebook)
  Using cached fastjsonschema-2.21.2-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: six>=1.5 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [10]:
!pip install git+https://github.com/twopirllc/pandas-ta.git@development

  Running command git clone --filter=blob:none --quiet https://github.com/twopirllc/pandas-ta.git 'C:\Users\mathi\AppData\Local\Temp\pip-req-build-1boh1nqd'
  remote: Repository not found.
  fatal: repository 'https://github.com/twopirllc/pandas-ta.git/' not found
  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/twopirllc/pandas-ta.git 'C:\Users\mathi\AppData\Local\Temp\pip-req-build-1boh1nqd' did not run successfully.
  │ exit code: 128
  ╰─> No available output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed to build 'git+https://github.com/twopirllc/pandas-ta.git@development' when git clone --filter=blob:none --quiet https://github.com/twopirllc/pandas-ta.git 'c:\users\mathi\appdata\local\temp\pip-req-build-1boh1nqd'
Exception ignored in: <_io.FileIO name=3 mode='wb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    stdout : str
              ^^^
ResourceWarning: unclosed file <_io.BufferedWriter name=3>
Exception ignored in: <_io.FileIO name=4 mode='rb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    stdout : str
              ^^^
ResourceWarning: unclosed file <_io.BufferedReader name=4>
Exception ignored in: <_io.FileIO name=5 mode='rb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    stdout : str
              ^^^
ResourceWarning: unclosed file <_io.BufferedReader name=5>

Collecting git+https://github.com/twopirllc/pandas-ta.git@development
  Cloning https://github.com/twopirllc/pandas-ta.git (to revision development) to c:\users\mathi\appdata\local\temp\pip-req-build-1boh1nqd

In [2]:
!pip install ta

Collecting ta
  Downloading ta-0.11.0.tar.gz (25 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ta) (2.2.6)
Requirement already satisfied: pandas in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ta) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas->ta) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas->ta) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas->ta) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas->ta) (1.17.0)
Building wheels for collected packages: ta
  Building wheel for ta (pyproject.toml): started
  Building wheel for ta (pyproject.toml): finished with status 'done'
  Created wheel for ta: filename=ta-0.11.0-py3-none-any.whl size=29497 sha256=1b02cf8ddd51c48daf3a9917215ee6047d5839052d43b7578b10c36672e950ff
  Stored in directory: c:\users\mathi\appdata\local\pip\cache\wheels\5f\67\4f\8a9f252836e053e532c6587a3230bc72a4deb16b03a829610b
Successfully built ta
Installing collected packages: ta
Successfully installed ta-0.11.0

In [8]:
!pip install "stable-baselines3[extra]" wandb pandas plotly notebook pandas_ta

ERROR: Ignored the following versions that require a different python version: 0.4.67b0 Requires-Python >=3.12; 0.4.71b0 Requires-Python >=3.12
ERROR: Could not find a version that satisfies the requirement pandas_ta (from versions: none)
ERROR: No matching distribution found for pandas_ta
Exception ignored in: <_io.FileIO name=3 mode='wb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    stdout : str
              ^^^
ResourceWarning: unclosed file <_io.BufferedWriter name=3>
Exception ignored in: <_io.FileIO name=4 mode='rb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    stdout : str
              ^^^
ResourceWarning: unclosed file <_io.BufferedReader name=4>
Exception ignored in: <_io.FileIO name=5 mode='rb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    stdout : str
              ^^^
ResourceWarning: unclosed file <_io.BufferedReader name=5>

Collecting wandb
  Downloading wandb-0.23.1-py3-none-win_amd64.whl.metadata (12 kB)
Requirement already satisfied: pandas in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (2.3.3)
Collecting plotly
  Downloading plotly-6.5.0-py3-none-any.whl.metadata (8.5 kB)
Collecting notebook
  Downloading notebook-7.5.1-py3-none-any.whl.metadata (10 kB)

In [1]:
import numpy as np
import pandas as pd
import gymnasium as gym
import gym_trading_env
import wandb
from wandb.integration.sb3 import WandbCallback
from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.env_checker import check_env
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import os

In [2]:
os.environ["WANDB_ERROR_REPORTING"] = "False" 
os.environ["WANDB_CONSOLE"] = "off"

In [3]:
def preprocess(df):
    df = df.sort_index()
    df = df.dropna()
    df = df.drop_duplicates()

    df['feature_close'] = (df['close'] - df['close'].mean()) / df['close'].std()

    return df

df = preprocess(pd.read_pickle('./data/yfinance-AAPL-1h.pkl'))
df.head(20)

,open,high,low,close,volume,date_close,feature_close
date_open,,,,,,,
2023-11-21 14:30:00,191.410004,191.520004,190.270004,190.347504,8992766,2023-11-21 15:30:00,-0.953609
2023-11-21 15:30:00,190.350006,190.470001,189.740005,189.942001,5681421,2023-11-21 16:30:00,-0.969213
2023-11-21 16:30:00,189.940002,190.320007,189.830002,190.274994,3359800,2023-11-21 17:30:00,-0.956399
2023-11-21 17:30:00,190.276993,190.600006,190.039993,190.119995,3112369,2023-11-21 18:30:00,-0.962363
2023-11-21 18:30:00,190.119995,190.615005,190.085007,190.380005,2874142,2023-11-21 19:30:00,-0.952358
2023-11-21 19:30:00,190.382797,190.710007,190.289993,190.649994,3442863,2023-11-21 20:30:00,-0.941969
2023-11-21 20:30:00,190.645004,190.729996,190.289993,190.660004,5535871,2023-11-21 21:30:00,-0.941583
2023-11-22 14:30:00,192.360001,192.929993,191.429993,191.931503,11546645,2023-11-22 15:30:00,-0.892655
2023-11-22 15:30:00,191.949997,192.369995,191.389999,191.660004,4786188,2023-11-22 16:30:00,-0.903103
2023-11-22 16:30:00,191.660004,191.960007,191.479996,191.914993,3340080,2023-11-22 17:30:00,-0.893291
2023-11-22 17:30:00,191.914993,192.089996,191.639999,192.005005,3467320,2023-11-22 18:30:00,-0.889827
2023-11-22 18:30:00,192.009995,192.030304,191.490005,191.634995,3409564,2023-11-22 19:30:00,-0.904065
2023-11-22 19:30:00,191.639999,191.639999,190.824997,191.512497,3992146,2023-11-22 20:30:00,-0.908779
2023-11-22 20:30:00,191.520004,191.699997,191.220001,191.300003,3537662,2023-11-22 21:30:00,-0.916956
2023-11-24 14:30:00,190.869995,190.899994,189.300003,189.460007,7873135,2023-11-24 15:30:00,-0.987760
2023-11-24 15:30:00,189.470001,189.669998,189.250000,189.610001,4853829,2023-11-24 16:30:00,-0.981988
2023-11-24 16:30:00,189.600006,189.788895,189.350006,189.539993,3827135,2023-11-24 17:30:00,-0.984682
2023-11-27 14:30:00,190.250702,190.299896,188.899994,189.059998,8344466,2023-11-27 15:30:00,-1.003153
2023-11-27 15:30:00,189.070007,189.500000,189.009995,189.494995,3959357,2023-11-27 16:30:00,-0.986414
2023-11-27 16:30:00,189.490005,190.509995,189.440002,190.369995,4866435,2023-11-27 17:30:00,-0.952743

In [4]:
env = gym.make(
    "MultiDatasetTradingEnv",
    dataset_dir="data/*.pkl",
    preprocess=preprocess,
    # Valeur initiale du portefeuille
    portfolio_initial_value=1_000,
    # Frais de transactions
    trading_fees=0.1/100,
    # Intérêts sur les prêts
    borrow_interest_rate=0.02/100/24,
)

In [11]:
pip install stable-baselines3[extra]

Exception ignored in: <_io.FileIO name=3 mode='wb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    res = process_handler(cmd, _system_body)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ResourceWarning: unclosed file <_io.BufferedWriter name=3>
Exception ignored in: <_io.FileIO name=4 mode='rb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    res = process_handler(cmd, _system_body)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ResourceWarning: unclosed file <_io.BufferedReader name=4>
Exception ignored in: <_io.FileIO name=5 mode='rb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    res = process_handler(cmd, _system_body)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ResourceWarning: unclosed file <_io.BufferedReader name=5>

Collecting stable-baselines3[extra]
  Downloading stable_baselines3-2.7.1-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: gymnasium<1.3.0,>=0.29.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from stable-baselines3[extra]) (1.2.2)
Requirement already satisfied: numpy<3.0,>=1.20 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from stable-baselines3[extra]) (2.2.6)
Collecting torch<3.0,>=2.3 (from stable-baselines3[extra])
  Downloading torch-2.9.1-cp312-cp312-win_amd64.whl.metadata (30 kB)
Requirement already satisfied: cloudpickle in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from stable-baselines3[extra]) (3.1.2)
Requirement already satisfied: pandas in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from stable-baselines3[extra]) (2.3.3)
Collecting matplotlib (from stable-baselines3[extra])
  Downloading matplotlib-3.10.8-cp312-cp312-win_amd64.whl.metadata (52 kB)
Collecting opencv-python (from stable-baselines3[extra])
  Downloading opencv_python-4.12.0.88-cp37-abi3-win_amd64.whl.metadata (19 kB)
Collecting pygame (from stable-baselines3[extra])
  Downloading pygame-2.6.1-cp312-cp312-win_amd64.whl.metadata (13 kB)
Collecting tensorboard>=2.9.1 (from stable-baselines3[extra])
  Downloading tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: psutil in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from stable-baselines3[extra]) (7.1.3)
Requirement already satisfied: tqdm in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from stable-baselines3[extra]) (4.67.1)
Collecting rich (from stable-baselines3[extra])
  Downloading rich-14.2.0-py3-none-any.whl.metadata (18 kB)
Collecting ale-py>=0.9.0 (from stable-baselines3[extra])
  Downloading ale_py-0.11.2-cp312-cp312-win_amd64.whl.metadata (9.2 kB)
Collecting pillow (from stable-baselines3[extra])
  Downloading pillow-12.0.0-cp312-cp312-win_amd64.whl.metadata (9.0 kB)
Requirement already satisfied: typing-extensions>=4.3.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gymnasium<1.3.0,>=0.29.1->stable-baselines3[extra]) (4.15.0)
Requirement already satisfied: farama-notifications>=0.0.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gymnasium<1.3.0,>=0.29.1->stable-baselines3[extra]) (0.0.4)
Collecting filelock (from torch<3.0,>=2.3->stable-baselines3[extra])
  Downloading filelock-3.20.1-py3-none-any.whl.metadata (2.1 kB)
Collecting sympy>=1.13.3 (from torch<3.0,>=2.3->stable-baselines3[extra])
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch<3.0,>=2.3->stable-baselines3[extra])
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: jinja2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from torch<3.0,>=2.3->stable-baselines3[extra]) (3.1.6)
Collecting fsspec>=0.8.5 (from torch<3.0,>=2.3->stable-baselines3[extra])
  Downloading fsspec-2025.12.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: setuptools in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from torch<3.0,>=2.3->stable-baselines3[extra]) (80.9.0)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch<3.0,>=2.3->stable-baselines3[extra])
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting absl-py>=0.4 (from tensorboard>=2.9.1->stable-baselines3[extra])
  Downloading absl_py-2.3.1-py3-none-any.whl.metadata (3.3 kB)
Collecting grpcio>=1.48.2 (from tensorboard>=2.9.1->stable-baselines3[extra])
  Downloading grpcio-1.76.0-cp312-cp312-win_amd64.whl.metadata (3.8 kB)
Collecting markdown>=2.6.8 (from tensorboard>=2.9.1->stable-baselines3[extra])
  Downloading markdown-3.10-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: packaging in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (25.0)
Collecting protobuf!=4.24.0,>=3.19.6 (from tensorboard>=2.9.1->stable-baselines3[extra])
  Downloading protobuf-6.33.2-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard>=2.9.1->stable-baselines3[extra])
  Downloading tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (3.1.4)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from werkzeug>=1.0.1->tensorboard>=2.9.1->stable-baselines3[extra]) (3.0.3)
Collecting contourpy>=1.0.1 (from matplotlib->stable-baselines3[extra])
  Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib->stable-baselines3[extra])
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib->stable-baselines3[extra])
  Downloading fonttools-4.61.1-cp312-cp312-win_amd64.whl.metadata (116 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib->stable-baselines3[extra])
  Downloading kiwisolver-1.4.9-cp312-cp312-win_amd64.whl.metadata (6.4 kB)
Collecting pyparsing>=3 (from matplotlib->stable-baselines3[extra])
  Downloading pyparsing-3.2.5-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from matplotlib->stable-baselines3[extra]) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->stable-baselines3[extra]) (1.17.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas->stable-baselines3[extra]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas->stable-baselines3[extra]) (2025.3)
Collecting markdown-it-py>=2.2.0 (from rich->stable-baselines3[extra])
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from rich->stable-baselines3[extra]) (2.19.2)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->stable-baselines3[extra])
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: colorama in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from tqdm->stable-baselines3[extra]) (0.4.6)
Downloading stable_baselines3-2.7.1-py3-none-any.whl (188 kB)
Downloading torch-2.9.1-cp312-cp312-win_amd64.whl (110.9 MB)
   ---------------------------------------- 0.0/110.9 MB ? eta -:--:--
    --------------------------------------- 1.6/110.9 MB 7.6 MB/s eta 0:00:15
   - -------------------------------------- 3.1/110.9 MB 7.7 MB/s eta 0:00:15
   - -------------------------------------- 4.7/110.9 MB 7.7 MB/s eta 0:00:14
   -- ------------------------------------- 6.6/110.9 MB 7.7 MB/s eta 0:00:14
   --- ------------------------------------ 8.4/110.9 MB 8.0 MB/s eta 0:00:13
   --- ------------------------------------ 10.5/110.9 MB 8.3 MB/s eta 0:00:13
   ---- ----------------------------------- 12.3/110.9 MB 8.3 MB/s eta 0:00:12
   ----- ---------------------------------- 14.4/110.9 MB 8.5 MB/s eta 0:00:12
   ----- ---------------------------------- 16.5/110.9 MB 8.7 MB/s eta 0:00:11
   ------ --------------------------------- 18.9/110.9 MB 9.0 MB/s eta 0:00:11
   ------- -------------------------------- 21.2/110.9 MB 9.1 MB/s eta 0:00:10
   -------- ------------------------------- 23.6/110.9 MB 9.3 MB/s eta 0:00:10
   --------- ------------------------------ 26.2/110.9 MB 9.5 MB/s eta 0:00:09
   ---------- ----------------------------- 28.8/110.9 MB 9.7 MB/s eta 0:00:09
   ----------- ---------------------------- 31.7/110.9 MB 10.0 MB/s eta 0:00:08
   ------------ --------------------------- 34.6/110.9 MB 10.3 MB/s eta 0:00:08
   ------------- -------------------------- 36.4/110.9 MB 10.1 MB/s eta 0:00:08
   ------------- -------------------------- 38.0/110.9 MB 10.0 MB/s eta 0:00:08
   ------------- -------------------------- 38.8/110.9 MB 9.7 MB/s eta 0:00:08
   -------------- ------------------------- 39.6/110.9 MB 9.5 MB/s eta 0:00:08
   -------------- ------------------------- 40.6/110.9 MB 9.1 MB/s eta 0:00:08
   --------------- ------------------------ 41.7/110.9 MB 9.0 MB/s eta 0:00:08
   --------------- ------------------------ 43.0/110.9 MB 8.8 MB/s eta 0:00:08
   --------------- ------------------------ 44.3/110.9 MB 8.7 MB/s eta 0:00:08
   ---------------- ----------------------- 45.6/110.9 MB 8.6 MB/s eta 0:00:08
   ---------------- ----------------------- 46.9/110.9 MB 8.5 MB/s eta 0:00:08
   ----------------- ---------------------- 48.5/110.9 MB 8.5 MB/s eta 0:00:08
   ------------------ --------------------- 50.3/110.9 MB 8.4 MB/s eta 0:00:08
   ------------------ --------------------- 51.9/110.9 MB 8.4 MB/s eta 0:00:08
   ------------------- -------------------- 53.5/110.9 MB 8.4 MB/s eta 0:00:07
   -------------------- ------------------- 55.6/110.9 MB 8.4 MB/s eta 0:00:07
   -------------------- ------------------- 57.4/110.9 MB 8.5 MB/s eta 0:00:07
   --------------------- ------------------ 59.5/110.9 MB 8.5 MB/s eta 0:00:07
   ---------------------- ----------------- 61.6/110.9 MB 8.5 MB/s eta 0:00:06
   ----------------------- ---------------- 64.0/110.9 MB 8.6 MB/s eta 0:00:06
   ----------------------- ---------------- 66.3/110.9 MB 8.7 MB/s eta 0:00:06
   ------------------------ --------------- 68.7/110.9 MB 8.7 MB/s eta 0:00:05
   ------------------------- -------------- 71.0/110.9 MB 8.8 MB/s eta 0:00:05
   -------------------------- ------------- 73.9/110.9 MB 8.9 MB/s eta 0:00:05
   --------------------------- ------------ 76.3/110.9 MB 9.0 MB/s eta 0:00:04
   ---------------------------- ----------- 78.4/110.9 MB 9.0 MB/s eta 0:00:04
   ---------------------------- ----------- 79.7/110.9 MB 9.0 MB/s eta 0:00:04
   ----------------------------- ---------- 80.5/110.9 MB 8.9 MB/s eta 0:00:04
   ----------------------------- ---------- 81.3/110.9 MB 8.7 MB/s eta 0:00:04
   ----------------------------- ---------- 81.8/110.9 MB 8.6 MB/s eta 0:00:04
   ----------------------------- ---------- 82.3/110.9 MB 8.5 MB/s eta 0:00:04
   ----------------------------- ---------- 82.8/110.9 MB 8.4 MB/s eta 0:00:04
   ------------------------------ --------- 83.4/110.9 MB 8.3 MB/s eta 0:00:04
   ------------------------------ --------- 84.1/110.9 MB 8.1 MB/s eta 0:00:04
   ------------------------------ --------- 84.9/110.9 MB 8.0 MB/s eta 0:00:04
   ------------------------------ --------- 85.7/110.9 MB 7.9 MB/s eta 0:00:04
   ------------------------------- -------- 86.8/110.9 MB 7.9 MB/s eta 0:00:04
   ------------------------------- -------- 87.6/110.9 MB 7.8 MB/s eta 0:00:03
   -------------------------------- ------- 88.9/110.9 MB 7.8 MB/s eta 0:00:03
   -------------------------------- ------- 89.9/110.9 MB 7.7 MB/s eta 0:00:03
   -------------------------------- ------- 91.2/110.9 MB 7.7 MB/s eta 0:00:03
   --------------------------------- ------ 92.8/110.9 MB 7.7 MB/s eta 0:00:03
   ---------------------------------- ----- 94.4/110.9 MB 7.7 MB/s eta 0:00:03
   ---------------------------------- ----- 95.9/110.9 MB 7.7 MB/s eta 0:00:02
   ----------------------------------- ---- 97.8/110.9 MB 7.7 MB/s eta 0:00:02
   ----------------------------------- ---- 99.4/110.9 MB 7.7 MB/s eta 0:00:02
   ------------------------------------ --- 101.2/110.9 MB 7.7 MB/s eta 0:00:02
   ------------------------------------- -- 103.3/110.9 MB 7.7 MB/s eta 0:00:01
   ------------------------------------- -- 105.4/110.9 MB 7.8 MB/s eta 0:00:01
   -------------------------------------- - 107.7/110.9 MB 7.8 MB/s eta 0:00:01
   ---------------------------------------  109.8/110.9 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------  110.9/110.9 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------- 110.9/110.9 MB 7.7 MB/s  0:00:14
Downloading ale_py-0.11.2-cp312-cp312-win_amd64.whl (3.5 MB)
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   ------------------------ --------------- 2.1/3.5 MB 10.7 MB/s eta 0:00:01
   ---------------------------------------- 3.5/3.5 MB 10.8 MB/s  0:00:00
Downloading fsspec-2025.12.0-py3-none-any.whl (201 kB)
Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 11.6 MB/s  0:00:00
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ---------------------------------------- 0.0/6.3 MB ? eta -:--:--
   -------------- ------------------------- 2.4/6.3 MB 12.2 MB/s eta 0:00:01
   --------------------------------- ------ 5.2/6.3 MB 12.3 MB/s eta 0:00:01
   ---------------------------------------- 6.3/6.3 MB 12.1 MB/s  0:00:00
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ---------------------------------------- 0.0/536.2 kB ? eta -:--:--
   ---------------------------------------- 536.2/536.2 kB 8.8 MB/s  0:00:00
Downloading tensorboard-2.20.0-py3-none-any.whl (5.5 MB)
   ---------------------------------------- 0.0/5.5 MB ? eta -:--:--
   ------------------ --------------------- 2.6/5.5 MB 12.5 MB/s eta 0:00:01
   ------------------------------------ --- 5.0/5.5 MB 12.6 MB/s eta 0:00:01
   ---------------------------------------- 5.5/5.5 MB 12.0 MB/s  0:00:00
Downloading tensorboard_data_server-0.7.2-py3-none-any.whl (2.4 kB)
Downloading absl_py-2.3.1-py3-none-any.whl (135 kB)
Downloading grpcio-1.76.0-cp312-cp312-win_amd64.whl (4.7 MB)
   ---------------------------------------- 0.0/4.7 MB ? eta -:--:--
   -------------------------- ------------- 3.1/4.7 MB 16.8 MB/s eta 0:00:01
   ---------------------------------------- 4.7/4.7 MB 14.2 MB/s  0:00:00
Downloading markdown-3.10-py3-none-any.whl (107 kB)
Downloading protobuf-6.33.2-cp310-abi3-win_amd64.whl (436 kB)
Downloading filelock-3.20.1-py3-none-any.whl (16 kB)
Downloading matplotlib-3.10.8-cp312-cp312-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   --------------- ------------------------ 3.1/8.1 MB 14.2 MB/s eta 0:00:01
   ------------------------------ --------- 6.3/8.1 MB 14.9 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 12.9 MB/s  0:00:00
Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl (226 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.61.1-cp312-cp312-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 16.5 MB/s  0:00:00
Downloading kiwisolver-1.4.9-cp312-cp312-win_amd64.whl (73 kB)
Downloading pillow-12.0.0-cp312-cp312-win_amd64.whl (7.0 MB)
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   -------------------- ------------------- 3.7/7.0 MB 16.8 MB/s eta 0:00:01
   -------------------------------------- - 6.8/7.0 MB 16.8 MB/s eta 0:00:01
   ---------------------------------------- 7.0/7.0 MB 15.4 MB/s  0:00:00
Downloading pyparsing-3.2.5-py3-none-any.whl (113 kB)
Downloading opencv_python-4.12.0.88-cp37-abi3-win_amd64.whl (39.0 MB)
   ---------------------------------------- 0.0/39.0 MB ? eta -:--:--
   --- ------------------------------------ 3.1/39.0 MB 15.4 MB/s eta 0:00:03
   ------ --------------------------------- 6.6/39.0 MB 15.5 MB/s eta 0:00:03
   ----------- ---------------------------- 10.7/39.0 MB 16.8 MB/s eta 0:00:02
   -------------- ------------------------- 14.4/39.0 MB 16.8 MB/s eta 0:00:02
   ----------------- ---------------------- 16.8/39.0 MB 15.8 MB/s eta 0:00:02
   -------------------- ------------------- 19.7/39.0 MB 15.5 MB/s eta 0:00:02
   ----------------------- ---------------- 22.5/39.0 MB 15.2 MB/s eta 0:00:02
   -------------------------- ------------- 25.7/39.0 MB 15.2 MB/s eta 0:00:01
   ----------------------------- ---------- 29.1/39.0 MB 15.2 MB/s eta 0:00:01
   --------------------------------- ------ 32.5/39.0 MB 15.4 MB/s eta 0:00:01
   ------------------------------------- -- 36.4/39.0 MB 15.5 MB/s eta 0:00:01
   ---------------------------------------  38.8/39.0 MB 15.7 MB/s eta 0:00:01
   ---------------------------------------- 39.0/39.0 MB 15.1 MB/s  0:00:02
Downloading pygame-2.6.1-cp312-cp312-win_amd64.whl (10.6 MB)
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ------------- -------------------------- 3.7/10.6 MB 16.8 MB/s eta 0:00:01
   ---------------------------- ----------- 7.6/10.6 MB 18.1 MB/s eta 0:00:01
   ---------------------------------------- 10.6/10.6 MB 17.0 MB/s  0:00:00
Downloading rich-14.2.0-py3-none-any.whl (243 kB)
Downloading markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: mpmath, tensorboard-data-server, sympy, pyparsing, pygame, protobuf, pillow, opencv-python, networkx, mdurl, markdown, kiwisolver, grpcio, fsspec, fonttools, filelock, cycler, contourpy, ale-py, absl-py, torch, tensorboard, matplotlib, markdown-it-py, stable-baselines3, rich

   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   --- ------------------------------------  2/26 [sympy]
   --- ------------------------------------  2/26 [sympy]
   --- ------------------------------------  2/26 [sympy]
   --- ------------------------------------  2/26 [sympy]
   --- ------------------------------------  2/26 [sympy]
   --- ------------------------------------  2/26 [sympy]
   --- ------------------------------------  2/26 [sympy]
   --- ------------------------------------  2/26 [sympy]

In [ ]:
config1 = {
    "policy_type": "MlpPolicy",
    "initial_portfolio": 1_000,
    "total_timesteps" : 250_000,
    "env_id": "MultiDatasetTradingEnv"
}

run = wandb.init(
    project="rl-trading-project_billet_crespin_truong", 
    config=config1,
    sync_tensorboard=True,
    monitor_gym=False,
    save_code=False,
)

model = PPO("MlpPolicy",env,tensorboard_log=f"runs/{run.id}")
model.learn(
    total_timesteps=config1["total_timesteps"],
    callback=WandbCallback(
        gradient_save_freq=100,
        model_save_path=f"models/{run.id}",
        verbose=2,
    )
)
model.save("PPO_1st")

wandb: Currently logged in as: mathis_crespin (rl_trading_project_billet_crespin_truong) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

Market Return : 163.91%   |   Portfolio Return : -100.00%   |
Market Return : 103.26%   |   Portfolio Return : -99.95%   |
Market Return : 677.81%   |   Portfolio Return : -100.00%   |
Market Return : 27.70%   |   Portfolio Return : -53.42%   |
Market Return : 44.45%   |   Portfolio Return : -49.60%   |
Market Return : 10.54%   |   Portfolio Return : -47.37%   |

In [1]:
nb_episodes = 30

for episode in range(1, nb_episodes + 1):
    obs, _ = env.reset()
    done = False
    
    dataset_name = env.env.name 
    
    while not done:
        action, _states = model.predict(obs)
        obs, reward, terminated, truncated, _ = env.step(action.tolist())
        done = terminated or truncated

    if done:
        history = env.env.historical_info
        df_history = pd.DataFrame(history)
        
        initial_val = df_history['portfolio_valuation'].iloc[0]
        final_val = df_history['portfolio_valuation'].iloc[-1]
        c_r_pourcent = ((final_val - initial_val) / initial_val) * 100
        
        fig = make_subplots(specs=[[{"secondary_y": True}]])

        fig.add_trace(
            go.Scatter(y=df_history['data_close'], name="Prix (Close)", line=dict(color='gray', width=1)),
            secondary_y=False
        )

        fig.add_trace(
            go.Scatter(y=df_history['portfolio_valuation'], name="Portefeuille", line=dict(color='blue', width=2)),
            secondary_y=True
        )


        fig.update_layout(
            title=f"Episode {episode} : {dataset_name} (Compte de résultat: {c_r_pourcent:.2f}%)",
            xaxis_title="Steps"
        )

        wandb.log({
            "eval/episode": episode,
            "eval/dataset": dataset_name,
            "eval/cr_pourcent": c_r_pourcent,
            "eval/final_value": final_val,
            "eval/chart": wandb.Plotly(fig) 
        })
        
        print(f"Episode {episode} loggé : {dataset_name} -> PnL: {c_r_pourcent:.2f}%")

wandb.finish()

NameError: name 'env' is not defined

In [14]:
nb_episodes = 3

def metric_portfolio_valuation(history):
    return round(history['portfolio_valuation', -1], 2)

env.add_metric('Portfolio Valuation', metric_portfolio_valuation)


for episode in range(1, nb_episodes + 1):
    obs, _ = env.reset()
    print(f'Episode n˚{episode} -- Jeu de donnée {env.name}')
    done = False

    while not done:
        action, _states = model.predict(obs)
        obs, reward, terminated, truncated, _ = env.step(action)
        done = terminated or truncated
    env.save_for_render(dir="logs")        
    if terminated:
        print('Argent perdu')
        
    elif truncated:
        print('Épisode terminé')

Episode n˚1 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 95.06%   |   Portfolio Return : -101.35%   |   Portfolio Valuation : -13.46   |
Argent perdu
Episode n˚2 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.94%   |   Portfolio Return : -45.77%   |   Portfolio Valuation : 542.28   |
Épisode terminé
Episode n˚3 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.27%   |   Portfolio Return : -6.77%   |   Portfolio Valuation : 932.32   |
Épisode terminé

In [67]:
env.historical_info[-1]

{'idx': 2763,
 'step': 2763,
 'date': np.datetime64('2025-06-25T13:30:00.000000000'),
 'position_index': array(1),
 'position': 1,
 'real_position': np.float64(1.0000000000000002),
 'data_date_close': Timestamp('2025-06-25 14:30:00'),
 'data_close': 6100.830078125,
 'data_high': 6108.509765625,
 'data_volume': 0,
 'data_open': 6104.22998046875,
 'data_low': 6096.8798828125,
 'portfolio_valuation': np.float64(1346.3183462273655),
 'portfolio_distribution_asset': np.float64(0.22067789612018449),
 'portfolio_distribution_fiat': 0,
 'portfolio_distribution_borrowed_asset': 0,
 'portfolio_distribution_borrowed_fiat': np.float64(1.1368683772161603e-13),
 'portfolio_distribution_interest_asset': 0.0,
 'portfolio_distribution_interest_fiat': np.float64(9.473903143468003e-19),
 'reward': np.float64(0.0012383509773613998)}

Actuellement, les résultats sont trop aléatoirs, parfois l'agent apprend rapidement mais il n'est pas enclin à faire mieux que le marché. Il se contente de toujours garder son argent.
Nous allons améliorer notre programme de 2 manières:
    - Changer la fonction de reward, pour qu'elle récompense plus l'exploration
    - ajouter des features pour que l'agent comprenne mieux le marché

In [112]:
env.env.historical_info[-1]

{'idx': 42131,
 'step': 42131,
 'date': np.datetime64('2025-11-20T13:00:00.000000000'),
 'position_index': 13,
 'position': 1.4,
 'real_position': np.float64(1.398325122244509),
 'data_high': 0.13837,
 'data_low': 0.13651,
 'data_open': 0.13783,
 'data_date_close': Timestamp('2025-11-20 14:00:00'),
 'data_volume': 445127.0,
 'data_close': 0.13673,
 'portfolio_valuation': np.float64(1654.837230888517),
 'portfolio_distribution_asset': np.float64(16923.86801124077),
 'portfolio_distribution_fiat': 0,
 'portfolio_distribution_borrowed_asset': 0,
 'portfolio_distribution_borrowed_fiat': np.float64(659.1577493071892),
 'portfolio_distribution_interest_asset': 0.0,
 'portfolio_distribution_interest_fiat': np.float64(0.0054929812442265765),
 'reward': np.float64(-0.00355254135303337)}

In [104]:
def preprocess_v2(df):
    df = df.sort_index()
    df = df.dropna()
    df = df.drop_duplicates()

    # Valeur des différentes features par rapport à la moyenne
    df['feature_close'] = (df['close'] - df['close'].mean()) / df['close'].std()
    df['feature_high'] = (df['high'] - df['high'].mean()) / df['high'].std()
    df['feature_low'] = (df['low'] - df['low'].mean()) / df['low'].std()

    #Valeur des ratios entre 2 des 4 niveaux (haut/bas ou fermeture/ouverture)
    df['feature_ratio_high_low'] = (df['high'] / df['low'])
    df['feature_ratio_close_open'] = (df['close'] / df['open'])
    df['feature_ratio_high_close'] = (df['high'] / df['close'])

    #Valeur des features par rapport à leur max
    df['feature_max_ratio_close'] = (df['close'] - df['close'].max()) / df['close'].max()
    df['feature_max_ratio_open'] = (df['open'] - df['open'].max()) / df['open'].max()
    df['feature_max_ratio_low'] = (df['low'] - df['low'].max()) / df['low'].max()
    df['feature_max_ratio_high'] = (df['high'] - df['high'].max()) / df['high'].max()

    #Valeur des ratios par rapport à leur max entre 2 des 4 niveaux (haut/bas ou fermeture/ouverture)
    df['feature_ratio_max_high_low'] = (df['feature_ratio_high_low'] - df['feature_ratio_high_low'].max()) / df['feature_ratio_high_low'].max()
    df['feature_ratio_max__close_open'] = (df['feature_ratio_close_open'] - df['feature_ratio_close_open'].max()) / df['feature_ratio_close_open'].max()
    df['feature_ratio_max_high_close'] = (df['feature_ratio_high_close'] - df['feature_ratio_high_close'].max()) / df['feature_ratio_high_close'].max()

    return df

df = preprocess_v2(pd.read_pickle('./data/yfinance-AAPL-1h.pkl'))
df.head(5)

,open,high,low,close,volume,date_close,feature_close,feature_high,feature_low,feature_ratio_high_low,feature_ratio_close_open,feature_ratio_high_close,feature_max_ratio_close,feature_max_ratio_open,feature_max_ratio_low,feature_max_ratio_high,feature_ratio_max_high_low,feature_ratio_max__close_open,feature_ratio_max_high_close
date_open,,,,,,,,,,,,,,,,,,,
2023-11-21 14:30:00,191.410004,191.520004,190.270004,190.347504,8992766,2023-11-21 15:30:00,-0.953609,-0.934171,-0.930512,1.006570,0.994449,1.006160,-0.309597,-0.308964,-0.308235,-0.309390,-0.094637,-0.052735,-0.054685
2023-11-21 15:30:00,190.350006,190.470001,189.740005,189.942001,5681421,2023-11-21 16:30:00,-0.969213,-0.974486,-0.950975,1.003847,0.997857,1.002780,-0.311068,-0.312791,-0.310162,-0.313176,-0.097086,-0.049490,-0.057860
2023-11-21 16:30:00,189.940002,190.320007,189.830002,190.274994,3359800,2023-11-21 17:30:00,-0.956399,-0.980244,-0.947501,1.002581,1.001764,1.000237,-0.309860,-0.314271,-0.309835,-0.313717,-0.098224,-0.045768,-0.060250
2023-11-21 17:30:00,190.276993,190.600006,190.039993,190.119995,3112369,2023-11-21 18:30:00,-0.962363,-0.969494,-0.939393,1.002947,0.999175,1.002525,-0.310422,-0.313055,-0.309071,-0.312707,-0.097895,-0.048234,-0.058100
2023-11-21 18:30:00,190.119995,190.615005,190.085007,190.380005,2874142,2023-11-21 19:30:00,-0.952358,-0.968918,-0.937655,1.002788,1.001368,1.001234,-0.309479,-0.313621,-0.308907,-0.312653,-0.098038,-0.046145,-0.059312

In [6]:
from gym_trading_env.wrapper import DiscreteActionsWrapper

def metric_portfolio_valuation(history):
    return round(history['portfolio_valuation', -1], 2)

def reward_function(history):
    return history['step']*(history['portfolio_valuation', -1] - history['portfolio_valuation', -2])

def reward_function_rapport_market(history):
    return 10*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1]))

def reward_function_rapport_market_v2(history):
    weight = 0 
    if (history['position',1] == history['position',-2]):
        weight = 0.1
    return 10*(history['data_open', -2] / history['data_close', -1])*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1])) - weight 


env = gym.make(
    "MultiDatasetTradingEnv",
    dataset_dir="data/*.pkl",
    preprocess=preprocess_v2,
    reward_function=reward_function_rapport_market,
    # Valeur initiale du portefeuille
    portfolio_initial_value=1_000,
    # Frais de transactions
    trading_fees=0.1/100,
    # Intérêts sur les prêts
    borrow_interest_rate=0.02/100/24,
)

env.add_metric('Portfolio Valuation', metric_portfolio_valuation)
env = DiscreteActionsWrapper(env, positions=[-1,-0.8,-0.6,-0.4,-0.2,0,0.2,0.4,0.5,0.6,0.8,1,1.2,1.4,1.6,1.8,2])
obs, _ = env.reset()

ModuleNotFoundError: No module named 'gym_trading_env.wrapper'

In [125]:
from stable_baselines3 import PPO

model = PPO("MlpPolicy",env)

model = model.learn(total_timesteps=300_000)

Market Return : 39.94%   |   Portfolio Return : -97.79%   |   Portfolio Valuation : 22.14   |
Market Return :  5.27%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.01   |
Market Return : 163.91%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.0   |
Market Return : 904.05%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.0   |
Market Return : 10.54%   |   Portfolio Return : -59.97%   |   Portfolio Valuation : 400.28   |
Market Return : 677.81%   |   Portfolio Return : -99.96%   |   Portfolio Valuation : 0.4   |
Market Return : 27.70%   |   Portfolio Return : -36.32%   |   Portfolio Valuation : 636.84   |
Market Return : 10.54%   |   Portfolio Return : -16.43%   |   Portfolio Valuation : 835.73   |
Market Return : 904.05%   |   Portfolio Return : 745.66%   |   Portfolio Valuation : 8456.63   |
Market Return :  5.27%   |   Portfolio Return : -89.92%   |   Portfolio Valuation : 100.82   |
Market Return : 39.94%   |   Portfolio Return : -28.13%   |   Portfolio Valuation : 718.7   |
Market Return : 44.45%   |   Portfolio Return : -48.28%   |   Portfolio Valuation : 517.16   |
Market Return : 677.81%   |   Portfolio Return : -99.76%   |   Portfolio Valuation : 2.39   |

In [127]:
nb_episodes = 10

for episode in range(1, nb_episodes + 1):
    obs, _ = env.reset()
    print(f'Episode n˚{episode} -- Jeu de donnée {env.env.name}')
    done = False

    while not done:
        action, _states = model.predict(obs)
        obs, reward, terminated, truncated, _ = env.step(action.tolist())
        done = terminated or truncated
    env.env.save_for_render(dir="logs")        
    if terminated:
        print('Argent perdu')
        
    elif truncated:
        print('Épisode terminé')

Episode n˚1 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 27.70%   |   Portfolio Return : -38.70%   |   Portfolio Valuation : 612.98   |
Épisode terminé
Episode n˚2 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 163.91%   |   Portfolio Return : -57.81%   |   Portfolio Valuation : 421.9   |
Épisode terminé
Episode n˚3 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 904.05%   |   Portfolio Return : -96.30%   |   Portfolio Valuation : 36.96   |
Épisode terminé
Episode n˚4 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 44.45%   |   Portfolio Return : -8.39%   |   Portfolio Valuation : 916.08   |
Épisode terminé
Episode n˚5 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.27%   |   Portfolio Return : -88.12%   |   Portfolio Valuation : 118.85   |
Épisode terminé
Episode n˚6 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 27.70%   |   Portfolio Return : -28.74%   |   Portfolio Valuation : 712.57   |
Épisode terminé
Episode n˚7 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.26%   |   Portfolio Return : -76.53%   |   Portfolio Valuation : 234.69   |
Épisode terminé
Episode n˚8 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.94%   |   Portfolio Return : 10.65%   |   Portfolio Valuation : 1106.5   |
Épisode terminé
Episode n˚9 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 677.81%   |   Portfolio Return : -98.26%   |   Portfolio Valuation : 17.45   |
Épisode terminé
Episode n˚10 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return : 10.54%   |   Portfolio Return : -35.47%   |   Portfolio Valuation : 645.28   |
Épisode terminé

In [81]:
env.env.historical_info[-1]

{'idx': 4509,
 'step': 4509,
 'date': np.datetime64('2025-11-21T13:00:00.000000000'),
 'position_index': 4,
 'position': 1,
 'real_position': np.float64(1.0),
 'data_high': 5531.83984375,
 'data_open': 5525.81982421875,
 'data_low': 5518.8798828125,
 'data_volume': 0,
 'data_delta_high_low': 1.002348295526029,
 'data_delta_open_close': 1.0009030758391957,
 'data_date_close': Timestamp('2025-11-21 14:00:00'),
 'data_close': 5530.81005859375,
 'portfolio_valuation': np.float64(1121.6929142246133),
 'portfolio_distribution_asset': np.float64(0.20280807012740049),
 'portfolio_distribution_fiat': 0,
 'portfolio_distribution_borrowed_asset': 0,
 'portfolio_distribution_borrowed_fiat': 0,
 'portfolio_distribution_interest_asset': 0.0,
 'portfolio_distribution_interest_fiat': 0.0,
 'reward': np.float64(-6.340988893560606e-05)}

In [1]:
!pip install pandas_ta

Collecting pandas_ta
  Using cached pandas_ta-0.4.71b0-py3-none-any.whl.metadata (2.3 kB)
Collecting numba==0.61.2 (from pandas_ta)
  Using cached numba-0.61.2-cp312-cp312-win_amd64.whl.metadata (2.9 kB)
Requirement already satisfied: numpy>=2.2.6 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas_ta) (2.3.5)
Requirement already satisfied: pandas>=2.3.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas_ta) (2.3.3)
Collecting tqdm>=4.67.1 (from pandas_ta)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting llvmlite<0.45,>=0.44.0dev0 (from numba==0.61.2->pandas_ta)
  Using cached llvmlite-0.44.0-cp312-cp312-win_amd64.whl.metadata (5.0 kB)
Collecting numpy>=2.2.6 (from pandas_ta)
  Using cached numpy-2.2.6-cp312-cp312-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas>=2.3.2->pandas_ta) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas>=2.3.2->pandas_ta) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas>=2.3.2->pandas_ta) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.3.2->pandas_ta) (1.17.0)
Requirement already satisfied: colorama in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from tqdm>=4.67.1->pandas_ta) (0.4.6)
Using cached pandas_ta-0.4.71b0-py3-none-any.whl (240 kB)
Using cached numba-0.61.2-cp312-cp312-win_amd64.whl (2.8 MB)
Using cached llvmlite-0.44.0-cp312-cp312-win_amd64.whl (30.3 MB)
Using cached numpy-2.2.6-cp312-cp312-win_amd64.whl (12.6 MB)
Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, numpy, llvmlite, numba, pandas_ta

   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
  Attempting uninstall: numpy
   ---------------------------------------- 0/5 [tqdm]
    Found existing installation: numpy 2.3.5
   ---------------------------------------- 0/5 [tqdm]
   -------- ------------------------------- 1/5 [numpy]
    Uninstalling numpy-2.3.5:
   -------- ------------------------------- 1/5 [numpy]
      Successfully uninstalled numpy-2.3.5
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   ---------------- ----------------------- 2/5 [llvmlite]
   ---------------- ----------------------- 2/5 [llvmlite]
   ---------------- ----------------------- 2/5 [llvmlite]
   ---------------- ----------------------- 2/5 [llvmlite]
   ---------------- ----------------------- 2/5 [llvmlite]
   ---------------- ----------------------- 2/5 [llvmlite]
   ---------------- ----------------------- 2/5 [llvmlite]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   ---------------------------------------- 5/5 [pandas_ta]

Successfully installed llvmlite-0.44.0 numba-0.61.2 numpy-2.2.6 pandas_ta-0.4.71b0 tqdm-4.67.1

In [2]:
pip install --upgrade pip

Requirement already satisfied: pip in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (25.3)
Note: you may need to restart the kernel to use updated packages.

In [1]:
pip install gym-trading-env-continuous

Collecting gym-trading-env-continuous
  Using cached gym_trading_env_continuous-1.0.3-py3-none-any.whl.metadata (4.9 kB)
Collecting pandas>=1.5.3 (from gym-trading-env-continuous)
  Using cached pandas-2.3.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.21.1 (from gym-trading-env-continuous)
  Using cached numpy-2.3.5-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting gymnasium>=0.28.1 (from gym-trading-env-continuous)
  Using cached gymnasium-1.2.2-py3-none-any.whl.metadata (10 kB)
Collecting flask>=2.2.3 (from gym-trading-env-continuous)
  Downloading flask-3.1.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pyecharts>=2.0.2 (from gym-trading-env-continuous)
  Using cached pyecharts-2.0.9-py3-none-any.whl.metadata (1.6 kB)
Collecting ccxt==3.0.59 (from gym-trading-env-continuous)
  Using cached ccxt-3.0.59-py2.py3-none-any.whl.metadata (111 kB)
Requirement already satisfied: nest_asyncio in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gym-trading-env-continuous) (1.6.0)
Collecting setuptools>=60.9.0 (from ccxt==3.0.59->gym-trading-env-continuous)
  Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
Collecting certifi>=2018.1.18 (from ccxt==3.0.59->gym-trading-env-continuous)
  Using cached certifi-2025.11.12-py3-none-any.whl.metadata (2.5 kB)
Collecting requests>=2.18.4 (from ccxt==3.0.59->gym-trading-env-continuous)
  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting cryptography>=2.6.1 (from ccxt==3.0.59->gym-trading-env-continuous)
  Using cached cryptography-46.0.3-cp311-abi3-win_amd64.whl.metadata (5.7 kB)
Collecting aiohttp>=3.8 (from ccxt==3.0.59->gym-trading-env-continuous)
  Using cached aiohttp-3.13.2-cp312-cp312-win_amd64.whl.metadata (8.4 kB)
Collecting aiodns>=1.1.1 (from ccxt==3.0.59->gym-trading-env-continuous)
  Using cached aiodns-3.6.1-py3-none-any.whl.metadata (5.8 kB)
Collecting yarl>=1.7.2 (from ccxt==3.0.59->gym-trading-env-continuous)
  Using cached yarl-1.22.0-cp312-cp312-win_amd64.whl.metadata (77 kB)
Collecting pycares<5,>=4.9.0 (from aiodns>=1.1.1->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached pycares-4.11.0-cp312-cp312-win_amd64.whl.metadata (4.8 kB)
Collecting cffi>=1.5.0 (from pycares<5,>=4.9.0->aiodns>=1.1.1->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached cffi-2.0.0-cp312-cp312-win_amd64.whl.metadata (2.6 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp>=3.8->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp>=3.8->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp>=3.8->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Collecting frozenlist>=1.1.1 (from aiohttp>=3.8->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached frozenlist-1.8.0-cp312-cp312-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp>=3.8->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached multidict-6.7.0-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp>=3.8->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached propcache-0.4.1-cp312-cp312-win_amd64.whl.metadata (14 kB)
Collecting idna>=2.0 (from yarl>=1.7.2->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting typing-extensions>=4.2 (from aiosignal>=1.4.0->aiohttp>=3.8->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pycparser (from cffi>=1.5.0->pycares<5,>=4.9.0->aiodns>=1.1.1->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached pycparser-2.23-py3-none-any.whl.metadata (993 bytes)
Collecting blinker>=1.9.0 (from flask>=2.2.3->gym-trading-env-continuous)
  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting click>=8.1.3 (from flask>=2.2.3->gym-trading-env-continuous)
  Using cached click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Collecting itsdangerous>=2.2.0 (from flask>=2.2.3->gym-trading-env-continuous)
  Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting jinja2>=3.1.2 (from flask>=2.2.3->gym-trading-env-continuous)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting markupsafe>=2.1.1 (from flask>=2.2.3->gym-trading-env-continuous)
  Using cached markupsafe-3.0.3-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Collecting werkzeug>=3.1.0 (from flask>=2.2.3->gym-trading-env-continuous)
  Using cached werkzeug-3.1.4-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: colorama in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from click>=8.1.3->flask>=2.2.3->gym-trading-env-continuous) (0.4.6)
Collecting cloudpickle>=1.2.0 (from gymnasium>=0.28.1->gym-trading-env-continuous)
  Using cached cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting farama-notifications>=0.0.1 (from gymnasium>=0.28.1->gym-trading-env-continuous)
  Using cached Farama_Notifications-0.0.4-py3-none-any.whl.metadata (558 bytes)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas>=1.5.3->gym-trading-env-continuous) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas>=1.5.3->gym-trading-env-continuous)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas>=1.5.3->gym-trading-env-continuous)
  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting prettytable (from pyecharts>=2.0.2->gym-trading-env-continuous)
  Using cached prettytable-3.17.0-py3-none-any.whl.metadata (34 kB)
Collecting simplejson (from pyecharts>=2.0.2->gym-trading-env-continuous)
  Using cached simplejson-3.20.2-cp312-cp312-win_amd64.whl.metadata (3.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.3->gym-trading-env-continuous) (1.17.0)
Collecting charset_normalizer<4,>=2 (from requests>=2.18.4->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached charset_normalizer-3.4.4-cp312-cp312-win_amd64.whl.metadata (38 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.18.4->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached urllib3-2.6.2-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: wcwidth in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from prettytable->pyecharts>=2.0.2->gym-trading-env-continuous) (0.2.14)
Using cached gym_trading_env_continuous-1.0.3-py3-none-any.whl (18 kB)
Using cached ccxt-3.0.59-py2.py3-none-any.whl (3.6 MB)
Using cached aiodns-3.6.1-py3-none-any.whl (8.0 kB)
Using cached pycares-4.11.0-cp312-cp312-win_amd64.whl (144 kB)
Using cached aiohttp-3.13.2-cp312-cp312-win_amd64.whl (453 kB)
Using cached multidict-6.7.0-cp312-cp312-win_amd64.whl (46 kB)
Using cached yarl-1.22.0-cp312-cp312-win_amd64.whl (87 kB)
Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Using cached attrs-25.4.0-py3-none-any.whl (67 kB)
Using cached certifi-2025.11.12-py3-none-any.whl (159 kB)
Using cached cffi-2.0.0-cp312-cp312-win_amd64.whl (183 kB)
Using cached cryptography-46.0.3-cp311-abi3-win_amd64.whl (3.5 MB)
Downloading flask-3.1.2-py3-none-any.whl (103 kB)
Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Using cached click-8.3.1-py3-none-any.whl (108 kB)
Using cached frozenlist-1.8.0-cp312-cp312-win_amd64.whl (44 kB)
Using cached gymnasium-1.2.2-py3-none-any.whl (952 kB)
Using cached cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Using cached Farama_Notifications-0.0.4-py3-none-any.whl (2.5 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Using cached itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached markupsafe-3.0.3-cp312-cp312-win_amd64.whl (15 kB)
Using cached numpy-2.3.5-cp312-cp312-win_amd64.whl (12.8 MB)
Using cached pandas-2.3.3-cp312-cp312-win_amd64.whl (11.0 MB)
Using cached propcache-0.4.1-cp312-cp312-win_amd64.whl (41 kB)
Using cached pyecharts-2.0.9-py3-none-any.whl (153 kB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached requests-2.32.5-py3-none-any.whl (64 kB)
Using cached charset_normalizer-3.4.4-cp312-cp312-win_amd64.whl (107 kB)
Using cached urllib3-2.6.2-py3-none-any.whl (131 kB)
Using cached setuptools-80.9.0-py3-none-any.whl (1.2 MB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Using cached werkzeug-3.1.4-py3-none-any.whl (224 kB)
Using cached prettytable-3.17.0-py3-none-any.whl (34 kB)
Using cached pycparser-2.23-py3-none-any.whl (118 kB)
Using cached simplejson-3.20.2-cp312-cp312-win_amd64.whl (75 kB)
Installing collected packages: pytz, farama-notifications, urllib3, tzdata, typing-extensions, simplejson, setuptools, pycparser, propcache, prettytable, numpy, multidict, markupsafe, itsdangerous, idna, frozenlist, cloudpickle, click, charset_normalizer, certifi, blinker, attrs, aiohappyeyeballs, yarl, werkzeug, requests, pandas, jinja2, gymnasium, cffi, aiosignal, pyecharts, pycares, flask, cryptography, aiohttp, aiodns, ccxt, gym-trading-env-continuous

   ----------------------------------------  0/39 [pytz]
   ----------------------------------------  0/39 [pytz]
   ----------------------------------------  0/39 [pytz]
   ----------------------------------------  0/39 [pytz]
   - --------------------------------------  1/39 [farama-notifications]
   -- -------------------------------------  2/39 [urllib3]
   -- -------------------------------------  2/39 [urllib3]
   -- -------------------------------------  2/39 [urllib3]
   -- -------------------------------------  2/39 [urllib3]
   -- -------------------------------------  2/39 [urllib3]
   -- -------------------------------------  2/39 [urllib3]
   -- -------------------------------------  2/39 [urllib3]
   -- -------------------------------------  2/39 [urllib3]
   -- -------------------------------------  2/39 [urllib3]
   -- -------------------------------------  2/39 [urllib3]
   -- -------------------------------------  2/39 [urllib3]
   --- ------------------------------------  3/39 [tzdata]
   --- ------------------------------------  3/39 [tzdata]
   --- ------------------------------------  3/39 [tzdata]
   --- ------------------------------------  3/39 [tzdata]
   ----- ----------------------------------  5/39 [simplejson]
   ----- ----------------------------------  5/39 [simplejson]
   ----- ----------------------------------  5/39 [simplejson]
   ----- ----------------------------------  5/39 [simplejson]
   ----- ----------------------------------  5/39 [simplejson]
   ----- ----------------------------------  5/39 [simplejson]
   ----- ----------------------------------  5/39 [simplejson]
   ----- ----------------------------------  5/39 [simplejson]
   ----- ----------------------------------  5/39 [simplejson]
   ----- ----------------------------------  5/39 [simplejson]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------- --------------------------------  7/39 [pycparser]
   ------- --------------------------------  7/39 [pycparser]
   ------- --------------------------------  7/39 [pycparser]
   ------- --------------------------------  7/39 [pycparser]
   ------- --------------------------------  7/39 [pycparser]
   ------- --------------------------------  7/39 [pycparser]
   -------- -------------------------------  8/39 [propcache]
   --------- ------------------------------  9/39 [prettytable]
   --------- ------------------------------  9/39 [prettytable]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]

In [4]:
import pandas_ta as ta
import numpy as np

In [6]:
import pandas_ta as ta
import numpy as np

def preprocess_corrected(df):
    df = df.copy()
    
    df['feature_log_ret'] = np.log(df['close'] / df['close'].shift(1))

    df['feature_rsi'] = ta.rsi(df['close'], length=14) / 100.0 
    
    macd = ta.macd(df['close'])
    df['feature_macd_norm'] = macd['MACD_12_26_9'] / df['close']
    
    df['feature_atr_norm'] = ta.atr(df['high'], df['low'], df['close'], length=14) / df['close']
    
    df['feature_hour_sin'] = np.sin(2 * np.pi * df.index.hour / 24)
    df['feature_hour_cos'] = np.cos(2 * np.pi * df.index.hour / 24)

    df = df.dropna()
    
    df = df.replace([np.inf, -np.inf], 0)

    return df

In [7]:
from gym_trading_env.wrapper import DiscreteActionsWrapper

In [7]:
from gym_trading_env.wrapper import DiscreteActionsWrapper

def metric_portfolio_valuation(history):
    return round(history['portfolio_valuation', -1], 2)

def reward_function(history):
    return history['step']*(history['portfolio_valuation', -1] - history['portfolio_valuation', -2])

def reward_function_rapport_market(history):
    return 10*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1]))

def reward_function_rapport_market_v2(history):
    weight = 0 
    if (history['position',1] == history['position',-2]):
        weight = 0.1
    return 10*(history['data_open', -2] / history['data_close', -1])*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1])) - weight 

def reward_log_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = np.log(curr_val / prev_val)
    return reward

env = gym.make(
    "MultiDatasetTradingEnv",
    dataset_dir="data/*.pkl",
    preprocess=preprocess_corrected,
    reward_function=reward_log_returns,
    # Valeur initiale du portefeuille
    portfolio_initial_value=1_000,
    # Frais de transactions
    trading_fees=0.1/100,
    # Intérêts sur les prêts
    borrow_interest_rate=0.02/100/24,
)

env.add_metric('Portfolio Valuation', metric_portfolio_valuation)
env = DiscreteActionsWrapper(env, positions=[-1, 0, 1])
obs, _ = env.reset()

In [11]:
from stable_baselines3 import PPO

In [8]:
from stable_baselines3 import PPO

model = PPO("MlpPolicy",env)

model = model.learn(total_timesteps=1_000_000)

Market Return : 26.58%   |   Portfolio Return : -97.66%   |   Portfolio Valuation : 23.42   |
Market Return : 946.44%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.0   |
Market Return :  9.40%   |   Portfolio Return : -23.17%   |   Portfolio Valuation : 768.3   |
Market Return : 103.53%   |   Portfolio Return : 33.01%   |   Portfolio Valuation : 1330.08   |
Market Return :  5.93%   |   Portfolio Return : -2.23%   |   Portfolio Valuation : 977.66   |
Market Return : 43.37%   |   Portfolio Return : 39.13%   |   Portfolio Valuation : 1391.26   |
Market Return : 376.91%   |   Portfolio Return : 232.39%   |   Portfolio Valuation : 3323.86   |
Market Return : 43.37%   |   Portfolio Return : 40.84%   |   Portfolio Valuation : 1408.4   |
Market Return : 946.44%   |   Portfolio Return : 378.04%   |   Portfolio Valuation : 4780.42   |
Market Return : 699.62%   |   Portfolio Return : -68.27%   |   Portfolio Valuation : 317.3   |
Market Return : 103.53%   |   Portfolio Return : 86.52%   |   Portfolio Valuation : 1865.16   |
Market Return :  5.93%   |   Portfolio Return :  3.71%   |   Portfolio Valuation : 1037.07   |
Market Return : 26.58%   |   Portfolio Return : 26.54%   |   Portfolio Valuation : 1265.36   |
Market Return :  9.40%   |   Portfolio Return :  9.35%   |   Portfolio Valuation : 1093.54   |
Market Return : 553.19%   |   Portfolio Return : -104.82%   |   Portfolio Valuation : -48.21   |
Market Return : 39.77%   |   Portfolio Return : -11.87%   |   Portfolio Valuation : 881.26   |
Market Return :  9.40%   |   Portfolio Return : -53.59%   |   Portfolio Valuation : 464.1   |
Market Return : 43.37%   |   Portfolio Return : 21.76%   |   Portfolio Valuation : 1217.61   |
Market Return : 699.62%   |   Portfolio Return : -64.81%   |   Portfolio Valuation : 351.88   |
Market Return :  5.93%   |   Portfolio Return :  5.18%   |   Portfolio Valuation : 1051.84   |
Market Return : 376.91%   |   Portfolio Return : 325.32%   |   Portfolio Valuation : 4253.18   |
Market Return : 39.77%   |   Portfolio Return : 26.98%   |   Portfolio Valuation : 1269.77   |
Market Return : 26.58%   |   Portfolio Return : -12.56%   |   Portfolio Valuation : 874.37   |
Market Return : 103.53%   |   Portfolio Return : -46.77%   |   Portfolio Valuation : 532.28   |
Market Return : 946.44%   |   Portfolio Return : -92.83%   |   Portfolio Valuation : 71.68   |
Market Return : 376.91%   |   Portfolio Return : -76.56%   |   Portfolio Valuation : 234.37   |
Market Return :  5.93%   |   Portfolio Return : -63.18%   |   Portfolio Valuation : 368.24   |
Market Return : 103.53%   |   Portfolio Return : -37.26%   |   Portfolio Valuation : 627.38   |
Market Return : 699.62%   |   Portfolio Return : -94.71%   |   Portfolio Valuation : 52.85   |
Market Return :  9.40%   |   Portfolio Return : -2.52%   |   Portfolio Valuation : 974.82   |
Market Return : 946.44%   |   Portfolio Return : -87.11%   |   Portfolio Valuation : 128.94   |
Market Return : 26.58%   |   Portfolio Return : -0.57%   |   Portfolio Valuation : 994.29   |
Market Return : 43.37%   |   Portfolio Return : -49.59%   |   Portfolio Valuation : 504.08   |
Market Return : 39.77%   |   Portfolio Return : -46.02%   |   Portfolio Valuation : 539.79   |
Market Return : 946.44%   |   Portfolio Return : -87.30%   |   Portfolio Valuation : 126.99   |
Market Return : 376.91%   |   Portfolio Return : 12.27%   |   Portfolio Valuation : 1122.73   |
Market Return : 43.37%   |   Portfolio Return : -49.95%   |   Portfolio Valuation : 500.53   |
Market Return :  9.40%   |   Portfolio Return : -35.16%   |   Portfolio Valuation : 648.37   |
Market Return : 39.77%   |   Portfolio Return : -49.09%   |   Portfolio Valuation : 509.14   |
Market Return : 26.58%   |   Portfolio Return : -25.68%   |   Portfolio Valuation : 743.22   |
Market Return : 103.53%   |   Portfolio Return : -49.10%   |   Portfolio Valuation : 509.05   |
Market Return : 699.62%   |   Portfolio Return : -95.68%   |   Portfolio Valuation : 43.22   |
Market Return :  5.93%   |   Portfolio Return : -63.25%   |   Portfolio Valuation : 367.51   |
Market Return : 39.77%   |   Portfolio Return : -50.18%   |   Portfolio Valuation : 498.23   |
Market Return :  5.93%   |   Portfolio Return : -62.93%   |   Portfolio Valuation : 370.7   |
Market Return : 376.91%   |   Portfolio Return : 175.77%   |   Portfolio Valuation : 2757.74   |
Market Return : 43.37%   |   Portfolio Return : -48.77%   |   Portfolio Valuation : 512.26   |
Market Return :  9.40%   |   Portfolio Return : -46.75%   |   Portfolio Valuation : 532.47   |
Market Return : 946.44%   |   Portfolio Return : -99.90%   |   Portfolio Valuation : 0.95   |
Market Return : 103.53%   |   Portfolio Return : -76.37%   |   Portfolio Valuation : 236.29   |
Market Return : 699.62%   |   Portfolio Return : -98.53%   |   Portfolio Valuation : 14.7   |
Market Return : 26.58%   |   Portfolio Return : -6.75%   |   Portfolio Valuation : 932.46   |

In [9]:
nb_episodes = 30

for episode in range(1, nb_episodes + 1):
    obs, _ = env.reset()
    print(f'Episode n˚{episode} -- Jeu de donnée {env.env.name}')
    done = False

    while not done:
        action, _states = model.predict(obs)
        obs, reward, terminated, truncated, _ = env.step(action.tolist())
        done = terminated or truncated
    env.env.save_for_render(dir="logs")        
    if terminated:
        print('Argent perdu')
        
    elif truncated:
        print('Épisode terminé')

Episode n˚1 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : -46.21%   |   Portfolio Valuation : 537.92   |
Épisode terminé
Episode n˚2 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : -43.29%   |   Portfolio Valuation : 567.1   |
Épisode terminé
Episode n˚3 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return :  0.13%   |   Portfolio Valuation : 1001.33   |
Épisode terminé
Episode n˚4 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : -36.63%   |   Portfolio Valuation : 633.72   |
Épisode terminé
Episode n˚5 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -61.87%   |   Portfolio Valuation : 381.25   |
Épisode terminé
Episode n˚6 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : -3.97%   |   Portfolio Valuation : 960.33   |
Épisode terminé
Episode n˚7 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 376.91%   |   Portfolio Return : 165.03%   |   Portfolio Valuation : 2650.32   |
Épisode terminé
Episode n˚8 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : -92.13%   |   Portfolio Valuation : 78.74   |
Épisode terminé
Episode n˚9 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 946.44%   |   Portfolio Return : -87.68%   |   Portfolio Valuation : 123.21   |
Épisode terminé
Episode n˚10 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -61.43%   |   Portfolio Valuation : 385.73   |
Épisode terminé
Episode n˚11 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : -36.38%   |   Portfolio Valuation : 636.2   |
Épisode terminé
Episode n˚12 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : -2.56%   |   Portfolio Valuation : 974.38   |
Épisode terminé
Episode n˚13 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : -43.98%   |   Portfolio Valuation : 560.17   |
Épisode terminé
Episode n˚14 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : -91.70%   |   Portfolio Valuation : 82.99   |
Épisode terminé
Episode n˚15 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : -46.59%   |   Portfolio Valuation : 534.11   |
Épisode terminé
Episode n˚16 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 376.91%   |   Portfolio Return : 332.39%   |   Portfolio Valuation : 4323.86   |
Épisode terminé
Episode n˚17 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -2.82%   |   Portfolio Valuation : 971.79   |
Épisode terminé
Episode n˚18 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : -89.20%   |   Portfolio Valuation : 107.95   |
Épisode terminé
Episode n˚19 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 946.44%   |   Portfolio Return : -88.01%   |   Portfolio Valuation : 119.85   |
Épisode terminé
Episode n˚20 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -61.20%   |   Portfolio Valuation : 387.95   |
Épisode terminé
Episode n˚21 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 376.91%   |   Portfolio Return : 128.91%   |   Portfolio Valuation : 2289.09   |
Épisode terminé
Episode n˚22 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -1.99%   |   Portfolio Valuation : 980.14   |
Épisode terminé
Episode n˚23 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : -46.83%   |   Portfolio Valuation : 531.66   |
Épisode terminé
Episode n˚24 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : -37.83%   |   Portfolio Valuation : 621.71   |
Épisode terminé
Episode n˚25 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : -44.11%   |   Portfolio Valuation : 558.87   |
Épisode terminé
Episode n˚26 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : -1.20%   |   Portfolio Valuation : 988.0   |
Épisode terminé
Episode n˚27 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : -2.78%   |   Portfolio Valuation : 972.18   |
Épisode terminé
Episode n˚28 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : -46.29%   |   Portfolio Valuation : 537.11   |
Épisode terminé
Episode n˚29 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : -92.28%   |   Portfolio Valuation : 77.2   |
Épisode terminé
Episode n˚30 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : -46.63%   |   Portfolio Valuation : 533.69   |
Épisode terminé

In [12]:
def preprocess_corrected(df):
    df = df.copy()
    
    df['feature_log_ret'] = np.log(df['close'] / df['close'].shift(1))

    df['feature_rsi'] = ta.rsi(df['close'], length=14) / 100.0 
    
    macd = ta.macd(df['close'])
    df['feature_macd_norm'] = macd['MACD_12_26_9'] / df['close']
    
    df['feature_atr_norm'] = ta.atr(df['high'], df['low'], df['close'], length=14) / df['close']
    
    df['feature_hour_sin'] = np.sin(2 * np.pi * df.index.hour / 24)
    df['feature_hour_cos'] = np.cos(2 * np.pi * df.index.hour / 24)

    df = df.dropna()
    
    df = df.replace([np.inf, -np.inf], 0)

    return df


def metric_portfolio_valuation(history):
    return round(history['portfolio_valuation', -1], 2)

def reward_function(history):
    return history['step']*(history['portfolio_valuation', -1] - history['portfolio_valuation', -2])

def reward_function_rapport_market(history):
    return 10*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1]))

def reward_function_rapport_market_v2(history):
    weight = 0 
    if (history['position',1] == history['position',-2]):
        weight = 0.1
    return 10*(history['data_open', -2] / history['data_close', -1])*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1])) - weight 

def reward_log_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = np.log(curr_val / prev_val)
    return reward

def reward_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = (curr_val - prev_val) / prev_val
    return reward

env = gym.make(
    "MultiDatasetTradingEnv",
    dataset_dir="data/*.pkl",
    preprocess=preprocess_corrected,
    reward_function=reward_returns,
    # Valeur initiale du portefeuille
    portfolio_initial_value=1_000,
    # Frais de transactions
    trading_fees=0.1/100,
    # Intérêts sur les prêts
    borrow_interest_rate=0.02/100/24,
)

env.add_metric('Portfolio Valuation', metric_portfolio_valuation)
env = DiscreteActionsWrapper(env, positions=[-1, 0, 0.5, 1,2])
obs, _ = env.reset()

model = PPO("MlpPolicy",env)

model = model.learn(total_timesteps=1_500_000)

Market Return : 43.37%   |   Portfolio Return : -97.53%   |   Portfolio Valuation : 24.66   |
Market Return : 26.58%   |   Portfolio Return : -98.95%   |   Portfolio Valuation : 10.5   |
Market Return :  9.40%   |   Portfolio Return : -98.34%   |   Portfolio Valuation : 16.62   |
Market Return : 39.77%   |   Portfolio Return : -95.20%   |   Portfolio Valuation : 47.96   |
Market Return : 103.53%   |   Portfolio Return : -99.82%   |   Portfolio Valuation : 1.79   |
Market Return : 946.44%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.01   |
Market Return :  5.93%   |   Portfolio Return : -54.17%   |   Portfolio Valuation : 458.28   |
Market Return : 39.77%   |   Portfolio Return : 76.58%   |   Portfolio Valuation : 1765.76   |
Market Return : 351.97%   |   Portfolio Return : -100.70%   |   Portfolio Valuation : -7.04   |
Market Return : 26.58%   |   Portfolio Return : 47.12%   |   Portfolio Valuation : 1471.24   |
Market Return :  5.93%   |   Portfolio Return :  9.70%   |   Portfolio Valuation : 1096.96   |
Market Return :  9.40%   |   Portfolio Return : 18.63%   |   Portfolio Valuation : 1186.3   |
Market Return : 699.62%   |   Portfolio Return : 2172.11%   |   Portfolio Valuation : 22721.14   |
Market Return : 43.37%   |   Portfolio Return : 86.51%   |   Portfolio Valuation : 1865.11   |
Market Return : 223.70%   |   Portfolio Return : -114.55%   |   Portfolio Valuation : -145.52   |
Market Return : 103.53%   |   Portfolio Return : 261.69%   |   Portfolio Valuation : 3616.91   |
Market Return : 235.14%   |   Portfolio Return : -115.22%   |   Portfolio Valuation : -152.25   |
Market Return : 39.77%   |   Portfolio Return : 76.14%   |   Portfolio Valuation : 1761.42   |
Market Return :  9.40%   |   Portfolio Return : 14.50%   |   Portfolio Valuation : 1144.98   |
Market Return : 26.58%   |   Portfolio Return : 55.59%   |   Portfolio Valuation : 1555.89   |
Market Return : 699.62%   |   Portfolio Return : 116.12%   |   Portfolio Valuation : 2161.21   |
Market Return : 43.37%   |   Portfolio Return : 96.64%   |   Portfolio Valuation : 1966.38   |
Market Return : 103.53%   |   Portfolio Return : 153.58%   |   Portfolio Valuation : 2535.79   |
Market Return : 504.01%   |   Portfolio Return : -102.74%   |   Portfolio Valuation : -27.37   |
Market Return :  5.93%   |   Portfolio Return : -39.08%   |   Portfolio Valuation : 609.24   |
Market Return : 43.37%   |   Portfolio Return : 91.46%   |   Portfolio Valuation : 1914.59   |
Market Return :  9.40%   |   Portfolio Return : 15.38%   |   Portfolio Valuation : 1153.76   |
Market Return : 39.77%   |   Portfolio Return : 81.51%   |   Portfolio Valuation : 1815.13   |
Market Return :  5.93%   |   Portfolio Return :  8.60%   |   Portfolio Valuation : 1085.98   |
Market Return : 497.35%   |   Portfolio Return : -147.90%   |   Portfolio Valuation : -478.97   |
Market Return : 103.53%   |   Portfolio Return : 158.19%   |   Portfolio Valuation : 2581.86   |
Market Return : 392.20%   |   Portfolio Return : -274.01%   |   Portfolio Valuation : -1740.13   |
Market Return : 175.57%   |   Portfolio Return : -105.17%   |   Portfolio Valuation : -51.75   |
Market Return : 26.58%   |   Portfolio Return : 52.88%   |   Portfolio Valuation : 1528.79   |
Market Return :  9.40%   |   Portfolio Return : 18.72%   |   Portfolio Valuation : 1187.24   |
Market Return :  5.93%   |   Portfolio Return : -43.87%   |   Portfolio Valuation : 561.34   |
Market Return : 39.77%   |   Portfolio Return : 86.71%   |   Portfolio Valuation : 1867.06   |
Market Return : 103.53%   |   Portfolio Return : 196.44%   |   Portfolio Valuation : 2964.35   |
Market Return : 497.35%   |   Portfolio Return : -118.17%   |   Portfolio Valuation : -181.72   |
Market Return : 26.58%   |   Portfolio Return : 51.44%   |   Portfolio Valuation : 1514.39   |
Market Return : 43.37%   |   Portfolio Return : 92.54%   |   Portfolio Valuation : 1925.37   |
Market Return : 317.93%   |   Portfolio Return : -138.40%   |   Portfolio Valuation : -384.04   |
Market Return : 699.62%   |   Portfolio Return : -6.32%   |   Portfolio Valuation : 936.84   |
Market Return : 504.01%   |   Portfolio Return : -120.19%   |   Portfolio Valuation : -201.91   |
Market Return : 699.62%   |   Portfolio Return : 404.60%   |   Portfolio Valuation : 5045.97   |
Market Return : 103.53%   |   Portfolio Return : 259.82%   |   Portfolio Valuation : 3598.22   |
Market Return : 334.02%   |   Portfolio Return : -165.61%   |   Portfolio Valuation : -656.06   |
Market Return :  9.40%   |   Portfolio Return : 14.99%   |   Portfolio Valuation : 1149.85   |
Market Return :  5.93%   |   Portfolio Return : -1.71%   |   Portfolio Valuation : 982.94   |
Market Return : 26.58%   |   Portfolio Return : 54.78%   |   Portfolio Valuation : 1547.78   |
Market Return : 39.77%   |   Portfolio Return : 81.63%   |   Portfolio Valuation : 1816.29   |
Market Return : 43.37%   |   Portfolio Return : 97.04%   |   Portfolio Valuation : 1970.38   |
Market Return :  9.40%   |   Portfolio Return : 12.51%   |   Portfolio Valuation : 1125.13   |
Market Return : 685.28%   |   Portfolio Return : -713.74%   |   Portfolio Valuation : -6137.38   |
Market Return : 65.92%   |   Portfolio Return : -102.97%   |   Portfolio Valuation : -29.67   |
Market Return : 103.53%   |   Portfolio Return : 236.66%   |   Portfolio Valuation : 3366.62   |
Market Return : 26.58%   |   Portfolio Return : 52.64%   |   Portfolio Valuation : 1526.36   |
Market Return : 275.57%   |   Portfolio Return : -108.07%   |   Portfolio Valuation : -80.66   |
Market Return : 39.77%   |   Portfolio Return : 69.66%   |   Portfolio Valuation : 1696.59   |
Market Return : 43.37%   |   Portfolio Return : 96.36%   |   Portfolio Valuation : 1963.58   |
Market Return :  5.93%   |   Portfolio Return :  3.44%   |   Portfolio Valuation : 1034.41   |
Market Return :  9.40%   |   Portfolio Return : 14.81%   |   Portfolio Valuation : 1148.1   |
Market Return : 39.77%   |   Portfolio Return : 79.54%   |   Portfolio Valuation : 1795.44   |
Market Return : 26.58%   |   Portfolio Return : 55.02%   |   Portfolio Valuation : 1550.23   |
Market Return : 69.60%   |   Portfolio Return : -111.23%   |   Portfolio Valuation : -112.35   |
Market Return : 43.37%   |   Portfolio Return : 95.76%   |   Portfolio Valuation : 1957.64   |
Market Return : 103.53%   |   Portfolio Return : 265.44%   |   Portfolio Valuation : 3654.45   |
Market Return : 392.20%   |   Portfolio Return : -118.80%   |   Portfolio Valuation : -187.99   |
Market Return : 394.28%   |   Portfolio Return : -102.89%   |   Portfolio Valuation : -28.9   |
Market Return :  5.93%   |   Portfolio Return :  9.47%   |   Portfolio Valuation : 1094.69   |
Market Return : 26.58%   |   Portfolio Return : 55.33%   |   Portfolio Valuation : 1553.35   |
Market Return : 39.77%   |   Portfolio Return : 77.23%   |   Portfolio Valuation : 1772.29   |
Market Return : 699.62%   |   Portfolio Return : 155.09%   |   Portfolio Valuation : 2550.95   |
Market Return :  5.93%   |   Portfolio Return : -1.90%   |   Portfolio Valuation : 981.01   |
Market Return : 103.53%   |   Portfolio Return : 260.28%   |   Portfolio Valuation : 3602.81   |
Market Return : 579.70%   |   Portfolio Return : -311.26%   |   Portfolio Valuation : -2112.64   |
Market Return : 306.85%   |   Portfolio Return : -119.53%   |   Portfolio Valuation : -195.29   |
Market Return :  9.40%   |   Portfolio Return : 18.60%   |   Portfolio Valuation : 1186.0   |
Market Return : 43.37%   |   Portfolio Return : 94.78%   |   Portfolio Valuation : 1947.84   |
Market Return :  9.40%   |   Portfolio Return : 11.38%   |   Portfolio Valuation : 1113.8   |
Market Return :  5.93%   |   Portfolio Return : -1.66%   |   Portfolio Valuation : 983.36   |
Market Return : 946.44%   |   Portfolio Return : -72.79%   |   Portfolio Valuation : 272.15   |
Market Return : 76.78%   |   Portfolio Return : -100.06%   |   Portfolio Valuation : -0.65   |
Market Return : 43.37%   |   Portfolio Return : 94.13%   |   Portfolio Valuation : 1941.35   |
Market Return : 39.77%   |   Portfolio Return : 84.11%   |   Portfolio Valuation : 1841.08   |
Market Return : 103.53%   |   Portfolio Return : 260.79%   |   Portfolio Valuation : 3607.92   |
Market Return : 504.01%   |   Portfolio Return : -125.78%   |   Portfolio Valuation : -257.83   |
Market Return : 26.58%   |   Portfolio Return : 52.94%   |   Portfolio Valuation : 1529.38   |
Market Return : 369.71%   |   Portfolio Return : -180.70%   |   Portfolio Valuation : -806.97   |
Market Return :  5.93%   |   Portfolio Return : -6.05%   |   Portfolio Valuation : 939.5   |
Market Return : 69.60%   |   Portfolio Return : -103.13%   |   Portfolio Valuation : -31.28   |
Market Return :  9.40%   |   Portfolio Return : 18.69%   |   Portfolio Valuation : 1186.9   |
Market Return : 103.53%   |   Portfolio Return : 261.89%   |   Portfolio Valuation : 3618.95   |
Market Return : 114.68%   |   Portfolio Return : -104.47%   |   Portfolio Valuation : -44.7   |
Market Return : 39.77%   |   Portfolio Return : 77.15%   |   Portfolio Valuation : 1771.54   |
Market Return : 43.37%   |   Portfolio Return : 100.66%   |   Portfolio Valuation : 2006.6   |
Market Return : 26.58%   |   Portfolio Return : -57.77%   |   Portfolio Valuation : 422.3   |
Market Return :  5.93%   |   Portfolio Return : -60.74%   |   Portfolio Valuation : 392.56   |
Market Return : 26.58%   |   Portfolio Return : 42.10%   |   Portfolio Valuation : 1420.99   |
Market Return : 103.53%   |   Portfolio Return : 263.31%   |   Portfolio Valuation : 3633.13   |
Market Return : 685.28%   |   Portfolio Return : -893.09%   |   Portfolio Valuation : -7930.88   |
Market Return :  9.40%   |   Portfolio Return : 17.40%   |   Portfolio Valuation : 1174.03   |
Market Return : 699.62%   |   Portfolio Return : -99.34%   |   Portfolio Valuation : 6.56   |
Market Return : 43.37%   |   Portfolio Return : 60.17%   |   Portfolio Valuation : 1601.69   |
Market Return : 369.71%   |   Portfolio Return : -228.07%   |   Portfolio Valuation : -1280.66   |
Market Return : 39.77%   |   Portfolio Return : 78.19%   |   Portfolio Valuation : 1781.89   |
Market Return : 672.24%   |   Portfolio Return : -110.26%   |   Portfolio Valuation : -102.64   |
Market Return : 39.77%   |   Portfolio Return : 77.01%   |   Portfolio Valuation : 1770.14   |
Market Return : 26.58%   |   Portfolio Return : 48.50%   |   Portfolio Valuation : 1485.05   |
Market Return : 177.46%   |   Portfolio Return : -101.04%   |   Portfolio Valuation : -10.36   |
Market Return :  5.93%   |   Portfolio Return : -86.00%   |   Portfolio Valuation : 139.96   |
Market Return : 392.20%   |   Portfolio Return : -252.63%   |   Portfolio Valuation : -1526.26   |
Market Return : 43.37%   |   Portfolio Return : 67.58%   |   Portfolio Valuation : 1675.79   |
Market Return : 103.53%   |   Portfolio Return : 114.85%   |   Portfolio Valuation : 2148.5   |
Market Return :  9.40%   |   Portfolio Return : 18.64%   |   Portfolio Valuation : 1186.43   |
Market Return : 685.28%   |   Portfolio Return : -3550.61%   |   Portfolio Valuation : -34506.08   |
Market Return : 26.58%   |   Portfolio Return : 53.00%   |   Portfolio Valuation : 1529.98   |
Market Return : 369.71%   |   Portfolio Return : -308.21%   |   Portfolio Valuation : -2082.14   |
Market Return : 103.53%   |   Portfolio Return : 91.34%   |   Portfolio Valuation : 1913.38   |
Market Return : 148.20%   |   Portfolio Return : -134.69%   |   Portfolio Valuation : -346.87   |
Market Return :  5.93%   |   Portfolio Return : -46.67%   |   Portfolio Valuation : 533.27   |
Market Return :  9.40%   |   Portfolio Return : 14.90%   |   Portfolio Valuation : 1148.97   |
Market Return : 43.37%   |   Portfolio Return : 94.70%   |   Portfolio Valuation : 1947.01   |
Market Return : 39.77%   |   Portfolio Return : 88.36%   |   Portfolio Valuation : 1883.55   |
Market Return : 672.24%   |   Portfolio Return : -166.55%   |   Portfolio Valuation : -665.46   |
Market Return :  5.93%   |   Portfolio Return : -24.87%   |   Portfolio Valuation : 751.34   |
Market Return : 103.53%   |   Portfolio Return : -71.56%   |   Portfolio Valuation : 284.41   |
Market Return : 39.77%   |   Portfolio Return : -24.99%   |   Portfolio Valuation : 750.06   |
Market Return :  9.40%   |   Portfolio Return : -10.19%   |   Portfolio Valuation : 898.15   |
Market Return : 68.04%   |   Portfolio Return : -100.78%   |   Portfolio Valuation : -7.8   |
Market Return : 26.58%   |   Portfolio Return : 17.65%   |   Portfolio Valuation : 1176.51   |
Market Return : 43.37%   |   Portfolio Return : 39.31%   |   Portfolio Valuation : 1393.13   |
Market Return : 334.51%   |   Portfolio Return : -100.27%   |   Portfolio Valuation : -2.73   |
Market Return : 685.28%   |   Portfolio Return : -729.36%   |   Portfolio Valuation : -6293.58   |
Market Return : 39.77%   |   Portfolio Return : 59.67%   |   Portfolio Valuation : 1596.69   |
Market Return : 103.53%   |   Portfolio Return : 263.44%   |   Portfolio Valuation : 3634.41   |
Market Return :  5.93%   |   Portfolio Return :  9.60%   |   Portfolio Valuation : 1095.96   |
Market Return : 347.65%   |   Portfolio Return : -281.00%   |   Portfolio Valuation : -1810.04   |
Market Return : 43.37%   |   Portfolio Return : 69.44%   |   Portfolio Valuation : 1694.37   |
Market Return : 177.20%   |   Portfolio Return : -135.39%   |   Portfolio Valuation : -353.86   |
Market Return :  9.40%   |   Portfolio Return : 13.66%   |   Portfolio Valuation : 1136.62   |
Market Return : 26.58%   |   Portfolio Return : 44.79%   |   Portfolio Valuation : 1447.86   |
Market Return : 369.71%   |   Portfolio Return : -282.86%   |   Portfolio Valuation : -1828.59   |
Market Return : 26.58%   |   Portfolio Return : 45.95%   |   Portfolio Valuation : 1459.53   |
Market Return : 43.37%   |   Portfolio Return : 46.46%   |   Portfolio Valuation : 1464.61   |
Market Return :  5.93%   |   Portfolio Return :  1.30%   |   Portfolio Valuation : 1012.97   |
Market Return : 39.77%   |   Portfolio Return : 86.35%   |   Portfolio Valuation : 1863.51   |
Market Return :  9.40%   |   Portfolio Return : 18.66%   |   Portfolio Valuation : 1186.57   |
Market Return : 103.53%   |   Portfolio Return : 278.26%   |   Portfolio Valuation : 3782.59   |
Market Return : 186.86%   |   Portfolio Return : -112.91%   |   Portfolio Valuation : -129.07   |
Market Return : 685.28%   |   Portfolio Return : -2904.01%   |   Portfolio Valuation : -28040.11   |
Market Return : 99.02%   |   Portfolio Return : -117.96%   |   Portfolio Valuation : -179.56   |
Market Return : 39.77%   |   Portfolio Return : 52.32%   |   Portfolio Valuation : 1523.24   |
Market Return :  5.93%   |   Portfolio Return : -64.85%   |   Portfolio Valuation : 351.55   |
Market Return : 43.37%   |   Portfolio Return : 81.52%   |   Portfolio Valuation : 1815.2   |
Market Return : 26.58%   |   Portfolio Return : 52.81%   |   Portfolio Valuation : 1528.13   |
Market Return : 103.53%   |   Portfolio Return : 277.83%   |   Portfolio Valuation : 3778.3   |

In [13]:
nb_episodes = 30

for episode in range(1, nb_episodes + 1):
    obs, _ = env.reset()
    print(f'Episode n˚{episode} -- Jeu de donnée {env.env.name}')
    done = False

    while not done:
        action, _states = model.predict(obs)
        obs, reward, terminated, truncated, _ = env.step(action.tolist())
        done = terminated or truncated
    env.env.save_for_render(dir="logs")        
    if terminated:
        print('Argent perdu')
        
    elif truncated:
        print('Épisode terminé')

Episode n˚1 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -12.12%   |   Portfolio Valuation : 878.83   |
Épisode terminé
Episode n˚2 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 685.28%   |   Portfolio Return : -653.78%   |   Portfolio Valuation : -5537.75   |
Argent perdu
Episode n˚3 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -24.12%   |   Portfolio Valuation : 758.77   |
Épisode terminé
Episode n˚4 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : 46.06%   |   Portfolio Valuation : 1460.65   |
Épisode terminé
Episode n˚5 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : 65.91%   |   Portfolio Valuation : 1659.11   |
Épisode terminé
Episode n˚6 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : 10.22%   |   Portfolio Valuation : 1102.24   |
Épisode terminé
Episode n˚7 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 175.57%   |   Portfolio Return : -103.03%   |   Portfolio Valuation : -30.29   |
Argent perdu
Episode n˚8 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 369.71%   |   Portfolio Return : -253.22%   |   Portfolio Valuation : -1532.19   |
Argent perdu
Episode n˚9 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 685.28%   |   Portfolio Return : -608.39%   |   Portfolio Valuation : -5083.89   |
Argent perdu
Episode n˚10 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -7.23%   |   Portfolio Valuation : 927.75   |
Épisode terminé
Episode n˚11 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : 61.02%   |   Portfolio Valuation : 1610.22   |
Épisode terminé
Episode n˚12 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 422.77%   |   Portfolio Return : -103.76%   |   Portfolio Valuation : -37.63   |
Argent perdu
Episode n˚13 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : 57.60%   |   Portfolio Valuation : 1575.95   |
Épisode terminé
Episode n˚14 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -28.18%   |   Portfolio Valuation : 718.25   |
Épisode terminé
Episode n˚15 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 685.28%   |   Portfolio Return : -938.52%   |   Portfolio Valuation : -8385.23   |
Argent perdu
Episode n˚16 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return :  3.78%   |   Portfolio Valuation : 1037.76   |
Épisode terminé
Episode n˚17 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 186.86%   |   Portfolio Return : -108.28%   |   Portfolio Valuation : -82.79   |
Argent perdu
Episode n˚18 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : 51.03%   |   Portfolio Valuation : 1510.26   |
Épisode terminé
Episode n˚19 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -28.21%   |   Portfolio Valuation : 717.87   |
Épisode terminé
Episode n˚20 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : 118.92%   |   Portfolio Valuation : 2189.16   |
Épisode terminé
Episode n˚21 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -20.74%   |   Portfolio Valuation : 792.6   |
Épisode terminé
Episode n˚22 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : 57.45%   |   Portfolio Valuation : 1574.46   |
Épisode terminé
Episode n˚23 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -30.40%   |   Portfolio Valuation : 695.95   |
Épisode terminé
Episode n˚24 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : 81.81%   |   Portfolio Valuation : 1818.14   |
Épisode terminé
Episode n˚25 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 347.65%   |   Portfolio Return : -215.16%   |   Portfolio Valuation : -1151.56   |
Argent perdu
Episode n˚26 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : 96.84%   |   Portfolio Valuation : 1968.44   |
Épisode terminé
Episode n˚27 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return :  1.96%   |   Portfolio Valuation : 1019.64   |
Épisode terminé
Episode n˚28 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 685.28%   |   Portfolio Return : -252.72%   |   Portfolio Valuation : -1527.25   |
Argent perdu
Episode n˚29 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 161.14%   |   Portfolio Return : -153.28%   |   Portfolio Valuation : -532.79   |
Argent perdu
Episode n˚30 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 161.14%   |   Portfolio Return : -156.01%   |   Portfolio Valuation : -560.09   |
Argent perdu

In [15]:
def preprocess_corrected(df):
    df = df.copy()
    
    df['feature_log_ret'] = np.log(df['close'] / df['close'].shift(1))

    df['feature_rsi'] = ta.rsi(df['close'], length=14) / 100.0 
    
    macd = ta.macd(df['close'])
    df['feature_macd_norm'] = macd['MACD_12_26_9'] / df['close']
    
    df['feature_atr_norm'] = ta.atr(df['high'], df['low'], df['close'], length=14) / df['close']
    
    df['feature_hour_sin'] = np.sin(2 * np.pi * df.index.hour / 24)
    df['feature_hour_cos'] = np.cos(2 * np.pi * df.index.hour / 24)

    df = df.dropna()
    
    df = df.replace([np.inf, -np.inf], 0)

    return df


def metric_portfolio_valuation(history):
    return round(history['portfolio_valuation', -1], 2)

def reward_function(history):
    return history['step']*(history['portfolio_valuation', -1] - history['portfolio_valuation', -2])

def reward_function_rapport_market(history):
    return 10*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1]))

def reward_function_rapport_market_v2(history):
    weight = 0 
    if (history['position',1] == history['position',-2]):
        weight = 0.1
    return 10*(history['data_open', -2] / history['data_close', -1])*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1])) - weight 

def reward_log_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = np.log(curr_val / prev_val)
    return reward

def reward_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = (curr_val - prev_val) / prev_val
    return reward

env = gym.make(
    "MultiDatasetTradingEnv",
    dataset_dir="data/*.pkl",
    preprocess=preprocess_corrected,
    reward_function=reward_returns,
    # Valeur initiale du portefeuille
    portfolio_initial_value=1_000,
    # Frais de transactions
    trading_fees=0.1/100,
    # Intérêts sur les prêts
    borrow_interest_rate=0.02/100/24,
)

env.add_metric('Portfolio Valuation', metric_portfolio_valuation)
env = DiscreteActionsWrapper(env, positions=[0, 1])
obs, _ = env.reset()

model = PPO("MlpPolicy",env)

model = model.learn(total_timesteps=1_500_000)
model.save("PPO_v6")

Market Return : 103.53%   |   Portfolio Return : -98.82%   |   Portfolio Valuation : 11.78   |
Market Return : 43.37%   |   Portfolio Return : -57.29%   |   Portfolio Valuation : 427.08   |
Market Return : 26.58%   |   Portfolio Return : -53.04%   |   Portfolio Valuation : 469.6   |
Market Return : 39.77%   |   Portfolio Return : -26.26%   |   Portfolio Valuation : 737.43   |
Market Return : 376.91%   |   Portfolio Return : -98.31%   |   Portfolio Valuation : 16.95   |
Market Return :  5.93%   |   Portfolio Return : -26.75%   |   Portfolio Valuation : 732.51   |
Market Return : 699.62%   |   Portfolio Return : 21.96%   |   Portfolio Valuation : 1219.63   |
Market Return : 699.62%   |   Portfolio Return : -8.81%   |   Portfolio Valuation : 911.94   |
Market Return : 946.44%   |   Portfolio Return : -41.61%   |   Portfolio Valuation : 583.87   |
Market Return : 376.91%   |   Portfolio Return : -68.54%   |   Portfolio Valuation : 314.56   |
Market Return : 43.37%   |   Portfolio Return :  1.41%   |   Portfolio Valuation : 1014.07   |
Market Return : 26.58%   |   Portfolio Return : -5.99%   |   Portfolio Valuation : 940.11   |
Market Return : 103.53%   |   Portfolio Return : -22.20%   |   Portfolio Valuation : 777.98   |
Market Return :  5.93%   |   Portfolio Return : -17.08%   |   Portfolio Valuation : 829.21   |
Market Return :  9.40%   |   Portfolio Return :  3.63%   |   Portfolio Valuation : 1036.26   |
Market Return : 39.77%   |   Portfolio Return : 35.95%   |   Portfolio Valuation : 1359.52   |
Market Return :  9.40%   |   Portfolio Return : 14.39%   |   Portfolio Valuation : 1143.92   |
Market Return : 39.77%   |   Portfolio Return : 40.96%   |   Portfolio Valuation : 1409.58   |
Market Return : 43.37%   |   Portfolio Return : 43.69%   |   Portfolio Valuation : 1436.86   |
Market Return : 699.62%   |   Portfolio Return : 758.59%   |   Portfolio Valuation : 8585.9   |
Market Return :  5.93%   |   Portfolio Return : -4.41%   |   Portfolio Valuation : 955.92   |
Market Return : 103.53%   |   Portfolio Return : -28.39%   |   Portfolio Valuation : 716.14   |
Market Return : 946.44%   |   Portfolio Return : 174.76%   |   Portfolio Valuation : 2747.59   |
Market Return : 26.58%   |   Portfolio Return :  5.52%   |   Portfolio Valuation : 1055.17   |
Market Return : 376.91%   |   Portfolio Return : 340.03%   |   Portfolio Valuation : 4400.34   |
Market Return : 699.62%   |   Portfolio Return : 683.53%   |   Portfolio Valuation : 7835.35   |
Market Return : 946.44%   |   Portfolio Return : 664.24%   |   Portfolio Valuation : 7642.44   |
Market Return :  9.40%   |   Portfolio Return :  9.30%   |   Portfolio Valuation : 1092.98   |
Market Return : 376.91%   |   Portfolio Return : 410.58%   |   Portfolio Valuation : 5105.78   |
Market Return : 26.58%   |   Portfolio Return : 26.46%   |   Portfolio Valuation : 1264.6   |
Market Return :  5.93%   |   Portfolio Return :  5.93%   |   Portfolio Valuation : 1059.26   |
Market Return : 43.37%   |   Portfolio Return : 43.33%   |   Portfolio Valuation : 1433.33   |
Market Return : 103.53%   |   Portfolio Return : 103.34%   |   Portfolio Valuation : 2033.36   |
Market Return : 39.77%   |   Portfolio Return : 39.71%   |   Portfolio Valuation : 1397.05   |
Market Return : 26.58%   |   Portfolio Return : 26.51%   |   Portfolio Valuation : 1265.12   |
Market Return : 43.37%   |   Portfolio Return : 43.24%   |   Portfolio Valuation : 1432.42   |
Market Return : 699.62%   |   Portfolio Return : 149.81%   |   Portfolio Valuation : 2498.15   |
Market Return :  5.93%   |   Portfolio Return : -33.36%   |   Portfolio Valuation : 666.37   |
Market Return :  9.40%   |   Portfolio Return :  8.83%   |   Portfolio Valuation : 1088.26   |
Market Return : 103.53%   |   Portfolio Return : 87.67%   |   Portfolio Valuation : 1876.69   |
Market Return : 39.77%   |   Portfolio Return : 36.85%   |   Portfolio Valuation : 1368.52   |
Market Return : 376.91%   |   Portfolio Return : 353.85%   |   Portfolio Valuation : 4538.53   |
Market Return : 946.44%   |   Portfolio Return : 946.30%   |   Portfolio Valuation : 10463.01   |
Market Return : 39.77%   |   Portfolio Return : 39.66%   |   Portfolio Valuation : 1396.64   |
Market Return : 43.37%   |   Portfolio Return : 43.23%   |   Portfolio Valuation : 1432.29   |
Market Return :  9.40%   |   Portfolio Return :  9.30%   |   Portfolio Valuation : 1092.97   |
Market Return : 376.91%   |   Portfolio Return : 374.06%   |   Portfolio Valuation : 4740.63   |
Market Return : 946.44%   |   Portfolio Return : 169.18%   |   Portfolio Valuation : 2691.79   |
Market Return : 103.53%   |   Portfolio Return : 53.94%   |   Portfolio Valuation : 1539.35   |
Market Return : 26.58%   |   Portfolio Return : 26.14%   |   Portfolio Valuation : 1261.4   |
Market Return : 699.62%   |   Portfolio Return : 129.99%   |   Portfolio Valuation : 2299.89   |
Market Return :  5.93%   |   Portfolio Return :  3.50%   |   Portfolio Valuation : 1035.01   |
Market Return : 946.44%   |   Portfolio Return : 871.01%   |   Portfolio Valuation : 9710.06   |
Market Return : 26.58%   |   Portfolio Return : 26.53%   |   Portfolio Valuation : 1265.29   |
Market Return : 699.62%   |   Portfolio Return : 638.62%   |   Portfolio Valuation : 7386.23   |
Market Return :  9.40%   |   Portfolio Return :  8.94%   |   Portfolio Valuation : 1089.4   |
Market Return : 43.37%   |   Portfolio Return : 43.27%   |   Portfolio Valuation : 1432.71   |
Market Return : 376.91%   |   Portfolio Return : -65.88%   |   Portfolio Valuation : 341.17   |
Market Return : 103.53%   |   Portfolio Return : 101.81%   |   Portfolio Valuation : 2018.14   |
Market Return : 39.77%   |   Portfolio Return : 39.66%   |   Portfolio Valuation : 1396.6   |
Market Return :  5.93%   |   Portfolio Return :  5.47%   |   Portfolio Valuation : 1054.66   |
Market Return :  5.93%   |   Portfolio Return :  5.64%   |   Portfolio Valuation : 1056.42   |
Market Return : 376.91%   |   Portfolio Return : 36.63%   |   Portfolio Valuation : 1366.26   |
Market Return : 43.37%   |   Portfolio Return : 43.94%   |   Portfolio Valuation : 1439.45   |
Market Return :  9.40%   |   Portfolio Return :  9.38%   |   Portfolio Valuation : 1093.82   |
Market Return : 26.58%   |   Portfolio Return : 26.46%   |   Portfolio Valuation : 1264.62   |
Market Return : 39.77%   |   Portfolio Return :  2.54%   |   Portfolio Valuation : 1025.41   |
Market Return : 103.53%   |   Portfolio Return : 11.65%   |   Portfolio Valuation : 1116.54   |
Market Return : 946.44%   |   Portfolio Return : 407.41%   |   Portfolio Valuation : 5074.08   |
Market Return : 699.62%   |   Portfolio Return : 434.69%   |   Portfolio Valuation : 5346.92   |
Market Return : 946.44%   |   Portfolio Return : 622.71%   |   Portfolio Valuation : 7227.07   |
Market Return :  9.40%   |   Portfolio Return : -2.38%   |   Portfolio Valuation : 976.16   |
Market Return : 376.91%   |   Portfolio Return : 485.93%   |   Portfolio Valuation : 5859.27   |
Market Return : 43.37%   |   Portfolio Return : 42.95%   |   Portfolio Valuation : 1429.48   |
Market Return : 103.53%   |   Portfolio Return : 103.52%   |   Portfolio Valuation : 2035.22   |
Market Return :  5.93%   |   Portfolio Return :  5.70%   |   Portfolio Valuation : 1056.98   |
Market Return : 26.58%   |   Portfolio Return : 26.46%   |   Portfolio Valuation : 1264.65   |
Market Return : 699.62%   |   Portfolio Return : 673.31%   |   Portfolio Valuation : 7733.12   |

In [16]:
nb_episodes = 30

for episode in range(1, nb_episodes + 1):
    obs, _ = env.reset()
    print(f'Episode n˚{episode} -- Jeu de donnée {env.env.name}')
    done = False

    while not done:
        action, _states = model.predict(obs)
        obs, reward, terminated, truncated, _ = env.step(action.tolist())
        done = terminated or truncated
    env.env.save_for_render(dir="logs")        
    if terminated:
        print('Argent perdu')
        
    elif truncated:
        print('Épisode terminé')

Episode n˚1 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : 103.37%   |   Portfolio Valuation : 2033.72   |
Épisode terminé
Episode n˚2 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 376.91%   |   Portfolio Return : 372.85%   |   Portfolio Valuation : 4728.5   |
Épisode terminé
Episode n˚3 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : 26.58%   |   Portfolio Valuation : 1265.76   |
Épisode terminé
Episode n˚4 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : 43.32%   |   Portfolio Valuation : 1433.23   |
Épisode terminé
Episode n˚5 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 946.44%   |   Portfolio Return : 941.00%   |   Portfolio Valuation : 10410.0   |
Épisode terminé
Episode n˚6 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : 39.41%   |   Portfolio Valuation : 1394.11   |
Épisode terminé
Episode n˚7 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return :  9.40%   |   Portfolio Valuation : 1093.99   |
Épisode terminé
Episode n˚8 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : 696.40%   |   Portfolio Valuation : 7963.97   |
Épisode terminé
Episode n˚9 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return :  5.84%   |   Portfolio Valuation : 1058.39   |
Épisode terminé
Episode n˚10 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return :  9.31%   |   Portfolio Valuation : 1093.14   |
Épisode terminé
Episode n˚11 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : 103.18%   |   Portfolio Valuation : 2031.79   |
Épisode terminé
Episode n˚12 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : 692.83%   |   Portfolio Valuation : 7928.26   |
Épisode terminé
Episode n˚13 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : 26.57%   |   Portfolio Valuation : 1265.71   |
Épisode terminé
Episode n˚14 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return :  5.87%   |   Portfolio Valuation : 1058.66   |
Épisode terminé
Episode n˚15 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : 39.77%   |   Portfolio Valuation : 1397.68   |
Épisode terminé
Episode n˚16 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 946.44%   |   Portfolio Return : 937.65%   |   Portfolio Valuation : 10376.52   |
Épisode terminé
Episode n˚17 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : 43.30%   |   Portfolio Valuation : 1432.97   |
Épisode terminé
Episode n˚18 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 376.91%   |   Portfolio Return : 379.44%   |   Portfolio Valuation : 4794.36   |
Épisode terminé
Episode n˚19 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return :  9.36%   |   Portfolio Valuation : 1093.6   |
Épisode terminé
Episode n˚20 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 376.91%   |   Portfolio Return : 375.94%   |   Portfolio Valuation : 4759.39   |
Épisode terminé
Episode n˚21 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return :  5.61%   |   Portfolio Valuation : 1056.07   |
Épisode terminé
Episode n˚22 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : 39.67%   |   Portfolio Valuation : 1396.74   |
Épisode terminé
Episode n˚23 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : 43.28%   |   Portfolio Valuation : 1432.78   |
Épisode terminé
Episode n˚24 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 946.44%   |   Portfolio Return : 941.86%   |   Portfolio Valuation : 10418.59   |
Épisode terminé
Episode n˚25 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : 103.41%   |   Portfolio Valuation : 2034.09   |
Épisode terminé
Episode n˚26 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : 698.96%   |   Portfolio Valuation : 7989.62   |
Épisode terminé
Episode n˚27 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : 26.52%   |   Portfolio Valuation : 1265.25   |
Épisode terminé
Episode n˚28 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : 42.66%   |   Portfolio Valuation : 1426.55   |
Épisode terminé
Episode n˚29 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return :  9.33%   |   Portfolio Valuation : 1093.27   |
Épisode terminé
Episode n˚30 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : 703.07%   |   Portfolio Valuation : 8030.73   |
Épisode terminé

In [18]:
def preprocess_corrected(df):
    df = df.copy()
    
    df['feature_log_ret'] = np.log(df['close'] / df['close'].shift(1))

    df['feature_rsi'] = ta.rsi(df['close'], length=14) / 100.0 
    
    macd = ta.macd(df['close'])
    df['feature_macd_norm'] = macd['MACD_12_26_9'] / df['close']
    
    df['feature_atr_norm'] = ta.atr(df['high'], df['low'], df['close'], length=14) / df['close']
    
    df['feature_hour_sin'] = np.sin(2 * np.pi * df.index.hour / 24)
    df['feature_hour_cos'] = np.cos(2 * np.pi * df.index.hour / 24)

    df = df.dropna()
    
    df = df.replace([np.inf, -np.inf], 0)

    return df


def metric_portfolio_valuation(history):
    return round(history['portfolio_valuation', -1], 2)

def reward_function(history):
    return history['step']*(history['portfolio_valuation', -1] - history['portfolio_valuation', -2])

def reward_function_rapport_market(history):
    return 10*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1]))

def reward_function_rapport_market_v2(history):
    weight = 0 
    if (history['position',1] == history['position',-2]):
        weight = 0.1
    return 10*(history['data_open', -2] / history['data_close', -1])*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1])) - weight 

def reward_log_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = np.log(curr_val / prev_val)
    return reward

def reward_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = (curr_val - prev_val) / prev_val
    return reward

env = gym.make(
    "MultiDatasetTradingEnv",
    dataset_dir="data/*.pkl",
    preprocess=preprocess_corrected,
    reward_function=reward_returns,
    # Valeur initiale du portefeuille
    portfolio_initial_value=1_000,
    # Frais de transactions
    trading_fees=0.1/100,
    # Intérêts sur les prêts
    borrow_interest_rate=0.02/100/24,
)

env.add_metric('Portfolio Valuation', metric_portfolio_valuation)
env = DiscreteActionsWrapper(env, positions=[-0.5,0,0.5,1,1.5])
obs, _ = env.reset()

model = PPO("MlpPolicy",env)

model = model.learn(total_timesteps=1_500_000)
model.save("PPO_v7")

Market Return : 376.91%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.0   |
Market Return : 946.44%   |   Portfolio Return : -99.95%   |   Portfolio Valuation : 0.52   |
Market Return : 39.77%   |   Portfolio Return : 19.34%   |   Portfolio Valuation : 1193.36   |
Market Return :  9.40%   |   Portfolio Return : -17.61%   |   Portfolio Valuation : 823.88   |
Market Return : 43.37%   |   Portfolio Return : 29.01%   |   Portfolio Valuation : 1290.1   |
Market Return : 699.62%   |   Portfolio Return : 295.53%   |   Portfolio Valuation : 3955.27   |
Market Return : 103.53%   |   Portfolio Return : 146.59%   |   Portfolio Valuation : 2465.92   |
Market Return : 946.44%   |   Portfolio Return : 570.10%   |   Portfolio Valuation : 6700.96   |
Market Return :  9.40%   |   Portfolio Return : 11.35%   |   Portfolio Valuation : 1113.49   |
Market Return :  5.93%   |   Portfolio Return :  5.45%   |   Portfolio Valuation : 1054.51   |
Market Return : 699.62%   |   Portfolio Return : -59.72%   |   Portfolio Valuation : 402.84   |
Market Return : 103.53%   |   Portfolio Return : 117.34%   |   Portfolio Valuation : 2173.39   |
Market Return : 43.37%   |   Portfolio Return : 67.54%   |   Portfolio Valuation : 1675.38   |
Market Return : 26.58%   |   Portfolio Return : 27.32%   |   Portfolio Valuation : 1273.22   |
Market Return : 376.91%   |   Portfolio Return : -27.38%   |   Portfolio Valuation : 726.2   |
Market Return : 39.77%   |   Portfolio Return : 55.66%   |   Portfolio Valuation : 1556.61   |
Market Return : 699.62%   |   Portfolio Return : 137.80%   |   Portfolio Valuation : 2378.03   |
Market Return : 26.58%   |   Portfolio Return : 32.37%   |   Portfolio Valuation : 1323.69   |
Market Return : 43.37%   |   Portfolio Return : 66.88%   |   Portfolio Valuation : 1668.77   |
Market Return : 39.77%   |   Portfolio Return : 59.10%   |   Portfolio Valuation : 1591.01   |
Market Return : 103.53%   |   Portfolio Return : 158.52%   |   Portfolio Valuation : 2585.25   |
Market Return : 376.91%   |   Portfolio Return : -38.33%   |   Portfolio Valuation : 616.73   |
Market Return :  9.40%   |   Portfolio Return :  5.29%   |   Portfolio Valuation : 1052.88   |
Market Return :  5.93%   |   Portfolio Return : -3.66%   |   Portfolio Valuation : 963.4   |
Market Return : 148.67%   |   Portfolio Return : -127.89%   |   Portfolio Valuation : -278.87   |
Market Return : 43.37%   |   Portfolio Return : 67.30%   |   Portfolio Valuation : 1673.03   |
Market Return : 699.62%   |   Portfolio Return : 489.66%   |   Portfolio Valuation : 5896.61   |
Market Return : 351.97%   |   Portfolio Return : -105.06%   |   Portfolio Valuation : -50.61   |
Market Return :  5.93%   |   Portfolio Return : -15.63%   |   Portfolio Valuation : 843.66   |
Market Return : 26.58%   |   Portfolio Return : 36.23%   |   Portfolio Valuation : 1362.26   |
Market Return : 946.44%   |   Portfolio Return : 417.06%   |   Portfolio Valuation : 5170.62   |
Market Return :  9.40%   |   Portfolio Return : 14.05%   |   Portfolio Valuation : 1140.47   |
Market Return : 103.53%   |   Portfolio Return : 133.40%   |   Portfolio Valuation : 2334.03   |
Market Return : 39.77%   |   Portfolio Return : 59.56%   |   Portfolio Valuation : 1595.58   |
Market Return :  9.40%   |   Portfolio Return :  9.31%   |   Portfolio Valuation : 1093.1   |
Market Return : 514.89%   |   Portfolio Return : -143.45%   |   Portfolio Valuation : -434.5   |
Market Return : 26.58%   |   Portfolio Return : 40.47%   |   Portfolio Valuation : 1404.74   |
Market Return : 43.37%   |   Portfolio Return : 64.95%   |   Portfolio Valuation : 1649.5   |
Market Return : 37.30%   |   Portfolio Return : -104.35%   |   Portfolio Valuation : -43.45   |
Market Return :  5.93%   |   Portfolio Return :  7.36%   |   Portfolio Valuation : 1073.6   |
Market Return : 166.38%   |   Portfolio Return : -130.15%   |   Portfolio Valuation : -301.47   |
Market Return : 103.53%   |   Portfolio Return : 180.75%   |   Portfolio Valuation : 2807.47   |
Market Return : 39.77%   |   Portfolio Return : 59.46%   |   Portfolio Valuation : 1594.61   |
Market Return : 132.65%   |   Portfolio Return : -111.32%   |   Portfolio Valuation : -113.18   |
Market Return : 39.77%   |   Portfolio Return : 59.49%   |   Portfolio Valuation : 1594.95   |
Market Return : 26.58%   |   Portfolio Return : 35.48%   |   Portfolio Valuation : 1354.77   |
Market Return :  5.93%   |   Portfolio Return : -5.32%   |   Portfolio Valuation : 946.81   |
Market Return : 699.62%   |   Portfolio Return : 338.10%   |   Portfolio Valuation : 4380.98   |
Market Return : 376.91%   |   Portfolio Return : -18.84%   |   Portfolio Valuation : 811.56   |
Market Return :  9.40%   |   Portfolio Return :  4.97%   |   Portfolio Valuation : 1049.69   |
Market Return : 103.53%   |   Portfolio Return : 149.04%   |   Portfolio Valuation : 2490.43   |
Market Return : 43.37%   |   Portfolio Return : 67.09%   |   Portfolio Valuation : 1670.94   |
Market Return : 39.77%   |   Portfolio Return : 58.55%   |   Portfolio Valuation : 1585.48   |
Market Return : 103.53%   |   Portfolio Return : 91.66%   |   Portfolio Valuation : 1916.62   |
Market Return :  5.93%   |   Portfolio Return : -18.58%   |   Portfolio Valuation : 814.19   |
Market Return : 946.44%   |   Portfolio Return : 874.78%   |   Portfolio Valuation : 9747.75   |
Market Return : 43.37%   |   Portfolio Return : 65.66%   |   Portfolio Valuation : 1656.59   |
Market Return : 89.86%   |   Portfolio Return : -106.07%   |   Portfolio Valuation : -60.68   |
Market Return : 514.89%   |   Portfolio Return : -199.92%   |   Portfolio Valuation : -999.22   |
Market Return :  9.40%   |   Portfolio Return : 12.29%   |   Portfolio Valuation : 1122.89   |
Market Return : 26.58%   |   Portfolio Return : 38.07%   |   Portfolio Valuation : 1380.67   |
Market Return : 514.89%   |   Portfolio Return : -143.95%   |   Portfolio Valuation : -439.45   |
Market Return : 39.77%   |   Portfolio Return : 61.11%   |   Portfolio Valuation : 1611.06   |
Market Return : 89.86%   |   Portfolio Return : -111.53%   |   Portfolio Valuation : -115.31   |
Market Return : 946.44%   |   Portfolio Return : 2069.63%   |   Portfolio Valuation : 21696.31   |
Market Return : 26.58%   |   Portfolio Return : 10.93%   |   Portfolio Valuation : 1109.29   |
Market Return :  5.93%   |   Portfolio Return : -12.29%   |   Portfolio Valuation : 877.14   |
Market Return : 43.37%   |   Portfolio Return : 62.28%   |   Portfolio Valuation : 1622.75   |
Market Return : 103.53%   |   Portfolio Return : 164.10%   |   Portfolio Valuation : 2641.0   |
Market Return :  9.40%   |   Portfolio Return :  9.67%   |   Portfolio Valuation : 1096.68   |
Market Return :  9.40%   |   Portfolio Return :  7.86%   |   Portfolio Valuation : 1078.58   |
Market Return : 458.60%   |   Portfolio Return : -219.52%   |   Portfolio Valuation : -1195.16   |
Market Return : 43.37%   |   Portfolio Return : 67.40%   |   Portfolio Valuation : 1674.0   |
Market Return :  5.93%   |   Portfolio Return :  6.49%   |   Portfolio Valuation : 1064.89   |
Market Return : 89.86%   |   Portfolio Return : -111.81%   |   Portfolio Valuation : -118.09   |
Market Return : 235.14%   |   Portfolio Return : -114.99%   |   Portfolio Valuation : -149.95   |
Market Return : 26.58%   |   Portfolio Return : 39.91%   |   Portfolio Valuation : 1399.15   |
Market Return : 103.53%   |   Portfolio Return : 161.60%   |   Portfolio Valuation : 2615.97   |
Market Return : 39.77%   |   Portfolio Return : 59.66%   |   Portfolio Valuation : 1596.64   |
Market Return : 68.99%   |   Portfolio Return : -104.58%   |   Portfolio Valuation : -45.75   |
Market Return : 43.37%   |   Portfolio Return : 67.92%   |   Portfolio Valuation : 1679.17   |
Market Return : 39.77%   |   Portfolio Return : 58.25%   |   Portfolio Valuation : 1582.46   |
Market Return : 26.58%   |   Portfolio Return : 38.67%   |   Portfolio Valuation : 1386.75   |
Market Return : 699.62%   |   Portfolio Return : 1240.57%   |   Portfolio Valuation : 13405.66   |
Market Return :  5.93%   |   Portfolio Return : -1.17%   |   Portfolio Valuation : 988.31   |
Market Return :  9.40%   |   Portfolio Return :  4.90%   |   Portfolio Valuation : 1048.97   |
Market Return : 280.43%   |   Portfolio Return : -120.87%   |   Portfolio Valuation : -208.72   |
Market Return : 103.53%   |   Portfolio Return : 137.69%   |   Portfolio Valuation : 2376.92   |
Market Return :  5.93%   |   Portfolio Return : -7.24%   |   Portfolio Valuation : 927.63   |
Market Return : 166.38%   |   Portfolio Return : -137.46%   |   Portfolio Valuation : -374.6   |
Market Return : 237.29%   |   Portfolio Return : -103.20%   |   Portfolio Valuation : -32.04   |
Market Return : 26.58%   |   Portfolio Return : 31.17%   |   Portfolio Valuation : 1311.67   |
Market Return : 43.37%   |   Portfolio Return :  9.76%   |   Portfolio Valuation : 1097.61   |
Market Return : 103.53%   |   Portfolio Return : 68.52%   |   Portfolio Valuation : 1685.23   |
Market Return :  9.40%   |   Portfolio Return : -7.22%   |   Portfolio Valuation : 927.78   |
Market Return : 699.62%   |   Portfolio Return : 594.55%   |   Portfolio Valuation : 6945.53   |
Market Return : 39.77%   |   Portfolio Return : 56.79%   |   Portfolio Valuation : 1567.91   |
Market Return : 43.37%   |   Portfolio Return : 65.97%   |   Portfolio Valuation : 1659.68   |
Market Return : 103.53%   |   Portfolio Return : 164.98%   |   Portfolio Valuation : 2649.77   |
Market Return : 699.62%   |   Portfolio Return : 74.93%   |   Portfolio Valuation : 1749.28   |
Market Return :  9.40%   |   Portfolio Return : -24.49%   |   Portfolio Valuation : 755.09   |
Market Return : 26.58%   |   Portfolio Return : -5.04%   |   Portfolio Valuation : 949.61   |
Market Return : 39.77%   |   Portfolio Return : 14.58%   |   Portfolio Valuation : 1145.83   |
Market Return : 316.39%   |   Portfolio Return : -113.87%   |   Portfolio Valuation : -138.72   |
Market Return : 132.65%   |   Portfolio Return : -114.30%   |   Portfolio Valuation : -143.0   |

In [19]:
nb_episodes = 30

for episode in range(1, nb_episodes + 1):
    obs, _ = env.reset()
    print(f'Episode n˚{episode} -- Jeu de donnée {env.env.name}')
    done = False

    while not done:
        action, _states = model.predict(obs)
        obs, reward, terminated, truncated, _ = env.step(action.tolist())
        done = terminated or truncated
    env.env.save_for_render(dir="logs")        
    if terminated:
        print('Argent perdu')
        
    elif truncated:
        print('Épisode terminé')

Episode n˚1 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : 36.71%   |   Portfolio Valuation : 1367.08   |
Épisode terminé
Episode n˚2 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : 52.48%   |   Portfolio Valuation : 1524.82   |
Épisode terminé
Episode n˚3 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 579.70%   |   Portfolio Return : -149.94%   |   Portfolio Valuation : -499.44   |
Argent perdu
Episode n˚4 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return :  0.03%   |   Portfolio Valuation : 1000.27   |
Épisode terminé
Episode n˚5 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : 141.53%   |   Portfolio Valuation : 2415.34   |
Épisode terminé
Episode n˚6 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -7.02%   |   Portfolio Valuation : 929.79   |
Épisode terminé
Episode n˚7 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 37.30%   |   Portfolio Return : -103.37%   |   Portfolio Valuation : -33.66   |
Argent perdu
Episode n˚8 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 275.57%   |   Portfolio Return : -112.77%   |   Portfolio Valuation : -127.66   |
Argent perdu
Episode n˚9 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return :  9.54%   |   Portfolio Valuation : 1095.38   |
Épisode terminé
Episode n˚10 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 97.19%   |   Portfolio Return : -102.25%   |   Portfolio Valuation : -22.46   |
Argent perdu
Episode n˚11 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -5.14%   |   Portfolio Valuation : 948.64   |
Épisode terminé
Episode n˚12 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 514.89%   |   Portfolio Return : -268.22%   |   Portfolio Valuation : -1682.18   |
Argent perdu
Episode n˚13 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -3.05%   |   Portfolio Valuation : 969.48   |
Épisode terminé
Episode n˚14 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : 40.43%   |   Portfolio Valuation : 1404.28   |
Épisode terminé
Episode n˚15 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 166.38%   |   Portfolio Return : -127.18%   |   Portfolio Valuation : -271.8   |
Argent perdu
Episode n˚16 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : 128.71%   |   Portfolio Valuation : 2287.08   |
Épisode terminé
Episode n˚17 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : 50.96%   |   Portfolio Valuation : 1509.61   |
Épisode terminé
Episode n˚18 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return :  2.75%   |   Portfolio Valuation : 1027.49   |
Épisode terminé
Episode n˚19 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -9.62%   |   Portfolio Valuation : 903.83   |
Épisode terminé
Episode n˚20 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -1.33%   |   Portfolio Valuation : 986.73   |
Épisode terminé
Episode n˚21 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : 48.06%   |   Portfolio Valuation : 1480.62   |
Épisode terminé
Episode n˚22 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 235.14%   |   Portfolio Return : -132.46%   |   Portfolio Valuation : -324.59   |
Argent perdu
Episode n˚23 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 97.19%   |   Portfolio Return : -101.80%   |   Portfolio Valuation : -17.98   |
Argent perdu
Episode n˚24 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : 148.01%   |   Portfolio Valuation : 2480.14   |
Épisode terminé
Episode n˚25 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : 17.59%   |   Portfolio Valuation : 1175.95   |
Épisode terminé
Episode n˚26 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : 51.25%   |   Portfolio Valuation : 1512.55   |
Épisode terminé
Episode n˚27 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 504.01%   |   Portfolio Return : -124.02%   |   Portfolio Valuation : -240.2   |
Argent perdu
Episode n˚28 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : -1.79%   |   Portfolio Valuation : 982.08   |
Épisode terminé
Episode n˚29 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 275.57%   |   Portfolio Return : -105.31%   |   Portfolio Valuation : -53.11   |
Argent perdu
Episode n˚30 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -0.55%   |   Portfolio Valuation : 994.46   |
Épisode terminé

In [21]:
from typing import Callable

def linear_schedule(initial_value: float) -> Callable[[float], float]:
    def func(progress_remaining: float) -> float:
        return progress_remaining * initial_value
    return func

def preprocess_corrected(df):
    df = df.copy()
    
    df['feature_log_ret'] = np.log(df['close'] / df['close'].shift(1))

    df['feature_rsi'] = ta.rsi(df['close'], length=14) / 100.0 
    
    macd = ta.macd(df['close'])
    df['feature_macd_norm'] = macd['MACD_12_26_9'] / df['close']
    
    df['feature_atr_norm'] = ta.atr(df['high'], df['low'], df['close'], length=14) / df['close']
    
    df['feature_hour_sin'] = np.sin(2 * np.pi * df.index.hour / 24)
    df['feature_hour_cos'] = np.cos(2 * np.pi * df.index.hour / 24)

    df = df.dropna()
    
    df = df.replace([np.inf, -np.inf], 0)

    return df


def metric_portfolio_valuation(history):
    return round(history['portfolio_valuation', -1], 2)

def reward_function(history):
    return history['step']*(history['portfolio_valuation', -1] - history['portfolio_valuation', -2])

def reward_function_rapport_market(history):
    return 10*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1]))

def reward_function_rapport_market_v2(history):
    weight = 0 
    if (history['position',1] == history['position',-2]):
        weight = 0.1
    return 10*(history['data_open', -2] / history['data_close', -1])*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1])) - weight 

def reward_log_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = np.log(curr_val / prev_val)
    return reward

def reward_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = (curr_val - prev_val) / prev_val
    return reward

env = gym.make(
    "MultiDatasetTradingEnv",
    dataset_dir="data/*.pkl",
    preprocess=preprocess_corrected,
    reward_function=reward_returns,
    # Valeur initiale du portefeuille
    portfolio_initial_value=1_000,
    # Frais de transactions
    trading_fees=0.1/100,
    # Intérêts sur les prêts
    borrow_interest_rate=0.02/100/24,
)

env.add_metric('Portfolio Valuation', metric_portfolio_valuation)
env = DiscreteActionsWrapper(env, positions=[-0.5,0,0.5,1,1.5])
obs, _ = env.reset()

model = PPO("MlpPolicy",
            env,
            gamma=0.995, 
            gae_lambda=0.95,
            learning_rate=linear_schedule(0.0003), 
            ent_coef=0.01, 
            batch_size=64,
            n_steps=2048,
            verbose=1
)

model = model.learn(total_timesteps=1_500_000)
model.save("PPO_v8")

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
-----------------------------
| time/              |      |
|    fps             | 337  |
|    iterations      | 1    |
|    time_elapsed    | 6    |
|    total_timesteps | 2048 |
-----------------------------
Market Return : 39.77%   |   Portfolio Return : -91.27%   |   Portfolio Valuation : 87.33   |
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 3.47e+03    |
|    ep_rew_mean          | -2.37       |
| time/                   |             |
|    fps                  | 264         |
|    iterations           | 2           |
|    time_elapsed         | 15          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.011947415 |
|    clip_fraction        | 0.0858      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.6        |
|    explained_variance   | -10.5       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0303     |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.00677    |
|    value_loss           | 0.00462     |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 3.47e+03    |
|    ep_rew_mean          | -2.37       |
| time/                   |             |
|    fps                  | 227         |
|    iterations           | 3           |
|    time_elapsed         | 26          |
|    total_timesteps      | 6144        |
| train/                  |             |
|    approx_kl            | 0.009895023 |
|    clip_fraction        | 0.0669      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.58       |
|    explained_variance   | -0.329      |
|    learning_rate        | 0.000299    |
|    loss                 | -0.0352     |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.00728    |
|    value_loss           | 0.00103     |
-----------------------------------------
Market Return :  9.40%   |   Portfolio Return : -96.42%   |   Portfolio Valuation : 35.76   |
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 4.02e+03    |
|    ep_rew_mean          | -2.84       |
| time/                   |             |
|    fps                  | 205         |
|    iterations           | 4           |
|    time_elapsed         | 39          |
|    total_timesteps      | 8192        |
| train/                  |             |
|    approx_kl            | 0.011392297 |
|    clip_fraction        | 0.0858      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.6        |
|    explained_variance   | -5.72       |
|    learning_rate        | 0.000299    |
|    loss                 | -0.034      |
|    n_updates            | 30          |
|    policy_gradient_loss | -0.00631    |
|    value_loss           | 0.00017     |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 4.02e+03     |
|    ep_rew_mean          | -2.84        |
| time/                   |              |
|    fps                  | 210          |
|    iterations           | 5            |
|    time_elapsed         | 48           |
|    total_timesteps      | 10240        |
| train/                  |              |
|    approx_kl            | 0.0080245575 |
|    clip_fraction        | 0.096        |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.58        |
|    explained_variance   | -0.697       |
|    learning_rate        | 0.000298     |
|    loss                 | -0.0213      |
|    n_updates            | 40           |
|    policy_gradient_loss | -0.0111      |
|    value_loss           | 0.000154     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 4.02e+03    |
|    ep_rew_mean          | -2.84       |
| time/                   |             |
|    fps                  | 220         |
|    iterations           | 6           |
|    time_elapsed         | 55          |
|    total_timesteps      | 12288       |
| train/                  |             |
|    approx_kl            | 0.009861221 |
|    clip_fraction        | 0.0827      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.57       |
|    explained_variance   | -11.7       |
|    learning_rate        | 0.000298    |
|    loss                 | -0.0377     |
|    n_updates            | 50          |
|    policy_gradient_loss | -0.00977    |
|    value_loss           | 4.12e-05    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 4.02e+03    |
|    ep_rew_mean          | -2.84       |
| time/                   |             |
|    fps                  | 225         |
|    iterations           | 7           |
|    time_elapsed         | 63          |
|    total_timesteps      | 14336       |
| train/                  |             |
|    approx_kl            | 0.011613194 |
|    clip_fraction        | 0.139       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.52       |
|    explained_variance   | -2.08       |
|    learning_rate        | 0.000298    |
|    loss                 | -0.0233     |
|    n_updates            | 60          |
|    policy_gradient_loss | -0.0137     |
|    value_loss           | 2.2e-05     |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 4.02e+03    |
|    ep_rew_mean          | -2.84       |
| time/                   |             |
|    fps                  | 237         |
|    iterations           | 8           |
|    time_elapsed         | 68          |
|    total_timesteps      | 16384       |
| train/                  |             |
|    approx_kl            | 0.010372162 |
|    clip_fraction        | 0.122       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.48       |
|    explained_variance   | -1.24       |
|    learning_rate        | 0.000297    |
|    loss                 | -0.024      |
|    n_updates            | 70          |
|    policy_gradient_loss | -0.0141     |
|    value_loss           | 1.86e-05    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 4.02e+03    |
|    ep_rew_mean          | -2.84       |
| time/                   |             |
|    fps                  | 245         |
|    iterations           | 9           |
|    time_elapsed         | 75          |
|    total_timesteps      | 18432       |
| train/                  |             |
|    approx_kl            | 0.010567566 |
|    clip_fraction        | 0.125       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.43       |
|    explained_variance   | -0.532      |
|    learning_rate        | 0.000297    |
|    loss                 | -0.0356     |
|    n_updates            | 80          |
|    policy_gradient_loss | -0.0141     |
|    value_loss           | 1.98e-05    |
-----------------------------------------
Market Return :  5.93%   |   Portfolio Return : -99.91%   |   Portfolio Valuation : 0.91   |
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 6.8e+03    |
|    ep_rew_mean          | -4.23      |
| time/                   |            |
|    fps                  | 254        |
|    iterations           | 10         |
|    time_elapsed         | 80         |
|    total_timesteps      | 20480      |
| train/                  |            |
|    approx_kl            | 0.00945399 |
|    clip_fraction        | 0.103      |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.37      |
|    explained_variance   | -0.547     |
|    learning_rate        | 0.000296   |
|    loss                 | -0.0331    |
|    n_updates            | 90         |
|    policy_gradient_loss | -0.0107    |
|    value_loss           | 2.13e-05   |
----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 6.8e+03     |
|    ep_rew_mean          | -4.23       |
| time/                   |             |
|    fps                  | 251         |
|    iterations           | 11          |
|    time_elapsed         | 89          |
|    total_timesteps      | 22528       |
| train/                  |             |
|    approx_kl            | 0.008814376 |
|    clip_fraction        | 0.0992      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.32       |
|    explained_variance   | -0.345      |
|    learning_rate        | 0.000296    |
|    loss                 | 0.00265     |
|    n_updates            | 100         |
|    policy_gradient_loss | -0.00804    |
|    value_loss           | 1.82e-05    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 6.8e+03     |
|    ep_rew_mean          | -4.23       |
| time/                   |             |
|    fps                  | 254         |
|    iterations           | 12          |
|    time_elapsed         | 96          |
|    total_timesteps      | 24576       |
| train/                  |             |
|    approx_kl            | 0.008967902 |
|    clip_fraction        | 0.0639      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.28       |
|    explained_variance   | -0.0207     |
|    learning_rate        | 0.000295    |
|    loss                 | -0.0445     |
|    n_updates            | 110         |
|    policy_gradient_loss | -0.00677    |
|    value_loss           | 0.000556    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 6.8e+03     |
|    ep_rew_mean          | -4.23       |
| time/                   |             |
|    fps                  | 261         |
|    iterations           | 13          |
|    time_elapsed         | 101         |
|    total_timesteps      | 26624       |
| train/                  |             |
|    approx_kl            | 0.008177467 |
|    clip_fraction        | 0.0717      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.24       |
|    explained_variance   | -0.0317     |
|    learning_rate        | 0.000295    |
|    loss                 | -0.0117     |
|    n_updates            | 120         |
|    policy_gradient_loss | -0.00655    |
|    value_loss           | 0.00168     |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 6.8e+03     |
|    ep_rew_mean          | -4.23       |
| time/                   |             |
|    fps                  | 264         |
|    iterations           | 14          |
|    time_elapsed         | 108         |
|    total_timesteps      | 28672       |
| train/                  |             |
|    approx_kl            | 0.007882143 |
|    clip_fraction        | 0.0775      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.19       |
|    explained_variance   | -0.0397     |
|    learning_rate        | 0.000295    |
|    loss                 | -0.00316    |
|    n_updates            | 130         |
|    policy_gradient_loss | -0.00642    |
|    value_loss           | 0.000946    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 6.8e+03     |
|    ep_rew_mean          | -4.23       |
| time/                   |             |
|    fps                  | 263         |
|    iterations           | 15          |
|    time_elapsed         | 116         |
|    total_timesteps      | 30720       |
| train/                  |             |
|    approx_kl            | 0.007886922 |
|    clip_fraction        | 0.0703      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.17       |
|    explained_variance   | -0.0303     |
|    learning_rate        | 0.000294    |
|    loss                 | -0.0147     |
|    n_updates            | 140         |
|    policy_gradient_loss | -0.00936    |
|    value_loss           | 0.00193     |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 6.8e+03     |
|    ep_rew_mean          | -4.23       |
| time/                   |             |
|    fps                  | 265         |
|    iterations           | 16          |
|    time_elapsed         | 123         |
|    total_timesteps      | 32768       |
| train/                  |             |
|    approx_kl            | 0.007946434 |
|    clip_fraction        | 0.095       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.15       |
|    explained_variance   | -0.165      |
|    learning_rate        | 0.000294    |
|    loss                 | -0.000231   |
|    n_updates            | 150         |
|    policy_gradient_loss | -0.00807    |
|    value_loss           | 0.000746    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 6.8e+03     |
|    ep_rew_mean          | -4.23       |
| time/                   |             |
|    fps                  | 269         |
|    iterations           | 17          |
|    time_elapsed         | 129         |
|    total_timesteps      | 34816       |
| train/                  |             |
|    approx_kl            | 0.007802247 |
|    clip_fraction        | 0.0501      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.08       |
|    explained_variance   | -0.0259     |
|    learning_rate        | 0.000293    |
|    loss                 | -0.0458     |
|    n_updates            | 160         |
|    policy_gradient_loss | -0.00594    |
|    value_loss           | 0.000496    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 6.8e+03      |
|    ep_rew_mean          | -4.23        |
| time/                   |              |
|    fps                  | 252          |
|    iterations           | 18           |
|    time_elapsed         | 145          |
|    total_timesteps      | 36864        |
| train/                  |              |
|    approx_kl            | 0.0058904868 |
|    clip_fraction        | 0.0416       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.05        |
|    explained_variance   | 0.013        |
|    learning_rate        | 0.000293     |
|    loss                 | -0.0357      |
|    n_updates            | 170          |
|    policy_gradient_loss | -0.00464     |
|    value_loss           | 0.00068      |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 6.8e+03      |
|    ep_rew_mean          | -4.23        |
| time/                   |              |
|    fps                  | 153          |
|    iterations           | 19           |
|    time_elapsed         | 253          |
|    total_timesteps      | 38912        |
| train/                  |              |
|    approx_kl            | 0.0079276245 |
|    clip_fraction        | 0.0638       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.05        |
|    explained_variance   | -0.00432     |
|    learning_rate        | 0.000293     |
|    loss                 | 0.00613      |
|    n_updates            | 180          |
|    policy_gradient_loss | -0.00478     |
|    value_loss           | 0.00116      |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 6.8e+03      |
|    ep_rew_mean          | -4.23        |
| time/                   |              |
|    fps                  | 141          |
|    iterations           | 20           |
|    time_elapsed         | 290          |
|    total_timesteps      | 40960        |
| train/                  |              |
|    approx_kl            | 0.0058267703 |
|    clip_fraction        | 0.0743       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.05        |
|    explained_variance   | -0.133       |
|    learning_rate        | 0.000292     |
|    loss                 | -0.00513     |
|    n_updates            | 190          |
|    policy_gradient_loss | -0.00691     |
|    value_loss           | 0.000662     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 6.8e+03     |
|    ep_rew_mean          | -4.23       |
| time/                   |             |
|    fps                  | 100         |
|    iterations           | 21          |
|    time_elapsed         | 429         |
|    total_timesteps      | 43008       |
| train/                  |             |
|    approx_kl            | 0.005018559 |
|    clip_fraction        | 0.037       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.976      |
|    explained_variance   | -0.00726    |
|    learning_rate        | 0.000292    |
|    loss                 | -0.0166     |
|    n_updates            | 200         |
|    policy_gradient_loss | -0.00379    |
|    value_loss           | 0.00039     |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 6.8e+03      |
|    ep_rew_mean          | -4.23        |
| time/                   |              |
|    fps                  | 99           |
|    iterations           | 22           |
|    time_elapsed         | 454          |
|    total_timesteps      | 45056        |
| train/                  |              |
|    approx_kl            | 0.0041478775 |
|    clip_fraction        | 0.0437       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.957       |
|    explained_variance   | -0.023       |
|    learning_rate        | 0.000291     |
|    loss                 | -0.0201      |
|    n_updates            | 210          |
|    policy_gradient_loss | -0.00382     |
|    value_loss           | 0.000493     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 6.8e+03      |
|    ep_rew_mean          | -4.23        |
| time/                   |              |
|    fps                  | 100          |
|    iterations           | 23           |
|    time_elapsed         | 469          |
|    total_timesteps      | 47104        |
| train/                  |              |
|    approx_kl            | 0.0052120998 |
|    clip_fraction        | 0.0539       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.953       |
|    explained_variance   | -0.065       |
|    learning_rate        | 0.000291     |
|    loss                 | -0.0141      |
|    n_updates            | 220          |

In [22]:
nb_episodes = 30

for episode in range(1, nb_episodes + 1):
    obs, _ = env.reset()
    print(f'Episode n˚{episode} -- Jeu de donnée {env.env.name}')
    done = False

    while not done:
        action, _states = model.predict(obs)
        obs, reward, terminated, truncated, _ = env.step(action.tolist())
        done = terminated or truncated
    env.env.save_for_render(dir="logs")        
    if terminated:
        print('Argent perdu')
        
    elif truncated:
        print('Épisode terminé')

Episode n˚1 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -7.70%   |   Portfolio Valuation : 923.0   |
Épisode terminé
Episode n˚2 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : 32.53%   |   Portfolio Valuation : 1325.33   |
Épisode terminé
Episode n˚3 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : 52.49%   |   Portfolio Valuation : 1524.91   |
Épisode terminé
Episode n˚4 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 946.44%   |   Portfolio Return : 355.77%   |   Portfolio Valuation : 4557.68   |
Épisode terminé
Episode n˚5 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 316.39%   |   Portfolio Return : -111.67%   |   Portfolio Valuation : -116.68   |
Argent perdu
Episode n˚6 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : 518.35%   |   Portfolio Valuation : 6183.51   |
Épisode terminé
Episode n˚7 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return :  8.28%   |   Portfolio Valuation : 1082.8   |
Épisode terminé
Episode n˚8 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -6.67%   |   Portfolio Valuation : 933.35   |
Épisode terminé
Episode n˚9 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : 27.08%   |   Portfolio Valuation : 1270.81   |
Épisode terminé
Episode n˚10 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : 38.68%   |   Portfolio Valuation : 1386.78   |
Épisode terminé
Episode n˚11 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : 110.82%   |   Portfolio Valuation : 2108.23   |
Épisode terminé
Episode n˚12 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 946.44%   |   Portfolio Return : 368.88%   |   Portfolio Valuation : 4688.85   |
Épisode terminé
Episode n˚13 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : 423.54%   |   Portfolio Valuation : 5235.45   |
Épisode terminé
Episode n˚14 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : 10.95%   |   Portfolio Valuation : 1109.49   |
Épisode terminé
Episode n˚15 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : 62.87%   |   Portfolio Valuation : 1628.72   |
Épisode terminé
Episode n˚16 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 376.91%   |   Portfolio Return : -4.14%   |   Portfolio Valuation : 958.63   |
Épisode terminé
Episode n˚17 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : 57.13%   |   Portfolio Valuation : 1571.29   |
Épisode terminé
Episode n˚18 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : 30.56%   |   Portfolio Valuation : 1305.64   |
Épisode terminé
Episode n˚19 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : 464.31%   |   Portfolio Valuation : 5643.07   |
Épisode terminé
Episode n˚20 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : 101.76%   |   Portfolio Valuation : 2017.58   |
Épisode terminé
Episode n˚21 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return :  7.11%   |   Portfolio Valuation : 1071.1   |
Épisode terminé
Episode n˚22 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 946.44%   |   Portfolio Return : 354.70%   |   Portfolio Valuation : 4547.03   |
Épisode terminé
Episode n˚23 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 316.39%   |   Portfolio Return : -111.29%   |   Portfolio Valuation : -112.85   |
Argent perdu
Episode n˚24 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -6.96%   |   Portfolio Valuation : 930.41   |
Épisode terminé
Episode n˚25 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : 55.87%   |   Portfolio Valuation : 1558.75   |
Épisode terminé
Episode n˚26 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return :  9.65%   |   Portfolio Valuation : 1096.49   |
Épisode terminé
Episode n˚27 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : 52.62%   |   Portfolio Valuation : 1526.18   |
Épisode terminé
Episode n˚28 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : 464.29%   |   Portfolio Valuation : 5642.87   |
Épisode terminé
Episode n˚29 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 376.91%   |   Portfolio Return : 16.33%   |   Portfolio Valuation : 1163.34   |
Épisode terminé
Episode n˚30 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : 86.09%   |   Portfolio Valuation : 1860.89   |
Épisode terminé

In [23]:
pip install sb3_contrib

Exception ignored in: <_io.FileIO name=3 mode='wb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    res = process_handler(cmd, _system_body)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ResourceWarning: unclosed file <_io.BufferedWriter name=3>
Exception ignored in: <_io.FileIO name=4 mode='rb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    res = process_handler(cmd, _system_body)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ResourceWarning: unclosed file <_io.BufferedReader name=4>
Exception ignored in: <_io.FileIO name=5 mode='rb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    res = process_handler(cmd, _system_body)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ResourceWarning: unclosed file <_io.BufferedReader name=5>

Collecting sb3_contrib
  Downloading sb3_contrib-2.7.1-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: stable_baselines3<3.0,>=2.7.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from sb3_contrib) (2.7.1)
Requirement already satisfied: gymnasium<1.3.0,>=0.29.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from stable_baselines3<3.0,>=2.7.0->sb3_contrib) (1.2.2)
Requirement already satisfied: numpy<3.0,>=1.20 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from stable_baselines3<3.0,>=2.7.0->sb3_contrib) (2.2.6)
Requirement already satisfied: torch<3.0,>=2.3 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from stable_baselines3<3.0,>=2.7.0->sb3_contrib) (2.9.1)
Requirement already satisfied: cloudpickle in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from stable_baselines3<3.0,>=2.7.0->sb3_contrib) (3.1.2)
Requirement already satisfied: pandas in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from stable_baselines3<3.0,>=2.7.0->sb3_contrib) (2.3.3)
Requirement already satisfied: matplotlib in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from stable_baselines3<3.0,>=2.7.0->sb3_contrib) (3.10.8)
Requirement already satisfied: typing-extensions>=4.3.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gymnasium<1.3.0,>=0.29.1->stable_baselines3<3.0,>=2.7.0->sb3_contrib) (4.15.0)
Requirement already satisfied: farama-notifications>=0.0.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gymnasium<1.3.0,>=0.29.1->stable_baselines3<3.0,>=2.7.0->sb3_contrib) (0.0.4)
Requirement already satisfied: filelock in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib) (3.20.1)
Requirement already satisfied: sympy>=1.13.3 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib) (2025.12.0)
Requirement already satisfied: setuptools in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib) (80.9.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from sympy>=1.13.3->torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from jinja2->torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib) (1.17.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas->stable_baselines3<3.0,>=2.7.0->sb3_contrib) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas->stable_baselines3<3.0,>=2.7.0->sb3_contrib) (2025.3)
Downloading sb3_contrib-2.7.1-py3-none-any.whl (93 kB)
Installing collected packages: sb3_contrib
Successfully installed sb3_contrib-2.7.1
Note: you may need to restart the kernel to use updated packages.

In [5]:
from typing import Callable
from sb3_contrib import RecurrentPPO

In [28]:
from typing import Callable
from sb3_contrib import RecurrentPPO

def linear_schedule(initial_value: float) -> Callable[[float], float]:
    def func(progress_remaining: float) -> float:
        return progress_remaining * initial_value
    return func

def preprocess_corrected(df):
    df = df.copy()
    
    df['feature_log_ret'] = np.log(df['close'] / df['close'].shift(1))

    df['feature_rsi'] = ta.rsi(df['close'], length=14) / 100.0 
    
    macd = ta.macd(df['close'])
    df['feature_macd_norm'] = macd['MACD_12_26_9'] / df['close']
    for i in range(1, 6):
        df[f'feature_log_ret_lag_{i}'] = df['feature_log_ret'].shift(i)

    df['feature_atr_norm'] = ta.atr(df['high'], df['low'], df['close'], length=14) / df['close']
    
    df['feature_hour_sin'] = np.sin(2 * np.pi * df.index.hour / 24)
    df['feature_hour_cos'] = np.cos(2 * np.pi * df.index.hour / 24)

    df = df.dropna().replace([np.inf, -np.inf], 0)
    return df


def metric_portfolio_valuation(history):
    return round(history['portfolio_valuation', -1], 2)

def reward_risk_adjusted(history):
    # Rendement actuel
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    if prev_val == 0: return 0
    
    # Rendement Logarithmique
    log_return = np.log(curr_val / prev_val)
    
    # On veut maximiser le gain, mais on soustrait une pénalité si l'agent est trop volatil
    # Astuce : On ne peut pas calculer la volatilité sur 1 step, 
    # mais on peut punir les gros mouvements négatifs plus fort.
    
    risk_penalty = 0
    if log_return < 0:
        # On punit les pertes 2x plus fort que les gains ne sont récompensés
        risk_penalty = abs(log_return) * 0.5 
        
    return log_return - risk_penalty

def reward_function(history):
    return history['step']*(history['portfolio_valuation', -1] - history['portfolio_valuation', -2])

def reward_function_rapport_market(history):
    return 10*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1]))

def reward_function_rapport_market_v2(history):
    weight = 0 
    if (history['position',1] == history['position',-2]):
        weight = 0.1
    return 10*(history['data_open', -2] / history['data_close', -1])*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1])) - weight 

def reward_log_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = np.log(curr_val / prev_val)
    return reward

def reward_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = (curr_val - prev_val) / prev_val
    return reward

env = gym.make(
    "MultiDatasetTradingEnv",
    dataset_dir="data/*.pkl",
    preprocess=preprocess_corrected,
    reward_function=reward_risk_adjusted,
    # Valeur initiale du portefeuille
    portfolio_initial_value=1_000,
    # Frais de transactions
    trading_fees=0.1/100,
    # Intérêts sur les prêts
    borrow_interest_rate=0.02/100/24,
)

env.add_metric('Portfolio Valuation', metric_portfolio_valuation)
env = DiscreteActionsWrapper(env, positions=[-0.5,0,0.5,1,1.5])
obs, _ = env.reset()

model = PPO("MlpPolicy",
            env,
            gamma=0.995, 
            gae_lambda=0.95,
            learning_rate=linear_schedule(0.0003), 
            ent_coef=0.01, 
            batch_size=64,
            n_steps=2048,
            verbose=1
)

model = model.learn(total_timesteps=1_500_000)
model.save("PPO_v9")

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
-----------------------------
| time/              |      |
|    fps             | 921  |
|    iterations      | 1    |
|    time_elapsed    | 2    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 366         |
|    iterations           | 2           |
|    time_elapsed         | 11          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.009123713 |
|    clip_fraction        | 0.0364      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.61       |
|    explained_variance   | -22.5       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0121     |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0041     |
|    value_loss           | 0.000335    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 323         |
|    iterations           | 3           |
|    time_elapsed         | 18          |
|    total_timesteps      | 6144        |
| train/                  |             |
|    approx_kl            | 0.013730226 |
|    clip_fraction        | 0.0755      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.59       |
|    explained_variance   | -5.29       |
|    learning_rate        | 0.000299    |
|    loss                 | -0.0355     |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.00658    |
|    value_loss           | 6.33e-05    |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 292        |
|    iterations           | 4          |
|    time_elapsed         | 27         |
|    total_timesteps      | 8192       |
| train/                  |            |
|    approx_kl            | 0.01521696 |
|    clip_fraction        | 0.18       |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.55      |
|    explained_variance   | -0.716     |
|    learning_rate        | 0.000299   |
|    loss                 | -0.00777   |
|    n_updates            | 30         |
|    policy_gradient_loss | -0.0164    |
|    value_loss           | 3.99e-05   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 288         |
|    iterations           | 5           |
|    time_elapsed         | 35          |
|    total_timesteps      | 10240       |
| train/                  |             |
|    approx_kl            | 0.012897229 |
|    clip_fraction        | 0.173       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.49       |
|    explained_variance   | -0.245      |
|    learning_rate        | 0.000298    |
|    loss                 | -0.0373     |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.0198     |
|    value_loss           | 3.06e-05    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 282         |
|    iterations           | 6           |
|    time_elapsed         | 43          |
|    total_timesteps      | 12288       |
| train/                  |             |
|    approx_kl            | 0.014848646 |
|    clip_fraction        | 0.188       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.41       |
|    explained_variance   | -0.128      |
|    learning_rate        | 0.000298    |
|    loss                 | -0.044      |
|    n_updates            | 50          |
|    policy_gradient_loss | -0.0197     |
|    value_loss           | 3.03e-05    |
-----------------------------------------
Market Return :  5.93%   |   Portfolio Return : -99.98%   |   Portfolio Valuation : 0.21   |
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -13.2       |
| time/                   |             |
|    fps                  | 279         |
|    iterations           | 7           |
|    time_elapsed         | 51          |
|    total_timesteps      | 14336       |
| train/                  |             |
|    approx_kl            | 0.011319164 |
|    clip_fraction        | 0.145       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.34       |
|    explained_variance   | -0.281      |
|    learning_rate        | 0.000298    |
|    loss                 | -0.0221     |
|    n_updates            | 60          |
|    policy_gradient_loss | -0.0175     |
|    value_loss           | 1.72e-05    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -13.2       |
| time/                   |             |
|    fps                  | 278         |
|    iterations           | 8           |
|    time_elapsed         | 58          |
|    total_timesteps      | 16384       |
| train/                  |             |
|    approx_kl            | 0.012751851 |
|    clip_fraction        | 0.16        |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.22       |
|    explained_variance   | -0.0674     |
|    learning_rate        | 0.000297    |
|    loss                 | -0.0258     |
|    n_updates            | 70          |
|    policy_gradient_loss | -0.016      |
|    value_loss           | 3.99e-05    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -13.2       |
| time/                   |             |
|    fps                  | 278         |
|    iterations           | 9           |
|    time_elapsed         | 66          |
|    total_timesteps      | 18432       |
| train/                  |             |
|    approx_kl            | 0.009127304 |
|    clip_fraction        | 0.122       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.13       |
|    explained_variance   | -0.0783     |
|    learning_rate        | 0.000297    |
|    loss                 | -0.0231     |
|    n_updates            | 80          |
|    policy_gradient_loss | -0.0118     |
|    value_loss           | 4.38e-05    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.24e+04     |
|    ep_rew_mean          | -13.2        |
| time/                   |              |
|    fps                  | 277          |
|    iterations           | 10           |
|    time_elapsed         | 73           |
|    total_timesteps      | 20480        |
| train/                  |              |
|    approx_kl            | 0.0117176175 |
|    clip_fraction        | 0.0942       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.02        |
|    explained_variance   | -0.104       |
|    learning_rate        | 0.000296     |
|    loss                 | -0.0196      |
|    n_updates            | 90           |
|    policy_gradient_loss | -0.0116      |
|    value_loss           | 5.37e-05     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -13.2       |
| time/                   |             |
|    fps                  | 277         |
|    iterations           | 11          |
|    time_elapsed         | 81          |
|    total_timesteps      | 22528       |
| train/                  |             |
|    approx_kl            | 0.008001675 |
|    clip_fraction        | 0.0982      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.911      |
|    explained_variance   | -0.144      |
|    learning_rate        | 0.000296    |
|    loss                 | -0.0289     |
|    n_updates            | 100         |
|    policy_gradient_loss | -0.0126     |
|    value_loss           | 4.22e-05    |
-----------------------------------------
Market Return : 103.53%   |   Portfolio Return : -97.07%   |   Portfolio Valuation : 29.26   |
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.19e+04    |
|    ep_rew_mean          | -10.1       |
| time/                   |             |
|    fps                  | 275         |
|    iterations           | 12          |
|    time_elapsed         | 89          |
|    total_timesteps      | 24576       |
| train/                  |             |
|    approx_kl            | 0.008606648 |
|    clip_fraction        | 0.0905      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.824      |
|    explained_variance   | -0.0483     |
|    learning_rate        | 0.000295    |
|    loss                 | -0.0192     |
|    n_updates            | 110         |
|    policy_gradient_loss | -0.00991    |
|    value_loss           | 5.54e-05    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.19e+04    |
|    ep_rew_mean          | -10.1       |
| time/                   |             |
|    fps                  | 275         |
|    iterations           | 13          |
|    time_elapsed         | 96          |
|    total_timesteps      | 26624       |
| train/                  |             |
|    approx_kl            | 0.005490318 |
|    clip_fraction        | 0.0632      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.718      |
|    explained_variance   | 0.0303      |
|    learning_rate        | 0.000295    |
|    loss                 | -0.0143     |
|    n_updates            | 120         |
|    policy_gradient_loss | -0.00826    |
|    value_loss           | 5.65e-05    |
-----------------------------------------
Market Return :  9.40%   |   Portfolio Return : -46.84%   |   Portfolio Valuation : 531.57   |
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 9.48e+03    |
|    ep_rew_mean          | -7.4        |
| time/                   |             |
|    fps                  | 274         |
|    iterations           | 14          |
|    time_elapsed         | 104         |
|    total_timesteps      | 28672       |
| train/                  |             |
|    approx_kl            | 0.005514729 |
|    clip_fraction        | 0.0625      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.665      |
|    explained_variance   | -0.0302     |
|    learning_rate        | 0.000295    |
|    loss                 | -0.00299    |
|    n_updates            | 130         |
|    policy_gradient_loss | -0.00802    |
|    value_loss           | 5.2e-05     |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 9.48e+03     |
|    ep_rew_mean          | -7.4         |
| time/                   |              |
|    fps                  | 274          |
|    iterations           | 15           |
|    time_elapsed         | 111          |
|    total_timesteps      | 30720        |
| train/                  |              |
|    approx_kl            | 0.0045431936 |
|    clip_fraction        | 0.0463       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.609       |
|    explained_variance   | -0.112       |
|    learning_rate        | 0.000294     |
|    loss                 | -0.0158      |
|    n_updates            | 140          |
|    policy_gradient_loss | -0.007       |
|    value_loss           | 6.6e-05      |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 9.48e+03     |
|    ep_rew_mean          | -7.4         |
| time/                   |              |
|    fps                  | 274          |
|    iterations           | 16           |
|    time_elapsed         | 119          |
|    total_timesteps      | 32768        |
| train/                  |              |
|    approx_kl            | 0.0050843954 |
|    clip_fraction        | 0.0579       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.581       |
|    explained_variance   | -0.015       |
|    learning_rate        | 0.000294     |
|    loss                 | -0.00733     |
|    n_updates            | 150          |
|    policy_gradient_loss | -0.00431     |
|    value_loss           | 0.000221     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 9.48e+03     |
|    ep_rew_mean          | -7.4         |
| time/                   |              |
|    fps                  | 274          |
|    iterations           | 17           |
|    time_elapsed         | 126          |
|    total_timesteps      | 34816        |
| train/                  |              |
|    approx_kl            | 0.0020381946 |
|    clip_fraction        | 0.0275       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.567       |
|    explained_variance   | -0.00856     |
|    learning_rate        | 0.000293     |
|    loss                 | -0.00997     |
|    n_updates            | 160          |
|    policy_gradient_loss | -0.00196     |
|    value_loss           | 0.000572     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 9.48e+03     |
|    ep_rew_mean          | -7.4         |
| time/                   |              |
|    fps                  | 274          |
|    iterations           | 18           |
|    time_elapsed         | 134          |
|    total_timesteps      | 36864        |
| train/                  |              |
|    approx_kl            | 0.0035243449 |
|    clip_fraction        | 0.0331       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.573       |
|    explained_variance   | 0.0531       |
|    learning_rate        | 0.000293     |
|    loss                 | -0.0103      |
|    n_updates            | 170          |
|    policy_gradient_loss | -0.00303     |
|    value_loss           | 0.000515     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 9.48e+03    |
|    ep_rew_mean          | -7.4        |
| time/                   |             |
|    fps                  | 274         |
|    iterations           | 19          |
|    time_elapsed         | 141         |
|    total_timesteps      | 38912       |
| train/                  |             |
|    approx_kl            | 0.004250042 |
|    clip_fraction        | 0.0411      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.58       |
|    explained_variance   | 0.0691      |
|    learning_rate        | 0.000293    |
|    loss                 | -0.0197     |
|    n_updates            | 180         |
|    policy_gradient_loss | -0.00419    |
|    value_loss           | 0.000668    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 9.48e+03     |
|    ep_rew_mean          | -7.4         |
| time/                   |              |
|    fps                  | 274          |
|    iterations           | 20           |
|    time_elapsed         | 149          |
|    total_timesteps      | 40960        |
| train/                  |              |
|    approx_kl            | 0.0046908283 |
|    clip_fraction        | 0.0563       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.611       |
|    explained_variance   | -0.121       |
|    learning_rate        | 0.000292     |
|    loss                 | -0.0146      |
|    n_updates            | 190          |
|    policy_gradient_loss | -0.00362     |
|    value_loss           | 0.000308     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 9.48e+03    |
|    ep_rew_mean          | -7.4        |
| time/                   |             |
|    fps                  | 274         |
|    iterations           | 21          |
|    time_elapsed         | 156         |
|    total_timesteps      | 43008       |
| train/                  |             |
|    approx_kl            | 0.005972406 |
|    clip_fraction        | 0.0577      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.599      |
|    explained_variance   | -0.0211     |
|    learning_rate        | 0.000292    |
|    loss                 | -0.00425    |
|    n_updates            | 200         |
|    policy_gradient_loss | -0.00592    |
|    value_loss           | 0.000351    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 9.48e+03    |
|    ep_rew_mean          | -7.4        |
| time/                   |             |
|    fps                  | 274         |
|    iterations           | 22          |
|    time_elapsed         | 163         |
|    total_timesteps      | 45056       |
| train/                  |             |
|    approx_kl            | 0.003570868 |
|    clip_fraction        | 0.0587      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.581      |
|    explained_variance   | -0.027      |
|    learning_rate        | 0.000291    |
|    loss                 | -0.0275     |
|    n_updates            | 210         |
|    policy_gradient_loss | -0.00691    |
|    value_loss           | 0.000299    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 9.48e+03     |
|    ep_rew_mean          | -7.4         |
| time/                   |              |
|    fps                  | 274          |
|    iterations           | 23           |
|    time_elapsed         | 171          |
|    total_timesteps      | 47104        |
| train/                  |              |
|    approx_kl            | 0.0034994981 |
|    clip_fraction        | 0.0363       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.595       |
|    explained_variance   | 0.0961       |
|    learning_rate        | 0.000291     |
|    loss                 | -0.0109      |
|    n_updates            | 220          |
|    policy_gradient_loss | -0.00444     |
|    value_loss           | 0.000456     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 9.48e+03    |
|    ep_rew_mean          | -7.4        |
| time/                   |             |
|    fps                  | 273         |
|    iterations           | 24          |
|    time_elapsed         | 179         |
|    total_timesteps      | 49152       |
| train/                  |             |
|    approx_kl            | 0.003633298 |
|    clip_fraction        | 0.0383      |

In [29]:
nb_episodes = 30

for episode in range(1, nb_episodes + 1):
    obs, _ = env.reset()
    print(f'Episode n˚{episode} -- Jeu de donnée {env.env.name}')
    done = False

    while not done:
        action, _states = model.predict(obs)
        obs, reward, terminated, truncated, _ = env.step(action.tolist())
        done = terminated or truncated
    env.env.save_for_render(dir="logs")        
    if terminated:
        print('Argent perdu')
        
    elif truncated:
        print('Épisode terminé')

Episode n˚1 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 946.44%   |   Portfolio Return :  2.32%   |   Portfolio Valuation : 1023.2   |
Épisode terminé
Episode n˚2 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : -0.05%   |   Portfolio Valuation : 999.49   |
Épisode terminé
Episode n˚3 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -0.14%   |   Portfolio Valuation : 998.64   |
Épisode terminé
Episode n˚4 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : -0.39%   |   Portfolio Valuation : 996.07   |
Épisode terminé
Episode n˚5 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return :  0.92%   |   Portfolio Valuation : 1009.15   |
Épisode terminé
Episode n˚6 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -0.18%   |   Portfolio Valuation : 998.25   |
Épisode terminé
Episode n˚7 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 376.91%   |   Portfolio Return : -1.13%   |   Portfolio Valuation : 988.67   |
Épisode terminé
Episode n˚8 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : -1.20%   |   Portfolio Valuation : 987.98   |
Épisode terminé
Episode n˚9 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : -0.92%   |   Portfolio Valuation : 990.78   |
Épisode terminé
Episode n˚10 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 946.44%   |   Portfolio Return : -2.30%   |   Portfolio Valuation : 976.99   |
Épisode terminé
Episode n˚11 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : -0.01%   |   Portfolio Valuation : 999.88   |
Épisode terminé
Episode n˚12 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : -0.70%   |   Portfolio Valuation : 992.96   |
Épisode terminé
Episode n˚13 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -1.01%   |   Portfolio Valuation : 989.9   |
Épisode terminé
Episode n˚14 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : -0.05%   |   Portfolio Valuation : 999.54   |
Épisode terminé
Episode n˚15 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -0.22%   |   Portfolio Valuation : 997.79   |
Épisode terminé
Episode n˚16 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : -0.16%   |   Portfolio Valuation : 998.42   |
Épisode terminé
Episode n˚17 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 376.91%   |   Portfolio Return : -3.68%   |   Portfolio Valuation : 963.24   |
Épisode terminé
Episode n˚18 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : -0.36%   |   Portfolio Valuation : 996.41   |
Épisode terminé
Episode n˚19 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -0.03%   |   Portfolio Valuation : 999.74   |
Épisode terminé
Episode n˚20 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return :  1.28%   |   Portfolio Valuation : 1012.82   |
Épisode terminé
Episode n˚21 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : -0.16%   |   Portfolio Valuation : 998.43   |
Épisode terminé
Episode n˚22 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 376.91%   |   Portfolio Return : -4.85%   |   Portfolio Valuation : 951.47   |
Épisode terminé
Episode n˚23 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 946.44%   |   Portfolio Return : -0.35%   |   Portfolio Valuation : 996.49   |
Épisode terminé
Episode n˚24 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : -0.06%   |   Portfolio Valuation : 999.4   |
Épisode terminé
Episode n˚25 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : -1.95%   |   Portfolio Valuation : 980.55   |
Épisode terminé
Episode n˚26 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -0.70%   |   Portfolio Valuation : 993.03   |
Épisode terminé
Episode n˚27 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : -0.38%   |   Portfolio Valuation : 996.21   |
Épisode terminé
Episode n˚28 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : -0.31%   |   Portfolio Valuation : 996.9   |
Épisode terminé
Episode n˚29 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : -0.10%   |   Portfolio Valuation : 999.0   |
Épisode terminé
Episode n˚30 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : -0.50%   |   Portfolio Valuation : 994.97   |
Épisode terminé

In [ ]:
from typing import Callable
from sb3_contrib import RecurrentPPO

def linear_schedule(initial_value: float) -> Callable[[float], float]:
    def func(progress_remaining: float) -> float:
        return progress_remaining * initial_value
    return func

def preprocess_corrected(df):
    df = df.copy()
    
    df['feature_log_ret'] = np.log(df['close'] / df['close'].shift(1))

    df['feature_rsi'] = ta.rsi(df['close'], length=14) / 100.0 
    
    macd = ta.macd(df['close'])
    df['feature_macd_norm'] = macd['MACD_12_26_9'] / df['close']
    for i in range(1, 6):
        df[f'feature_log_ret_lag_{i}'] = df['feature_log_ret'].shift(i)

    df['feature_atr_norm'] = ta.atr(df['high'], df['low'], df['close'], length=14) / df['close']
    
    df['feature_hour_sin'] = np.sin(2 * np.pi * df.index.hour / 24)
    df['feature_hour_cos'] = np.cos(2 * np.pi * df.index.hour / 24)

    df = df.dropna().replace([np.inf, -np.inf], 0)
    return df


def metric_portfolio_valuation(history):
    return round(history['portfolio_valuation', -1], 2)

def reward_risk_adjusted(history):
    # Rendement actuel
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    if prev_val == 0: return 0
    
    # Rendement Logarithmique
    log_return = np.log(curr_val / prev_val)
    
    # On veut maximiser le gain, mais on soustrait une pénalité si l'agent est trop volatil
    # Astuce : On ne peut pas calculer la volatilité sur 1 step, 
    # mais on peut punir les gros mouvements négatifs plus fort.
    
    risk_penalty = 0
    if log_return < 0:
        # On punit les pertes 2x plus fort que les gains ne sont récompensés
        risk_penalty = abs(log_return) * 0.5 
        
    return log_return - risk_penalty

def reward_function(history):
    return history['step']*(history['portfolio_valuation', -1] - history['portfolio_valuation', -2])

def reward_function_rapport_market(history):
    return 10*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1]))

def reward_function_rapport_market_v2(history):
    weight = 0 
    if (history['position',1] == history['position',-2]):
        weight = 0.1
    return 10*(history['data_open', -2] / history['data_close', -1])*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1])) - weight 

def reward_log_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = np.log(curr_val / prev_val)
    return reward

def reward_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = (curr_val - prev_val) / prev_val
    return reward

env = gym.make(
    "MultiDatasetTradingEnv",
    dataset_dir="data/*.pkl",
    preprocess=preprocess_corrected,
    reward_function=reward_risk_adjusted,
    # Valeur initiale du portefeuille
    portfolio_initial_value=1_000,
    # Frais de transactions
    trading_fees=0.1/100,
    # Intérêts sur les prêts
    borrow_interest_rate=0.02/100/24,
)

env.add_metric('Portfolio Valuation', metric_portfolio_valuation)
env = DiscreteActionsWrapper(env, positions=[-0.5,0,0.5,1,1.5])
obs, _ = env.reset()

model = RecurrentPPO("MlpLstmPolicy",
            env,
            gamma=0.995, 
            gae_lambda=0.95,
            learning_rate=linear_schedule(0.0003), 
            ent_coef=0.01, 
            batch_size=64,
            n_steps=2048,
            verbose=1
)

model = model.learn(total_timesteps=1_500_000)
model.save("PPO_v10")

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
-----------------------------
| time/              |      |
|    fps             | 242  |
|    iterations      | 1    |
|    time_elapsed    | 8    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 146         |
|    iterations           | 2           |
|    time_elapsed         | 27          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.011194831 |
|    clip_fraction        | 0.0759      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.6        |
|    explained_variance   | -1.28       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0162     |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0054     |
|    value_loss           | 0.000639    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 152         |
|    iterations           | 3           |
|    time_elapsed         | 40          |
|    total_timesteps      | 6144        |
| train/                  |             |
|    approx_kl            | 0.009774573 |
|    clip_fraction        | 0.0649      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.6        |
|    explained_variance   | -0.039      |
|    learning_rate        | 0.000299    |
|    loss                 | -0.0188     |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.00782    |
|    value_loss           | 0.00165     |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 157         |
|    iterations           | 4           |
|    time_elapsed         | 51          |
|    total_timesteps      | 8192        |
| train/                  |             |
|    approx_kl            | 0.010972487 |
|    clip_fraction        | 0.0977      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.57       |
|    explained_variance   | -0.0393     |
|    learning_rate        | 0.000299    |
|    loss                 | -0.00848    |
|    n_updates            | 30          |
|    policy_gradient_loss | -0.00858    |
|    value_loss           | 0.000912    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 163         |
|    iterations           | 5           |
|    time_elapsed         | 62          |
|    total_timesteps      | 10240       |
| train/                  |             |
|    approx_kl            | 0.011207301 |
|    clip_fraction        | 0.102       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.55       |
|    explained_variance   | -0.0258     |
|    learning_rate        | 0.000298    |
|    loss                 | -0.0415     |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.00778    |
|    value_loss           | 0.00118     |
-----------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 166          |
|    iterations           | 6            |
|    time_elapsed         | 73           |
|    total_timesteps      | 12288        |
| train/                  |              |
|    approx_kl            | 0.0074324994 |
|    clip_fraction        | 0.091        |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.51        |
|    explained_variance   | -0.00887     |
|    learning_rate        | 0.000298     |
|    loss                 | -0.0302      |
|    n_updates            | 50           |
|    policy_gradient_loss | -0.00792     |
|    value_loss           | 0.000498     |
------------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 169          |
|    iterations           | 7            |
|    time_elapsed         | 84           |
|    total_timesteps      | 14336        |
| train/                  |              |
|    approx_kl            | 0.0070014107 |
|    clip_fraction        | 0.0703       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.47        |
|    explained_variance   | -0.0707      |
|    learning_rate        | 0.000298     |
|    loss                 | -0.00546     |
|    n_updates            | 60           |
|    policy_gradient_loss | -0.00706     |
|    value_loss           | 0.000403     |
------------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 172         |
|    iterations           | 8           |
|    time_elapsed         | 95          |
|    total_timesteps      | 16384       |
| train/                  |             |
|    approx_kl            | 0.008165513 |
|    clip_fraction        | 0.097       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.44       |
|    explained_variance   | -0.0199     |
|    learning_rate        | 0.000297    |
|    loss                 | -0.0162     |
|    n_updates            | 70          |
|    policy_gradient_loss | -0.006      |
|    value_loss           | 0.000444    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 173         |
|    iterations           | 9           |
|    time_elapsed         | 106         |
|    total_timesteps      | 18432       |
| train/                  |             |
|    approx_kl            | 0.006473259 |
|    clip_fraction        | 0.0717      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.41       |
|    explained_variance   | -0.00461    |
|    learning_rate        | 0.000297    |
|    loss                 | -0.0391     |
|    n_updates            | 80          |
|    policy_gradient_loss | -0.0063     |
|    value_loss           | 0.000522    |
-----------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 175          |
|    iterations           | 10           |
|    time_elapsed         | 116          |
|    total_timesteps      | 20480        |
| train/                  |              |
|    approx_kl            | 0.0057243416 |
|    clip_fraction        | 0.0672       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.4         |
|    explained_variance   | -0.0274      |
|    learning_rate        | 0.000296     |
|    loss                 | -0.0229      |
|    n_updates            | 90           |
|    policy_gradient_loss | -0.00536     |
|    value_loss           | 0.0002       |
------------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 176         |
|    iterations           | 11          |
|    time_elapsed         | 127         |
|    total_timesteps      | 22528       |
| train/                  |             |
|    approx_kl            | 0.009153893 |
|    clip_fraction        | 0.1         |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.32       |
|    explained_variance   | 0.0309      |
|    learning_rate        | 0.000296    |
|    loss                 | -0.0248     |
|    n_updates            | 100         |
|    policy_gradient_loss | -0.0109     |
|    value_loss           | 0.000253    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 177         |
|    iterations           | 12          |
|    time_elapsed         | 138         |
|    total_timesteps      | 24576       |
| train/                  |             |
|    approx_kl            | 0.013208579 |
|    clip_fraction        | 0.169       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.24       |
|    explained_variance   | -0.0279     |
|    learning_rate        | 0.000295    |
|    loss                 | -0.0332     |
|    n_updates            | 110         |
|    policy_gradient_loss | -0.0169     |
|    value_loss           | 0.000135    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 177         |
|    iterations           | 13          |
|    time_elapsed         | 149         |
|    total_timesteps      | 26624       |
| train/                  |             |
|    approx_kl            | 0.010541925 |
|    clip_fraction        | 0.0982      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.18       |
|    explained_variance   | -0.0226     |
|    learning_rate        | 0.000295    |
|    loss                 | -0.00933    |
|    n_updates            | 120         |
|    policy_gradient_loss | -0.00821    |
|    value_loss           | 0.000227    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 177         |
|    iterations           | 14          |
|    time_elapsed         | 161         |
|    total_timesteps      | 28672       |
| train/                  |             |
|    approx_kl            | 0.010658655 |
|    clip_fraction        | 0.128       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.1        |
|    explained_variance   | -0.0801     |
|    learning_rate        | 0.000295    |
|    loss                 | -0.00415    |
|    n_updates            | 130         |
|    policy_gradient_loss | -0.013      |
|    value_loss           | 0.000102    |
-----------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 178          |
|    iterations           | 15           |
|    time_elapsed         | 171          |
|    total_timesteps      | 30720        |
| train/                  |              |
|    approx_kl            | 0.0094614625 |
|    clip_fraction        | 0.118        |
|    clip_range           | 0.2          |
|    entropy_loss         | -1           |
|    explained_variance   | -0.00698     |
|    learning_rate        | 0.000294     |
|    loss                 | -0.0346      |
|    n_updates            | 140          |
|    policy_gradient_loss | -0.0117      |
|    value_loss           | 5.7e-05      |
------------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 179         |
|    iterations           | 16          |
|    time_elapsed         | 182         |
|    total_timesteps      | 32768       |
| train/                  |             |
|    approx_kl            | 0.010456853 |
|    clip_fraction        | 0.143       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.932      |
|    explained_variance   | -0.025      |
|    learning_rate        | 0.000294    |
|    loss                 | -0.00685    |
|    n_updates            | 150         |
|    policy_gradient_loss | -0.0135     |
|    value_loss           | 0.000101    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 177         |
|    iterations           | 17          |
|    time_elapsed         | 196         |
|    total_timesteps      | 34816       |
| train/                  |             |
|    approx_kl            | 0.008663171 |
|    clip_fraction        | 0.111       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.847      |
|    explained_variance   | -0.00153    |
|    learning_rate        | 0.000293    |
|    loss                 | -0.0215     |
|    n_updates            | 160         |
|    policy_gradient_loss | -0.01       |
|    value_loss           | 9.72e-05    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 177         |
|    iterations           | 18          |
|    time_elapsed         | 207         |
|    total_timesteps      | 36864       |
| train/                  |             |
|    approx_kl            | 0.008058053 |
|    clip_fraction        | 0.0941      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.767      |
|    explained_variance   | -0.0285     |
|    learning_rate        | 0.000293    |
|    loss                 | 0.00652     |
|    n_updates            | 170         |
|    policy_gradient_loss | -0.00984    |
|    value_loss           | 8.11e-05    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 168         |
|    iterations           | 19          |
|    time_elapsed         | 230         |
|    total_timesteps      | 38912       |
| train/                  |             |
|    approx_kl            | 0.008073455 |
|    clip_fraction        | 0.103       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.681      |
|    explained_variance   | -0.00429    |
|    learning_rate        | 0.000293    |
|    loss                 | -0.022      |
|    n_updates            | 180         |
|    policy_gradient_loss | -0.0117     |
|    value_loss           | 9.8e-05     |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 168         |
|    iterations           | 20          |
|    time_elapsed         | 243         |
|    total_timesteps      | 40960       |
| train/                  |             |
|    approx_kl            | 0.008758422 |
|    clip_fraction        | 0.0952      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.602      |
|    explained_variance   | -0.0075     |
|    learning_rate        | 0.000292    |
|    loss                 | 0.0372      |
|    n_updates            | 190         |
|    policy_gradient_loss | -0.00912    |
|    value_loss           | 5.81e-05    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 166         |
|    iterations           | 21          |
|    time_elapsed         | 258         |
|    total_timesteps      | 43008       |
| train/                  |             |
|    approx_kl            | 0.006759167 |
|    clip_fraction        | 0.084       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.531      |
|    explained_variance   | -0.0199     |
|    learning_rate        | 0.000292    |
|    loss                 | -0.00541    |
|    n_updates            | 200         |
|    policy_gradient_loss | -0.00836    |
|    value_loss           | 6.4e-05     |
-----------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 167          |
|    iterations           | 22           |
|    time_elapsed         | 269          |
|    total_timesteps      | 45056        |
| train/                  |              |
|    approx_kl            | 0.0051828967 |
|    clip_fraction        | 0.0787       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.463       |
|    explained_variance   | 0.0327       |
|    learning_rate        | 0.000291     |
|    loss                 | -0.0221      |
|    n_updates            | 210          |
|    policy_gradient_loss | -0.00956     |
|    value_loss           | 2.32e-05     |
------------------------------------------
Market Return : 699.62%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.0   |
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 4.62e+04     |
|    ep_rew_mean          | -46.7        |
| time/                   |              |
|    fps                  | 166          |
|    iterations           | 23           |
|    time_elapsed         | 282          |
|    total_timesteps      | 47104        |
| train/                  |              |
|    approx_kl            | 0.0050918562 |
|    clip_fraction        | 0.0778       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.378       |
|    explained_variance   | 0.00129      |
|    learning_rate        | 0.000291     |
|    loss                 | -0.0064      |
|    n_updates            | 220          |
|    policy_gradient_loss | -0.0111      |
|    value_loss           | 2.59e-05     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 4.62e+04    |
|    ep_rew_mean          | -46.7       |
| time/                   |             |
|    fps                  | 166         |
|    iterations           | 24          |
|    time_elapsed         | 295         |
|    total_timesteps      | 49152       |
| train/                  |             |
|    approx_kl            | 0.004401584 |
|    clip_fraction        | 0.0555      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.32       |
|    explained_variance   | -0.0447     |
|    learning_rate        | 0.000291    |
|    loss                 | -0.000726   |
|    n_updates            | 230         |
|    policy_gradient_loss | -0.00629    |
|    value_loss           | 1.75e-05    |
-----------------------------------------
Market Return : 26.58%   |   Portfolio Return : -25.32%   |   Portfolio Valuation : 746.75   |
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 2.54e+04     |
|    ep_rew_mean          | -23.6        |
| time/                   |              |
|    fps                  | 166          |
|    iterations           | 25           |
|    time_elapsed         | 307          |
|    total_timesteps      | 51200        |
| train/                  |              |
|    approx_kl            | 0.0038377168 |
|    clip_fraction        | 0.059        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.275       |
|    explained_variance   | -0.0764      |
|    learning_rate        | 0.00029      |
|    loss                 | -0.0464      |
|    n_updates            | 240          |
|    policy_gradient_loss | -0.0105      |
|    value_loss           | 1.23e-05     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 2.54e+04     |
|    ep_rew_mean          | -23.6        |
| time/                   |              |
|    fps                  | 166          |
|    iterations           | 26           |
|    time_elapsed         | 320          |
|    total_timesteps      | 53248        |
| train/                  |              |
|    approx_kl            | 0.0032777789 |
|    clip_fraction        | 0.0482       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.248       |
|    explained_variance   | -0.0332      |
|    learning_rate        | 0.00029      |
|    loss                 | 0.012        |
|    n_updates            | 250          |
|    policy_gradient_loss | -0.0082      |

In [ ]:
nb_episodes = 30

for episode in range(1, nb_episodes + 1):
    obs, _ = env.reset()
    print(f'Episode n˚{episode} -- Jeu de donnée {env.env.name}')
    done = False

    while not done:
        action, _states = model.predict(obs)
        obs, reward, terminated, truncated, _ = env.step(action.tolist())
        done = terminated or truncated
    env.env.save_for_render(dir="logs")        
    if terminated:
        print('Argent perdu')
        
    elif truncated:
        print('Épisode terminé')

In [8]:
from typing import Callable
from sb3_contrib import RecurrentPPO

def linear_schedule(initial_value: float) -> Callable[[float], float]:
    def func(progress_remaining: float) -> float:
        return progress_remaining * initial_value
    return func

def preprocess_corrected(df):
    df = df.copy()
    
    df['feature_log_ret'] = np.log(df['close'] / df['close'].shift(1))

    df['feature_rsi'] = ta.rsi(df['close'], length=14) / 100.0 
    
    macd = ta.macd(df['close'])
    df['feature_macd_norm'] = macd['MACD_12_26_9'] / df['close']
    for i in range(1, 6):
        df[f'feature_log_ret_lag_{i}'] = df['feature_log_ret'].shift(i)

    df['feature_atr_norm'] = ta.atr(df['high'], df['low'], df['close'], length=14) / df['close']
    
    df['feature_hour_sin'] = np.sin(2 * np.pi * df.index.hour / 24)
    df['feature_hour_cos'] = np.cos(2 * np.pi * df.index.hour / 24)

    df = df.dropna().replace([np.inf, -np.inf], 0)
    return df


def metric_portfolio_valuation(history):
    return round(history['portfolio_valuation', -1], 2)

def reward_risk_adjusted(history):
    # Rendement actuel
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    if prev_val == 0: return 0
    
    # Rendement Logarithmique
    log_return = np.log(curr_val / prev_val)
    
    # On veut maximiser le gain, mais on soustrait une pénalité si l'agent est trop volatil
    # Astuce : On ne peut pas calculer la volatilité sur 1 step, 
    # mais on peut punir les gros mouvements négatifs plus fort.
    
    risk_penalty = 0
    if log_return < 0:
        # On punit les pertes 2x plus fort que les gains ne sont récompensés
        risk_penalty = abs(log_return) * 0.5 
        
    return log_return - risk_penalty

def reward_function(history):
    return history['step']*(history['portfolio_valuation', -1] - history['portfolio_valuation', -2])

def reward_function_rapport_market(history):
    return 10*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1]))

def reward_function_rapport_market_v2(history):
    weight = 0 
    if (history['position',1] == history['position',-2]):
        weight = 0.1
    return 10*(history['data_open', -2] / history['data_close', -1])*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1])) - weight 

def reward_log_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = np.log(curr_val / prev_val)
    return reward

def reward_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = (curr_val - prev_val) / prev_val
    return reward

env = gym.make(
    "MultiDatasetTradingEnv",
    dataset_dir="data/*.pkl",
    preprocess=preprocess_corrected,
    reward_function=reward_returns,
    # Valeur initiale du portefeuille
    portfolio_initial_value=1_000,
    # Frais de transactions
    trading_fees=0.1/100,
    # Intérêts sur les prêts
    borrow_interest_rate=0.02/100/24,
)

env.add_metric('Portfolio Valuation', metric_portfolio_valuation)
env = DiscreteActionsWrapper(env, positions=[-0.5,0,0.5,1,1.5])
obs, _ = env.reset()

model = RecurrentPPO("MlpLstmPolicy",
            env,
            gamma=0.995, 
            gae_lambda=0.95,
            learning_rate=linear_schedule(0.0003), 
            ent_coef=0.01, 
            batch_size=64,
            n_steps=2048,
            verbose=1
)

model = model.learn(total_timesteps=1_500_000)
model.save("PPO_v11")

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
-----------------------------
| time/              |      |
|    fps             | 281  |
|    iterations      | 1    |
|    time_elapsed    | 7    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 154         |
|    iterations           | 2           |
|    time_elapsed         | 26          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.021107545 |
|    clip_fraction        | 0.109       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.6        |
|    explained_variance   | -16.6       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.00485    |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0078     |
|    value_loss           | 0.00012     |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 140         |
|    iterations           | 3           |
|    time_elapsed         | 43          |
|    total_timesteps      | 6144        |
| train/                  |             |
|    approx_kl            | 0.014886995 |
|    clip_fraction        | 0.152       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.57       |
|    explained_variance   | -8.85       |
|    learning_rate        | 0.000299    |
|    loss                 | -0.0205     |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.00861    |
|    value_loss           | 1.91e-05    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 136         |
|    iterations           | 4           |
|    time_elapsed         | 60          |
|    total_timesteps      | 8192        |
| train/                  |             |
|    approx_kl            | 0.012461495 |
|    clip_fraction        | 0.198       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.52       |
|    explained_variance   | -0.236      |
|    learning_rate        | 0.000299    |
|    loss                 | -0.0557     |
|    n_updates            | 30          |
|    policy_gradient_loss | -0.0209     |
|    value_loss           | 3.44e-05    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 134         |
|    iterations           | 5           |
|    time_elapsed         | 76          |
|    total_timesteps      | 10240       |
| train/                  |             |
|    approx_kl            | 0.015561059 |
|    clip_fraction        | 0.209       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.48       |
|    explained_variance   | -0.348      |
|    learning_rate        | 0.000298    |
|    loss                 | -0.0162     |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.0188     |
|    value_loss           | 1.87e-05    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 133         |
|    iterations           | 6           |
|    time_elapsed         | 92          |
|    total_timesteps      | 12288       |
| train/                  |             |
|    approx_kl            | 0.013734872 |
|    clip_fraction        | 0.189       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.44       |
|    explained_variance   | -0.109      |
|    learning_rate        | 0.000298    |
|    loss                 | -0.0596     |
|    n_updates            | 50          |
|    policy_gradient_loss | -0.0188     |
|    value_loss           | 1.55e-05    |
-----------------------------------------
Market Return :  5.93%   |   Portfolio Return : -99.98%   |   Portfolio Valuation : 0.2   |
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.53       |
| time/                   |             |
|    fps                  | 132         |
|    iterations           | 7           |
|    time_elapsed         | 108         |
|    total_timesteps      | 14336       |
| train/                  |             |
|    approx_kl            | 0.014730533 |
|    clip_fraction        | 0.212       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.38       |
|    explained_variance   | -0.207      |
|    learning_rate        | 0.000298    |
|    loss                 | -0.055      |
|    n_updates            | 60          |
|    policy_gradient_loss | -0.0213     |
|    value_loss           | 1.51e-05    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.53       |
| time/                   |             |
|    fps                  | 129         |
|    iterations           | 8           |
|    time_elapsed         | 126         |
|    total_timesteps      | 16384       |
| train/                  |             |
|    approx_kl            | 0.009243425 |
|    clip_fraction        | 0.0996      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.35       |
|    explained_variance   | 0.000473    |
|    learning_rate        | 0.000297    |
|    loss                 | -0.0372     |
|    n_updates            | 70          |
|    policy_gradient_loss | -0.00833    |
|    value_loss           | 0.00513     |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.24e+04     |
|    ep_rew_mean          | -8.53        |
| time/                   |              |
|    fps                  | 129          |
|    iterations           | 9            |
|    time_elapsed         | 142          |
|    total_timesteps      | 18432        |
| train/                  |              |
|    approx_kl            | 0.0071068103 |
|    clip_fraction        | 0.0815       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.31        |
|    explained_variance   | 0.033        |
|    learning_rate        | 0.000297     |
|    loss                 | -0.00258     |
|    n_updates            | 80           |
|    policy_gradient_loss | -0.00576     |
|    value_loss           | 0.00276      |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.53       |
| time/                   |             |
|    fps                  | 129         |
|    iterations           | 10          |
|    time_elapsed         | 158         |
|    total_timesteps      | 20480       |
| train/                  |             |
|    approx_kl            | 0.009041644 |
|    clip_fraction        | 0.106       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.28       |
|    explained_variance   | -0.0389     |
|    learning_rate        | 0.000296    |
|    loss                 | -0.0347     |
|    n_updates            | 90          |
|    policy_gradient_loss | -0.00622    |
|    value_loss           | 0.000544    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.53       |
| time/                   |             |
|    fps                  | 129         |
|    iterations           | 11          |
|    time_elapsed         | 174         |
|    total_timesteps      | 22528       |
| train/                  |             |
|    approx_kl            | 0.010437548 |
|    clip_fraction        | 0.099       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.21       |
|    explained_variance   | 0.0129      |
|    learning_rate        | 0.000296    |
|    loss                 | -0.0118     |
|    n_updates            | 100         |
|    policy_gradient_loss | -0.00827    |
|    value_loss           | 0.000602    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.53       |
| time/                   |             |
|    fps                  | 129         |
|    iterations           | 12          |
|    time_elapsed         | 189         |
|    total_timesteps      | 24576       |
| train/                  |             |
|    approx_kl            | 0.008758105 |
|    clip_fraction        | 0.118       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.18       |
|    explained_variance   | 0.0209      |
|    learning_rate        | 0.000295    |
|    loss                 | -0.0382     |
|    n_updates            | 110         |
|    policy_gradient_loss | -0.00611    |
|    value_loss           | 0.000392    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.53       |
| time/                   |             |
|    fps                  | 129         |
|    iterations           | 13          |
|    time_elapsed         | 205         |
|    total_timesteps      | 26624       |
| train/                  |             |
|    approx_kl            | 0.009056333 |
|    clip_fraction        | 0.136       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.16       |
|    explained_variance   | -0.0225     |
|    learning_rate        | 0.000295    |
|    loss                 | -0.00306    |
|    n_updates            | 120         |
|    policy_gradient_loss | -0.00462    |
|    value_loss           | 0.000722    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.53       |
| time/                   |             |
|    fps                  | 129         |
|    iterations           | 14          |
|    time_elapsed         | 221         |
|    total_timesteps      | 28672       |
| train/                  |             |
|    approx_kl            | 0.009830646 |
|    clip_fraction        | 0.11        |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.15       |
|    explained_variance   | 0.000144    |
|    learning_rate        | 0.000295    |
|    loss                 | -0.000657   |
|    n_updates            | 130         |
|    policy_gradient_loss | -0.00705    |
|    value_loss           | 0.000469    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.53       |
| time/                   |             |
|    fps                  | 129         |
|    iterations           | 15          |
|    time_elapsed         | 236         |
|    total_timesteps      | 30720       |
| train/                  |             |
|    approx_kl            | 0.008249103 |
|    clip_fraction        | 0.104       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.15       |
|    explained_variance   | 0.00429     |
|    learning_rate        | 0.000294    |
|    loss                 | -0.0206     |
|    n_updates            | 140         |
|    policy_gradient_loss | -0.0087     |
|    value_loss           | 0.00118     |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.53       |
| time/                   |             |
|    fps                  | 129         |
|    iterations           | 16          |
|    time_elapsed         | 252         |
|    total_timesteps      | 32768       |
| train/                  |             |
|    approx_kl            | 0.008280099 |
|    clip_fraction        | 0.0977      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.13       |
|    explained_variance   | -0.0774     |
|    learning_rate        | 0.000294    |
|    loss                 | -0.0436     |
|    n_updates            | 150         |
|    policy_gradient_loss | -0.00586    |
|    value_loss           | 0.000333    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.53       |
| time/                   |             |
|    fps                  | 129         |
|    iterations           | 17          |
|    time_elapsed         | 269         |
|    total_timesteps      | 34816       |
| train/                  |             |
|    approx_kl            | 0.009182833 |
|    clip_fraction        | 0.112       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.11       |
|    explained_variance   | -0.00739    |
|    learning_rate        | 0.000293    |
|    loss                 | -0.0314     |
|    n_updates            | 160         |
|    policy_gradient_loss | -0.00775    |
|    value_loss           | 0.000611    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.53       |
| time/                   |             |
|    fps                  | 129         |
|    iterations           | 18          |
|    time_elapsed         | 285         |
|    total_timesteps      | 36864       |
| train/                  |             |
|    approx_kl            | 0.010668918 |
|    clip_fraction        | 0.111       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.07       |
|    explained_variance   | -0.0121     |
|    learning_rate        | 0.000293    |
|    loss                 | -0.0179     |
|    n_updates            | 170         |
|    policy_gradient_loss | -0.00847    |
|    value_loss           | 0.000337    |
-----------------------------------------
---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 1.24e+04  |
|    ep_rew_mean          | -8.53     |
| time/                   |           |
|    fps                  | 128       |
|    iterations           | 19        |
|    time_elapsed         | 301       |
|    total_timesteps      | 38912     |
| train/                  |           |
|    approx_kl            | 0.0080666 |
|    clip_fraction        | 0.0969    |
|    clip_range           | 0.2       |
|    entropy_loss         | -1        |
|    explained_variance   | -0.0251   |
|    learning_rate        | 0.000293  |
|    loss                 | -0.0122   |
|    n_updates            | 180       |
|    policy_gradient_loss | -0.00717  |
|    value_loss           | 0.000116  |
---------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.53       |
| time/                   |             |
|    fps                  | 129         |
|    iterations           | 20          |
|    time_elapsed         | 317         |
|    total_timesteps      | 40960       |
| train/                  |             |
|    approx_kl            | 0.011581888 |
|    clip_fraction        | 0.121       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.924      |
|    explained_variance   | -0.00494    |
|    learning_rate        | 0.000292    |
|    loss                 | -0.0405     |
|    n_updates            | 190         |
|    policy_gradient_loss | -0.00944    |
|    value_loss           | 0.00018     |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.24e+04     |
|    ep_rew_mean          | -8.53        |
| time/                   |              |
|    fps                  | 129          |
|    iterations           | 21           |
|    time_elapsed         | 333          |
|    total_timesteps      | 43008        |
| train/                  |              |
|    approx_kl            | 0.0061282846 |
|    clip_fraction        | 0.0684       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.929       |
|    explained_variance   | -0.000422    |
|    learning_rate        | 0.000292     |
|    loss                 | -0.0029      |
|    n_updates            | 200          |
|    policy_gradient_loss | -0.00404     |
|    value_loss           | 0.00101      |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.53       |
| time/                   |             |
|    fps                  | 129         |
|    iterations           | 22          |
|    time_elapsed         | 348         |
|    total_timesteps      | 45056       |
| train/                  |             |
|    approx_kl            | 0.008129716 |
|    clip_fraction        | 0.0943      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.929      |
|    explained_variance   | -0.0111     |
|    learning_rate        | 0.000291    |
|    loss                 | -0.0275     |
|    n_updates            | 210         |
|    policy_gradient_loss | -0.00514    |
|    value_loss           | 0.000277    |
-----------------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.24e+04   |
|    ep_rew_mean          | -8.53      |
| time/                   |            |
|    fps                  | 129        |
|    iterations           | 23         |
|    time_elapsed         | 364        |
|    total_timesteps      | 47104      |
| train/                  |            |
|    approx_kl            | 0.00946646 |
|    clip_fraction        | 0.114      |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.913     |
|    explained_variance   | -0.0289    |
|    learning_rate        | 0.000291   |
|    loss                 | -0.0263    |
|    n_updates            | 220        |
|    policy_gradient_loss | -0.00383   |
|    value_loss           | 0.000368   |
----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.53       |
| time/                   |             |
|    fps                  | 129         |
|    iterations           | 24          |
|    time_elapsed         | 380         |
|    total_timesteps      | 49152       |
| train/                  |             |
|    approx_kl            | 0.010528388 |
|    clip_fraction        | 0.108       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.898      |
|    explained_variance   | 0.0218      |
|    learning_rate        | 0.000291    |
|    loss                 | -0.0258     |
|    n_updates            | 230         |
|    policy_gradient_loss | -0.00598    |
|    value_loss           | 0.00121     |

In [9]:
nb_episodes = 30

for episode in range(1, nb_episodes + 1):
    obs, _ = env.reset()
    print(f'Episode n˚{episode} -- Jeu de donnée {env.env.name}')
    done = False

    while not done:
        action, _states = model.predict(obs)
        obs, reward, terminated, truncated, _ = env.step(action.tolist())
        done = terminated or truncated
    env.env.save_for_render(dir="logs")        
    if terminated:
        print('Argent perdu')
        
    elif truncated:
        print('Épisode terminé')

Episode n˚1 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : 72.13%   |   Portfolio Valuation : 1721.32   |
Épisode terminé
Episode n˚2 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : 35.93%   |   Portfolio Valuation : 1359.32   |
Épisode terminé
Episode n˚3 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -6.34%   |   Portfolio Valuation : 936.55   |
Épisode terminé
Episode n˚4 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 946.44%   |   Portfolio Return : -86.14%   |   Portfolio Valuation : 138.56   |
Épisode terminé
Episode n˚5 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : 72.35%   |   Portfolio Valuation : 1723.53   |
Épisode terminé
Episode n˚6 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : 11.34%   |   Portfolio Valuation : 1113.44   |
Épisode terminé
Episode n˚7 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : 55.15%   |   Portfolio Valuation : 1551.51   |
Épisode terminé
Episode n˚8 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : -42.83%   |   Portfolio Valuation : 571.72   |
Épisode terminé
Episode n˚9 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -9.73%   |   Portfolio Valuation : 902.73   |
Épisode terminé
Episode n˚10 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 376.91%   |   Portfolio Return : -95.39%   |   Portfolio Valuation : 46.11   |
Épisode terminé
Episode n˚11 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : 32.08%   |   Portfolio Valuation : 1320.84   |
Épisode terminé
Episode n˚12 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : 28.36%   |   Portfolio Valuation : 1283.64   |
Épisode terminé
Episode n˚13 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -12.08%   |   Portfolio Valuation : 879.18   |
Épisode terminé
Episode n˚14 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 946.44%   |   Portfolio Return : -88.29%   |   Portfolio Valuation : 117.07   |
Épisode terminé
Episode n˚15 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : 24.66%   |   Portfolio Valuation : 1246.59   |
Épisode terminé
Episode n˚16 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : -11.27%   |   Portfolio Valuation : 887.26   |
Épisode terminé
Episode n˚17 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 376.91%   |   Portfolio Return : -97.53%   |   Portfolio Valuation : 24.65   |
Épisode terminé
Episode n˚18 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -11.80%   |   Portfolio Valuation : 881.97   |
Épisode terminé
Episode n˚19 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : 77.86%   |   Portfolio Valuation : 1778.57   |
Épisode terminé
Episode n˚20 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : 32.36%   |   Portfolio Valuation : 1323.58   |
Épisode terminé
Episode n˚21 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : 25.43%   |   Portfolio Valuation : 1254.33   |
Épisode terminé
Episode n˚22 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : 71.03%   |   Portfolio Valuation : 1710.3   |
Épisode terminé
Episode n˚23 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 946.44%   |   Portfolio Return : -74.33%   |   Portfolio Valuation : 256.66   |
Épisode terminé
Episode n˚24 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -9.01%   |   Portfolio Valuation : 909.89   |
Épisode terminé
Episode n˚25 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : 17.12%   |   Portfolio Valuation : 1171.19   |
Épisode terminé
Episode n˚26 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -15.17%   |   Portfolio Valuation : 848.32   |
Épisode terminé
Episode n˚27 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : 26.70%   |   Portfolio Valuation : 1267.01   |
Épisode terminé
Episode n˚28 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : -28.10%   |   Portfolio Valuation : 719.0   |
Épisode terminé
Episode n˚29 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 376.91%   |   Portfolio Return : -99.06%   |   Portfolio Valuation : 9.41   |
Épisode terminé
Episode n˚30 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : 107.72%   |   Portfolio Valuation : 2077.19   |
Épisode terminé

In [12]:
from typing import Callable

def linear_schedule(initial_value: float) -> Callable[[float], float]:
    def func(progress_remaining: float) -> float:
        return progress_remaining * initial_value
    return func

def preprocess_corrected(df):
    df = df.copy()
    
    df['feature_log_ret'] = np.log(df['close'] / df['close'].shift(1))

    df['feature_rsi'] = ta.rsi(df['close'], length=14) / 100.0 
    
    macd = ta.macd(df['close'])
    df['feature_macd_norm'] = macd['MACD_12_26_9'] / df['close']
    
    df['feature_atr_norm'] = ta.atr(df['high'], df['low'], df['close'], length=14) / df['close']
    
    df['feature_hour_sin'] = np.sin(2 * np.pi * df.index.hour / 24)
    df['feature_hour_cos'] = np.cos(2 * np.pi * df.index.hour / 24)

    df = df.dropna()
    
    df = df.replace([np.inf, -np.inf], 0)

    return df


def metric_portfolio_valuation(history):
    return round(history['portfolio_valuation', -1], 2)

def reward_function(history):
    return history['step']*(history['portfolio_valuation', -1] - history['portfolio_valuation', -2])

def reward_function_rapport_market(history):
    return 10*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1]))

def reward_function_rapport_market_v2(history):
    weight = 0 
    if (history['position',1] == history['position',-2]):
        weight = 0.1
    return 10*(history['data_open', -2] / history['data_close', -1])*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1])) - weight 

def reward_log_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = np.log(curr_val / prev_val)
    return reward

def reward_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = (curr_val - prev_val) / prev_val
    return reward

env = gym.make(
    "MultiDatasetTradingEnv",
    dataset_dir="data/*.pkl",
    preprocess=preprocess_corrected,
    reward_function=reward_returns,
    # Valeur initiale du portefeuille
    portfolio_initial_value=1_000,
    # Frais de transactions
    trading_fees=0.1/100,
    # Intérêts sur les prêts
    borrow_interest_rate=0.02/100/24,
)

env.add_metric('Portfolio Valuation', metric_portfolio_valuation)
env = DiscreteActionsWrapper(env, positions=[-0.5,0,0.5,1,1.5])
obs, _ = env.reset()

model = PPO("MlpPolicy",
            env,
            gamma=0.995, 
            gae_lambda=0.95,
            learning_rate=linear_schedule(0.0003), 
            ent_coef=0.1, 
            batch_size=64,
            n_steps=2048,
            verbose=1
)

model = model.learn(total_timesteps=1_500_000)
model.save("PPO_v12")

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
-----------------------------
| time/              |      |
|    fps             | 606  |
|    iterations      | 1    |
|    time_elapsed    | 3    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 283         |
|    iterations           | 2           |
|    time_elapsed         | 14          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.011826113 |
|    clip_fraction        | 0.0905      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.6        |
|    explained_variance   | -17.2       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.148      |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.00823    |
|    value_loss           | 0.00115     |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 244        |
|    iterations           | 3          |
|    time_elapsed         | 25         |
|    total_timesteps      | 6144       |
| train/                  |            |
|    approx_kl            | 0.00845019 |
|    clip_fraction        | 0.0468     |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.6       |
|    explained_variance   | -0.746     |
|    learning_rate        | 0.000299   |
|    loss                 | -0.152     |
|    n_updates            | 20         |
|    policy_gradient_loss | -0.00519   |
|    value_loss           | 0.000718   |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 260         |
|    iterations           | 4           |
|    time_elapsed         | 31          |
|    total_timesteps      | 8192        |
| train/                  |             |
|    approx_kl            | 0.006345199 |
|    clip_fraction        | 0.0222      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.58       |
|    explained_variance   | -0.109      |
|    learning_rate        | 0.000299    |
|    loss                 | -0.174      |
|    n_updates            | 30          |
|    policy_gradient_loss | -0.00412    |
|    value_loss           | 0.0006      |
-----------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 290          |
|    iterations           | 5            |
|    time_elapsed         | 35           |
|    total_timesteps      | 10240        |
| train/                  |              |
|    approx_kl            | 0.0053935247 |
|    clip_fraction        | 0.0334       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.58        |
|    explained_variance   | -0.0615      |
|    learning_rate        | 0.000298     |
|    loss                 | -0.169       |
|    n_updates            | 40           |
|    policy_gradient_loss | -0.00437     |
|    value_loss           | 0.000497     |
------------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 319          |
|    iterations           | 6            |
|    time_elapsed         | 38           |
|    total_timesteps      | 12288        |
| train/                  |              |
|    approx_kl            | 0.0058834273 |
|    clip_fraction        | 0.014        |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.58        |
|    explained_variance   | -0.195       |
|    learning_rate        | 0.000298     |
|    loss                 | -0.176       |
|    n_updates            | 50           |
|    policy_gradient_loss | -0.00217     |
|    value_loss           | 0.000298     |
------------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 340          |
|    iterations           | 7            |
|    time_elapsed         | 42           |
|    total_timesteps      | 14336        |
| train/                  |              |
|    approx_kl            | 0.0082392115 |
|    clip_fraction        | 0.0807       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.57        |
|    explained_variance   | -0.0503      |
|    learning_rate        | 0.000298     |
|    loss                 | -0.184       |
|    n_updates            | 60           |
|    policy_gradient_loss | -0.0108      |
|    value_loss           | 0.000294     |
------------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 358          |
|    iterations           | 8            |
|    time_elapsed         | 45           |
|    total_timesteps      | 16384        |
| train/                  |              |
|    approx_kl            | 0.0058240024 |
|    clip_fraction        | 0.0364       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.56        |
|    explained_variance   | -0.0207      |
|    learning_rate        | 0.000297     |
|    loss                 | -0.166       |
|    n_updates            | 70           |
|    policy_gradient_loss | -0.00407     |
|    value_loss           | 0.000339     |
------------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 337         |
|    iterations           | 9           |
|    time_elapsed         | 54          |
|    total_timesteps      | 18432       |
| train/                  |             |
|    approx_kl            | 0.009231487 |
|    clip_fraction        | 0.0582      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.56       |
|    explained_variance   | -0.174      |
|    learning_rate        | 0.000297    |
|    loss                 | -0.16       |
|    n_updates            | 80          |
|    policy_gradient_loss | -0.00708    |
|    value_loss           | 0.000649    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 312         |
|    iterations           | 10          |
|    time_elapsed         | 65          |
|    total_timesteps      | 20480       |
| train/                  |             |
|    approx_kl            | 0.007716469 |
|    clip_fraction        | 0.073       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.56       |
|    explained_variance   | -0.0938     |
|    learning_rate        | 0.000296    |
|    loss                 | -0.162      |
|    n_updates            | 90          |
|    policy_gradient_loss | -0.00823    |
|    value_loss           | 0.000241    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 297         |
|    iterations           | 11          |
|    time_elapsed         | 75          |
|    total_timesteps      | 22528       |
| train/                  |             |
|    approx_kl            | 0.007058029 |
|    clip_fraction        | 0.04        |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.54       |
|    explained_variance   | -0.0585     |
|    learning_rate        | 0.000296    |
|    loss                 | -0.164      |
|    n_updates            | 100         |
|    policy_gradient_loss | -0.00581    |
|    value_loss           | 0.000255    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 285         |
|    iterations           | 12          |
|    time_elapsed         | 86          |
|    total_timesteps      | 24576       |
| train/                  |             |
|    approx_kl            | 0.007099621 |
|    clip_fraction        | 0.0543      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.53       |
|    explained_variance   | -0.0154     |
|    learning_rate        | 0.000295    |
|    loss                 | -0.19       |
|    n_updates            | 110         |
|    policy_gradient_loss | -0.00709    |
|    value_loss           | 0.000133    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 274         |
|    iterations           | 13          |
|    time_elapsed         | 96          |
|    total_timesteps      | 26624       |
| train/                  |             |
|    approx_kl            | 0.010198459 |
|    clip_fraction        | 0.0777      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.49       |
|    explained_variance   | -0.341      |
|    learning_rate        | 0.000295    |
|    loss                 | -0.184      |
|    n_updates            | 120         |
|    policy_gradient_loss | -0.0114     |
|    value_loss           | 0.000156    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 267         |
|    iterations           | 14          |
|    time_elapsed         | 107         |
|    total_timesteps      | 28672       |
| train/                  |             |
|    approx_kl            | 0.008212733 |
|    clip_fraction        | 0.0718      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.48       |
|    explained_variance   | -0.0687     |
|    learning_rate        | 0.000295    |
|    loss                 | -0.151      |
|    n_updates            | 130         |
|    policy_gradient_loss | -0.00698    |
|    value_loss           | 0.000106    |
-----------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 263          |
|    iterations           | 15           |
|    time_elapsed         | 116          |
|    total_timesteps      | 30720        |
| train/                  |              |
|    approx_kl            | 0.0077881813 |
|    clip_fraction        | 0.086        |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.48        |
|    explained_variance   | -0.119       |
|    learning_rate        | 0.000294     |
|    loss                 | -0.153       |
|    n_updates            | 140          |
|    policy_gradient_loss | -0.00907     |
|    value_loss           | 0.000193     |
------------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 259         |
|    iterations           | 16          |
|    time_elapsed         | 126         |
|    total_timesteps      | 32768       |
| train/                  |             |
|    approx_kl            | 0.010000018 |
|    clip_fraction        | 0.093       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.48       |
|    explained_variance   | -0.075      |
|    learning_rate        | 0.000294    |
|    loss                 | -0.144      |
|    n_updates            | 150         |
|    policy_gradient_loss | -0.00809    |
|    value_loss           | 0.000157    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 256         |
|    iterations           | 17          |
|    time_elapsed         | 135         |
|    total_timesteps      | 34816       |
| train/                  |             |
|    approx_kl            | 0.008985577 |
|    clip_fraction        | 0.0689      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.47       |
|    explained_variance   | -0.0812     |
|    learning_rate        | 0.000293    |
|    loss                 | -0.154      |
|    n_updates            | 160         |
|    policy_gradient_loss | -0.00695    |
|    value_loss           | 0.000189    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 253         |
|    iterations           | 18          |
|    time_elapsed         | 145         |
|    total_timesteps      | 36864       |
| train/                  |             |
|    approx_kl            | 0.006389411 |
|    clip_fraction        | 0.049       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.47       |
|    explained_variance   | -0.121      |
|    learning_rate        | 0.000293    |
|    loss                 | -0.148      |
|    n_updates            | 170         |
|    policy_gradient_loss | -0.00454    |
|    value_loss           | 0.000138    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 251         |
|    iterations           | 19          |
|    time_elapsed         | 154         |
|    total_timesteps      | 38912       |
| train/                  |             |
|    approx_kl            | 0.007395849 |
|    clip_fraction        | 0.0365      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.46       |
|    explained_variance   | -0.0389     |
|    learning_rate        | 0.000293    |
|    loss                 | -0.182      |
|    n_updates            | 180         |
|    policy_gradient_loss | -0.0044     |
|    value_loss           | 0.000197    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 248         |
|    iterations           | 20          |
|    time_elapsed         | 164         |
|    total_timesteps      | 40960       |
| train/                  |             |
|    approx_kl            | 0.006831622 |
|    clip_fraction        | 0.0467      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.47       |
|    explained_variance   | -0.0339     |
|    learning_rate        | 0.000292    |
|    loss                 | -0.152      |
|    n_updates            | 190         |
|    policy_gradient_loss | -0.00431    |
|    value_loss           | 0.000278    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 246         |
|    iterations           | 21          |
|    time_elapsed         | 174         |
|    total_timesteps      | 43008       |
| train/                  |             |
|    approx_kl            | 0.008762222 |
|    clip_fraction        | 0.0752      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.46       |
|    explained_variance   | 0.0722      |
|    learning_rate        | 0.000292    |
|    loss                 | -0.172      |
|    n_updates            | 200         |
|    policy_gradient_loss | -0.0101     |
|    value_loss           | 0.000249    |
-----------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 250          |
|    iterations           | 22           |
|    time_elapsed         | 179          |
|    total_timesteps      | 45056        |
| train/                  |              |
|    approx_kl            | 0.0077582407 |
|    clip_fraction        | 0.0651       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.45        |
|    explained_variance   | -0.0518      |
|    learning_rate        | 0.000291     |
|    loss                 | -0.169       |
|    n_updates            | 210          |
|    policy_gradient_loss | -0.00779     |
|    value_loss           | 8.4e-05      |
------------------------------------------
Market Return : 699.62%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.0   |
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 4.62e+04     |
|    ep_rew_mean          | -28.4        |
| time/                   |              |
|    fps                  | 250          |
|    iterations           | 23           |
|    time_elapsed         | 187          |
|    total_timesteps      | 47104        |
| train/                  |              |
|    approx_kl            | 0.0073305108 |
|    clip_fraction        | 0.0603       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.47        |
|    explained_variance   | -0.0067      |
|    learning_rate        | 0.000291     |
|    loss                 | -0.155       |
|    n_updates            | 220          |
|    policy_gradient_loss | -0.00517     |
|    value_loss           | 8.89e-05     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 4.62e+04    |
|    ep_rew_mean          | -28.4       |
| time/                   |             |
|    fps                  | 249         |
|    iterations           | 24          |
|    time_elapsed         | 196         |
|    total_timesteps      | 49152       |
| train/                  |             |
|    approx_kl            | 0.011839525 |
|    clip_fraction        | 0.125       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.48       |
|    explained_variance   | 0.107       |
|    learning_rate        | 0.000291    |
|    loss                 | -0.159      |
|    n_updates            | 230         |
|    policy_gradient_loss | -0.00964    |
|    value_loss           | 0.000333    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 4.62e+04    |
|    ep_rew_mean          | -28.4       |
| time/                   |             |
|    fps                  | 248         |
|    iterations           | 25          |
|    time_elapsed         | 205         |
|    total_timesteps      | 51200       |
| train/                  |             |
|    approx_kl            | 0.009938381 |
|    clip_fraction        | 0.0726      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.5        |
|    explained_variance   | -0.0974     |
|    learning_rate        | 0.00029     |
|    loss                 | -0.157      |
|    n_updates            | 240         |
|    policy_gradient_loss | -0.00583    |
|    value_loss           | 0.000302    |
-----------------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 4.62e+04   |
|    ep_rew_mean          | -28.4      |
| time/                   |            |
|    fps                  | 247        |
|    iterations           | 26         |
|    time_elapsed         | 215        |
|    total_timesteps      | 53248      |
| train/                  |            |
|    approx_kl            | 0.00815087 |
|    clip_fraction        | 0.0607     |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.5       |
|    explained_variance   | -0.0462    |
|    learning_rate        | 0.00029    |
|    loss                 | -0.177     |
|    n_updates            | 250        |
|    policy_gradient_loss | -0.00628   |
|    value_loss           | 0.00133    |
----------------------------------------
-----------------------------------------
| rollout/                |             |

In [13]:
nb_episodes = 30

for episode in range(1, nb_episodes + 1):
    obs, _ = env.reset()
    print(f'Episode n˚{episode} -- Jeu de donnée {env.env.name}')
    done = False

    while not done:
        action, _states = model.predict(obs)
        obs, reward, terminated, truncated, _ = env.step(action.tolist())
        done = terminated or truncated
    env.env.save_for_render(dir="logs")        
    if terminated:
        print('Argent perdu')
        
    elif truncated:
        print('Épisode terminé')

Episode n˚1 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -99.82%   |   Portfolio Valuation : 1.83   |
Épisode terminé
Episode n˚2 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : -72.91%   |   Portfolio Valuation : 270.86   |
Épisode terminé
Episode n˚3 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -90.77%   |   Portfolio Valuation : 92.35   |
Épisode terminé
Episode n˚4 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : -90.97%   |   Portfolio Valuation : 90.25   |
Épisode terminé
Episode n˚5 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : -99.68%   |   Portfolio Valuation : 3.17   |
Épisode terminé
Episode n˚6 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 376.91%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.0   |
Épisode terminé
Episode n˚7 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.0   |
Épisode terminé
Episode n˚8 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : -81.14%   |   Portfolio Valuation : 188.63   |
Épisode terminé
Episode n˚9 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 946.44%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.0   |
Épisode terminé
Episode n˚10 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : -99.50%   |   Portfolio Valuation : 4.96   |
Épisode terminé
Episode n˚11 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 376.91%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.0   |
Épisode terminé
Episode n˚12 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : -82.13%   |   Portfolio Valuation : 178.66   |
Épisode terminé
Episode n˚13 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 946.44%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.0   |
Épisode terminé
Episode n˚14 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -91.50%   |   Portfolio Valuation : 85.0   |
Épisode terminé
Episode n˚15 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.0   |
Épisode terminé
Episode n˚16 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : -89.91%   |   Portfolio Valuation : 100.9   |
Épisode terminé
Episode n˚17 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : -85.02%   |   Portfolio Valuation : 149.78   |
Épisode terminé
Episode n˚18 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -99.82%   |   Portfolio Valuation : 1.81   |
Épisode terminé
Episode n˚19 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -91.24%   |   Portfolio Valuation : 87.61   |
Épisode terminé
Episode n˚20 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -99.81%   |   Portfolio Valuation : 1.85   |
Épisode terminé
Episode n˚21 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 946.44%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.0   |
Épisode terminé
Episode n˚22 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : -80.62%   |   Portfolio Valuation : 193.8   |
Épisode terminé
Episode n˚23 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 376.91%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.0   |
Épisode terminé
Episode n˚24 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : -99.54%   |   Portfolio Valuation : 4.64   |
Épisode terminé
Episode n˚25 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : -90.72%   |   Portfolio Valuation : 92.79   |
Épisode terminé
Episode n˚26 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.0   |
Épisode terminé
Episode n˚27 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : -88.50%   |   Portfolio Valuation : 115.03   |
Épisode terminé
Episode n˚28 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -92.21%   |   Portfolio Valuation : 77.95   |
Épisode terminé
Episode n˚29 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : -82.52%   |   Portfolio Valuation : 174.84   |
Épisode terminé
Episode n˚30 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : -83.87%   |   Portfolio Valuation : 161.32   |
Épisode terminé

In [14]:
from typing import Callable

def linear_schedule(initial_value: float) -> Callable[[float], float]:
    def func(progress_remaining: float) -> float:
        return progress_remaining * initial_value
    return func

def preprocess_corrected(df):
    df = df.copy()
    
    df['feature_log_ret'] = np.log(df['close'] / df['close'].shift(1))

    df['feature_rsi'] = ta.rsi(df['close'], length=14) / 100.0 
    
    macd = ta.macd(df['close'])
    df['feature_macd_norm'] = macd['MACD_12_26_9'] / df['close']
    
    df['feature_atr_norm'] = ta.atr(df['high'], df['low'], df['close'], length=14) / df['close']
    
    df['feature_hour_sin'] = np.sin(2 * np.pi * df.index.hour / 24)
    df['feature_hour_cos'] = np.cos(2 * np.pi * df.index.hour / 24)

    df = df.dropna()
    
    df = df.replace([np.inf, -np.inf], 0)

    return df


def metric_portfolio_valuation(history):
    return round(history['portfolio_valuation', -1], 2)

def reward_function(history):
    return history['step']*(history['portfolio_valuation', -1] - history['portfolio_valuation', -2])

def reward_function_rapport_market(history):
    return 10*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1]))

def reward_function_rapport_market_v2(history):
    weight = 0 
    if (history['position',1] == history['position',-2]):
        weight = 0.1
    return 10*(history['data_open', -2] / history['data_close', -1])*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1])) - weight 

def reward_log_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = np.log(curr_val / prev_val)
    return reward

def reward_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = (curr_val - prev_val) / prev_val
    return reward

env = gym.make(
    "MultiDatasetTradingEnv",
    dataset_dir="data/*.pkl",
    preprocess=preprocess_corrected,
    reward_function=reward_returns,
    # Valeur initiale du portefeuille
    portfolio_initial_value=1_000,
    # Frais de transactions
    trading_fees=0.1/100,
    # Intérêts sur les prêts
    borrow_interest_rate=0.02/100/24,
)

env.add_metric('Portfolio Valuation', metric_portfolio_valuation)
env = DiscreteActionsWrapper(env, positions=[-0.5,0,0.5,1,1.5])
obs, _ = env.reset()

model = PPO("MlpPolicy",
            env,
            gamma=0.995, 
            gae_lambda=0.95,
            learning_rate=linear_schedule(0.0003), 
            ent_coef=0.03, 
            batch_size=64,
            n_steps=2048,
            verbose=1
)

model = model.learn(total_timesteps=1_500_000)
model.save("PPO_v13")

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
-----------------------------
| time/              |      |
|    fps             | 344  |
|    iterations      | 1    |
|    time_elapsed    | 5    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 278         |
|    iterations           | 2           |
|    time_elapsed         | 14          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.009594653 |
|    clip_fraction        | 0.077       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.6        |
|    explained_variance   | -26.9       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0819     |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.00728    |
|    value_loss           | 0.00051     |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 260         |
|    iterations           | 3           |
|    time_elapsed         | 23          |
|    total_timesteps      | 6144        |
| train/                  |             |
|    approx_kl            | 0.011583422 |
|    clip_fraction        | 0.0951      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.59       |
|    explained_variance   | -6.01       |
|    learning_rate        | 0.000299    |
|    loss                 | -0.0805     |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.00728    |
|    value_loss           | 4.05e-05    |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 273        |
|    iterations           | 4          |
|    time_elapsed         | 29         |
|    total_timesteps      | 8192       |
| train/                  |            |
|    approx_kl            | 0.01132763 |
|    clip_fraction        | 0.134      |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.56      |
|    explained_variance   | -3.07      |
|    learning_rate        | 0.000299   |
|    loss                 | -0.0592    |
|    n_updates            | 30         |
|    policy_gradient_loss | -0.016     |
|    value_loss           | 1.94e-05   |
----------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 294          |
|    iterations           | 5            |
|    time_elapsed         | 34           |
|    total_timesteps      | 10240        |
| train/                  |              |
|    approx_kl            | 0.0117773805 |
|    clip_fraction        | 0.126        |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.53        |
|    explained_variance   | -0.678       |
|    learning_rate        | 0.000298     |
|    loss                 | -0.0333      |
|    n_updates            | 40           |
|    policy_gradient_loss | -0.0139      |
|    value_loss           | 2.32e-05     |
------------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 309        |
|    iterations           | 6          |
|    time_elapsed         | 39         |
|    total_timesteps      | 12288      |
| train/                  |            |
|    approx_kl            | 0.01228869 |
|    clip_fraction        | 0.154      |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.47      |
|    explained_variance   | -0.276     |
|    learning_rate        | 0.000298   |
|    loss                 | -0.0645    |
|    n_updates            | 50         |
|    policy_gradient_loss | -0.0157    |
|    value_loss           | 2.03e-05   |
----------------------------------------
Market Return :  5.93%   |   Portfolio Return : -99.98%   |   Portfolio Valuation : 0.15   |
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.77       |
| time/                   |             |
|    fps                  | 323         |
|    iterations           | 7           |
|    time_elapsed         | 44          |
|    total_timesteps      | 14336       |
| train/                  |             |
|    approx_kl            | 0.012198826 |
|    clip_fraction        | 0.151       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.4        |
|    explained_variance   | -0.434      |
|    learning_rate        | 0.000298    |
|    loss                 | -0.0545     |
|    n_updates            | 60          |
|    policy_gradient_loss | -0.019      |
|    value_loss           | 1.34e-05    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.77       |
| time/                   |             |
|    fps                  | 332         |
|    iterations           | 8           |
|    time_elapsed         | 49          |
|    total_timesteps      | 16384       |
| train/                  |             |
|    approx_kl            | 0.008123267 |
|    clip_fraction        | 0.0852      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.37       |
|    explained_variance   | -0.122      |
|    learning_rate        | 0.000297    |
|    loss                 | -0.0498     |
|    n_updates            | 70          |
|    policy_gradient_loss | -0.00781    |
|    value_loss           | 0.00863     |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.77       |
| time/                   |             |
|    fps                  | 345         |
|    iterations           | 9           |
|    time_elapsed         | 53          |
|    total_timesteps      | 18432       |
| train/                  |             |
|    approx_kl            | 0.009408079 |
|    clip_fraction        | 0.084       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.32       |
|    explained_variance   | 0.00101     |
|    learning_rate        | 0.000297    |
|    loss                 | -0.0231     |
|    n_updates            | 80          |
|    policy_gradient_loss | -0.00916    |
|    value_loss           | 0.00428     |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.77       |
| time/                   |             |
|    fps                  | 355         |
|    iterations           | 10          |
|    time_elapsed         | 57          |
|    total_timesteps      | 20480       |
| train/                  |             |
|    approx_kl            | 0.006449921 |
|    clip_fraction        | 0.0336      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.31       |
|    explained_variance   | -0.089      |
|    learning_rate        | 0.000296    |
|    loss                 | -0.0595     |
|    n_updates            | 90          |
|    policy_gradient_loss | -0.00384    |
|    value_loss           | 0.00137     |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.24e+04     |
|    ep_rew_mean          | -8.77        |
| time/                   |              |
|    fps                  | 363          |
|    iterations           | 11           |
|    time_elapsed         | 61           |
|    total_timesteps      | 22528        |
| train/                  |              |
|    approx_kl            | 0.0069683734 |
|    clip_fraction        | 0.0392       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.32        |
|    explained_variance   | -0.0309      |
|    learning_rate        | 0.000296     |
|    loss                 | -0.0333      |
|    n_updates            | 100          |
|    policy_gradient_loss | -0.00406     |
|    value_loss           | 0.00113      |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.77       |
| time/                   |             |
|    fps                  | 365         |
|    iterations           | 12          |
|    time_elapsed         | 67          |
|    total_timesteps      | 24576       |
| train/                  |             |
|    approx_kl            | 0.007864435 |
|    clip_fraction        | 0.0599      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.3        |
|    explained_variance   | 0.0218      |
|    learning_rate        | 0.000295    |
|    loss                 | -0.0717     |
|    n_updates            | 110         |
|    policy_gradient_loss | -0.00861    |
|    value_loss           | 0.000812    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.77       |
| time/                   |             |
|    fps                  | 370         |
|    iterations           | 13          |
|    time_elapsed         | 71          |
|    total_timesteps      | 26624       |
| train/                  |             |
|    approx_kl            | 0.008285454 |
|    clip_fraction        | 0.0508      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.33       |
|    explained_variance   | -0.0574     |
|    learning_rate        | 0.000295    |
|    loss                 | -0.0462     |
|    n_updates            | 120         |
|    policy_gradient_loss | -0.00376    |
|    value_loss           | 0.000879    |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.24e+04     |
|    ep_rew_mean          | -8.77        |
| time/                   |              |
|    fps                  | 375          |
|    iterations           | 14           |
|    time_elapsed         | 76           |
|    total_timesteps      | 28672        |
| train/                  |              |
|    approx_kl            | 0.0082028825 |
|    clip_fraction        | 0.0318       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.31        |
|    explained_variance   | -0.00192     |
|    learning_rate        | 0.000295     |
|    loss                 | -0.0576      |
|    n_updates            | 130          |
|    policy_gradient_loss | -0.00455     |
|    value_loss           | 0.000456     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.77       |
| time/                   |             |
|    fps                  | 379         |
|    iterations           | 15          |
|    time_elapsed         | 80          |
|    total_timesteps      | 30720       |
| train/                  |             |
|    approx_kl            | 0.011138359 |
|    clip_fraction        | 0.0829      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.27       |
|    explained_variance   | -0.0438     |
|    learning_rate        | 0.000294    |
|    loss                 | -0.0509     |
|    n_updates            | 140         |
|    policy_gradient_loss | -0.00848    |
|    value_loss           | 0.00157     |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.24e+04     |
|    ep_rew_mean          | -8.77        |
| time/                   |              |
|    fps                  | 382          |
|    iterations           | 16           |
|    time_elapsed         | 85           |
|    total_timesteps      | 32768        |
| train/                  |              |
|    approx_kl            | 0.0067055444 |
|    clip_fraction        | 0.0592       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.23        |
|    explained_variance   | -0.0928      |
|    learning_rate        | 0.000294     |
|    loss                 | -0.0463      |
|    n_updates            | 150          |
|    policy_gradient_loss | -0.0076      |
|    value_loss           | 0.000459     |
------------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.24e+04     |
|    ep_rew_mean          | -8.77        |
| time/                   |              |
|    fps                  | 385          |
|    iterations           | 17           |
|    time_elapsed         | 90           |
|    total_timesteps      | 34816        |
| train/                  |              |
|    approx_kl            | 0.0062174676 |
|    clip_fraction        | 0.0475       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.23        |
|    explained_variance   | -0.0443      |
|    learning_rate        | 0.000293     |
|    loss                 | -0.041       |
|    n_updates            | 160          |
|    policy_gradient_loss | -0.00472     |
|    value_loss           | 0.000647     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.77       |
| time/                   |             |
|    fps                  | 388         |
|    iterations           | 18          |
|    time_elapsed         | 94          |
|    total_timesteps      | 36864       |
| train/                  |             |
|    approx_kl            | 0.006429107 |
|    clip_fraction        | 0.0445      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.21       |
|    explained_variance   | -0.0755     |
|    learning_rate        | 0.000293    |
|    loss                 | -0.00671    |
|    n_updates            | 170         |
|    policy_gradient_loss | -0.00419    |
|    value_loss           | 0.000556    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.77       |
| time/                   |             |
|    fps                  | 390         |
|    iterations           | 19          |
|    time_elapsed         | 99          |
|    total_timesteps      | 38912       |
| train/                  |             |
|    approx_kl            | 0.006976058 |
|    clip_fraction        | 0.0615      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.19       |
|    explained_variance   | -0.0563     |
|    learning_rate        | 0.000293    |
|    loss                 | -0.0686     |
|    n_updates            | 180         |
|    policy_gradient_loss | -0.00523    |
|    value_loss           | 0.000214    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.77       |
| time/                   |             |
|    fps                  | 392         |
|    iterations           | 20          |
|    time_elapsed         | 104         |
|    total_timesteps      | 40960       |
| train/                  |             |
|    approx_kl            | 0.005797233 |
|    clip_fraction        | 0.051       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.16       |
|    explained_variance   | -0.0306     |
|    learning_rate        | 0.000292    |
|    loss                 | -0.0646     |
|    n_updates            | 190         |
|    policy_gradient_loss | -0.00558    |
|    value_loss           | 0.000447    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.77       |
| time/                   |             |
|    fps                  | 394         |
|    iterations           | 21          |
|    time_elapsed         | 109         |
|    total_timesteps      | 43008       |
| train/                  |             |
|    approx_kl            | 0.009557974 |
|    clip_fraction        | 0.0517      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.18       |
|    explained_variance   | 0.000413    |
|    learning_rate        | 0.000292    |
|    loss                 | -0.0462     |
|    n_updates            | 200         |
|    policy_gradient_loss | -0.00361    |
|    value_loss           | 0.00155     |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1.24e+04     |
|    ep_rew_mean          | -8.77        |
| time/                   |              |
|    fps                  | 397          |
|    iterations           | 22           |
|    time_elapsed         | 113          |
|    total_timesteps      | 45056        |
| train/                  |              |
|    approx_kl            | 0.0030929092 |
|    clip_fraction        | 0.0168       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.17        |
|    explained_variance   | -0.0237      |
|    learning_rate        | 0.000291     |
|    loss                 | -0.0391      |
|    n_updates            | 210          |
|    policy_gradient_loss | -0.0024      |
|    value_loss           | 0.000516     |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.77       |
| time/                   |             |
|    fps                  | 399         |
|    iterations           | 23          |
|    time_elapsed         | 117         |
|    total_timesteps      | 47104       |
| train/                  |             |
|    approx_kl            | 0.007083819 |
|    clip_fraction        | 0.0694      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.13       |
|    explained_variance   | 0.0243      |
|    learning_rate        | 0.000291    |
|    loss                 | -0.0441     |
|    n_updates            | 220         |
|    policy_gradient_loss | -0.00646    |
|    value_loss           | 0.000602    |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.24e+04    |
|    ep_rew_mean          | -8.77       |
| time/                   |             |
|    fps                  | 401         |
|    iterations           | 24          |
|    time_elapsed         | 122         |
|    total_timesteps      | 49152       |
| train/                  |             |
|    approx_kl            | 0.005329762 |
|    clip_fraction        | 0.0429      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.11       |
|    explained_variance   | -0.0072     |
|    learning_rate        | 0.000291    |
|    loss                 | -0.0291     |

KeyboardInterrupt:

In [ ]:
nb_episodes = 30

for episode in range(1, nb_episodes + 1):
    obs, _ = env.reset()
    print(f'Episode n˚{episode} -- Jeu de donnée {env.env.name}')
    done = False

    while not done:
        action, _states = model.predict(obs)
        obs, reward, terminated, truncated, _ = env.step(action.tolist())
        done = terminated or truncated
    env.env.save_for_render(dir="logs")        
    if terminated:
        print('Argent perdu')
        
    elif truncated:
        print('Épisode terminé')